#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/internal/workflow/all/all_workflows_gen.go"
MODULE_PATH="github.com/yyhuni/lunafox/worker"

WORKFLOWS=()
while IFS= read -r wf; do
  WORKFLOWS+=("${wf}")
done < <(
  find "${ROOT_DIR}/internal/workflow" -mindepth 1 -maxdepth 1 -type d \
    | xargs -n1 basename \
    | grep -vE '^(all)$' \
    | sort
)

{
  echo "// Code generated by scripts/gen-workflow-imports.sh. DO NOT EDIT."
  echo "//go:generate bash ../../../scripts/gen-workflow-imports.sh"
  echo
  echo "package all"
  echo
  echo "import ("
  echo "	// Register built-in workflows."
  for wf in "${WORKFLOWS[@]}"; do
    if [[ -f "${ROOT_DIR}/internal/workflow/${wf}/workflow.go" ]]; then
      echo "	_ \"${MODULE_PATH}/internal/workflow/${wf}\""
    fi
  done
  echo ")"
} > "${OUTPUT_FILE}"

echo "generated ${OUTPUT_FILE}"
