package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/yyhuni/lunafox/worker/internal/workflow"
	"gopkg.in/yaml.v3"
)

type TemplateFile struct {
	Metadata workflow.WorkflowMetadata         `yaml:"metadata"`
	Tools    map[string]map[string]interface{} `yaml:"tools"`
}

func main() {
	inputFile := flag.String("input", "", "Input templates.yaml file")
	outputFile := flag.String("output", "", "Output Go constants file")
	packageName := flag.String("package", "subdomain_discovery", "Package name")
	flag.Parse()

	if *inputFile == "" || *outputFile == "" {
		fmt.Fprintf(os.Stderr, "Usage: const-gen -input <templates.yaml> -output <constants.go> [-package <name>]\n")
		os.Exit(1)
	}

	// Read input file
	data, err := os.ReadFile(*inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading input file: %v\n", err)
		os.Exit(1)
	}

	// Parse YAML
	var templateFile TemplateFile
	if err := yaml.Unmarshal(data, &templateFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing YAML: %v\n", err)
		os.Exit(1)
	}

	// Generate Go code
	var sb strings.Builder

	// File header
	fmt.Fprintf(&sb, "// Code generated by const-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Source: %s\n\n", *inputFile)
	fmt.Fprintf(&sb, "package %s\n\n", *packageName)

	// Stage constants
	fmt.Fprintf(&sb, "// Stage name constants (auto-generated from templates.yaml)\n")
	fmt.Fprintf(&sb, "const (\n")
	for _, stage := range templateFile.Metadata.Stages {
		constName := toCamelCase("stage_" + stage.ID)
		fmt.Fprintf(&sb, "\t%s = %q\n", constName, stage.ID)
	}
	fmt.Fprintf(&sb, ")\n\n")

	// Tool constants
	toolNames := make([]string, 0, len(templateFile.Tools))
	for toolName := range templateFile.Tools {
		toolNames = append(toolNames, toolName)
	}
	sort.Strings(toolNames)

	fmt.Fprintf(&sb, "// Tool name constants (auto-generated from templates.yaml)\n")
	fmt.Fprintf(&sb, "const (\n")
	for _, toolName := range toolNames {
		constName := toCamelCase("tool_" + toolName)
		fmt.Fprintf(&sb, "\t%s = %q\n", constName, toolName)
	}
	fmt.Fprintf(&sb, ")\n")

	// Write output file
	if err := os.WriteFile(*outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated constants in %s\n", *outputFile)
}

// toCamelCase converts "stage_recon-tools" to "stageReconTools"
func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})

	for i := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(parts[i])
		} else {
			parts[i] = strings.Title(parts[i])
		}
	}

	return strings.Join(parts, "")
}
