# Generated by Django 5.2.7 on 2026-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_add_screenshot_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='status_code',
            field=models.SmallIntegerField(blank=True, help_text='HTTP 响应状态码', null=True),
        ),
        migrations.AddField(
            model_name='screenshotsnapshot',
            name='status_code',
            field=models.SmallIntegerField(blank=True, help_text='HTTP 响应状态码', null=True),
        ),
    ]
