# Generated by Django 5.2.7 on 2026-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='cached_screenshots_count',
            field=models.IntegerField(default=0, help_text='缓存的截图数量'),
        ),
    ]
