export {
  DetailDrawer,
  DetailDrawerTabs,
  DetailDrawerTabsContent,
  DetailDrawerTabsList,
  DetailDrawerTabsTrigger,
  DETAIL_DRAWER_COMPACT_BODY_CLASS,
  DETAIL_DRAWER_COMPACT_FIELD_GRID_CLASS,
  DETAIL_DRAWER_COMPACT_FOOTER_CLASS,
  DETAIL_DRAWER_COMPACT_GUTTER_CLASS,
  DETAIL_DRAWER_COMPACT_INSET_CLASS,
  DETAIL_DRAWER_COMPACT_SECTION_STACK_CLASS,
} from "./detail-drawer"
