import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/auth/visual-split-login.tsx"), "utf8")

describe("visual-split-login contract", () => {
  it("keeps the visual split login focused on the real password auth path", () => {
    expect(source).toContain("export function VisualSplitLogin")
    expect(source).toContain("translations: VisualSplitLoginTranslations")
    expect(source).toContain("dynamic(")
    expect(source).toContain("import(\"@/components/faulty-terminal\")")
    expect(source).toContain("ssr: false")
    expect(source).toContain("<FaultyTerminal")
    expect(source).toContain('tint="var(--primary)"')
    expect(source).toContain('backgroundColor="var(--background)"')
    expect(source).toContain("mouseReact={false}")
    expect(source).toContain("maxFps={30}")
    expect(source).toContain("shaderReady")
    expect(source).toContain("shaderDecisionResolved")
    expect(source).toContain("onVisualReady")
    expect(source).toContain("handleShaderFirstFrame")
    expect(source).toContain("data-shader-ready")
    expect(source).toContain("onFirstFrame={handleShaderFirstFrame}")
    expect(source).toContain("usePublicLoginVisual")
    expect(source).toContain("PublishedLoginVisual")
    expect(source).toContain("data-login-visual-kind")
    expect(source).toContain("onError={handleFailure}")
    expect(source).not.toContain("auth-shader-fallback__dots")
    expect(source).not.toContain("auth-shader-fallback__dot")
    expect(source).toContain("import { LunaFoxMark }")
    expect(source).toContain("<LunaFoxMark")
    expect(source).toContain("aria-label={t.ariaLabel}")
    expect(source).toContain("Welcome to LunaFox")
    expect(source).toContain("Sign In.")
    expect(source).toContain("NEXT_PUBLIC_IMAGE_TAG")
    expect(source).toContain("appVersion")
    expect(source).toContain("{t.consoleLabel}")
    expect(source).toContain("{t.usernameLabel}")
    expect(source).toContain("{t.accessHelp}")
  })

  it("only enables the WebGL login shader when the browser budget is healthy", () => {
    expect(source).not.toContain("import FaultyTerminal")
    expect(source).toContain("useLoginShaderEnabled")
    expect(source).toContain("(prefers-reduced-motion: reduce)")
    expect(source).toContain("useReducedMotion")
    expect(source).toContain("visual?.kind === \"video\" && reducedMotion ? visual.posterUrl")
    expect(source).toContain("onCanPlay={handleReady}")
    expect(source).toContain("(pointer: fine)")
    expect(source).toContain("(min-width: 768px)")
    expect(source).toContain("navigator.hardwareConcurrency")
    expect(source).toContain("canCreateWebGLContext")
    expect(source).toContain("saveData")
    expect(source).toContain("effectiveType")
    expect(source).toContain("{shaderEnabled ? (")
  })

  it("does not expose unsupported secondary auth or account flows", () => {
    expect(source).not.toContain("Sign in with Google")
    expect(source).not.toContain("Sign in with Github")
    expect(source).not.toContain("Create an account")
    expect(source).not.toContain("Forgot Password?")
    expect(source).not.toContain("Remember this device")
  })
})
