"use client"
import { useTranslations } from "next-intl"
import { DetailDrawer, DETAIL_DRAWER_COMPACT_BODY_CLASS, DETAIL_DRAWER_COMPACT_FIELD_GRID_CLASS } from "@/components/shared/detail-drawer"
import { Skeleton } from "@/components/ui/skeleton"
import { textRole } from "@/lib/typography"
import { cn } from "@/lib/utils"
import type { FingerPrintHubFingerprintDetail, JsonValue } from "@/types/fingerprint.types"
import { formatFingerprintFieldValue, getFingerprintTextListPresentation } from "./fingerprint-field-display"
type Props = { inspection: { source: "fingerprinthub"; fingerprint: FingerPrintHubFingerprintDetail | null } | null; open: boolean; onOpenChange: (open: boolean) => void; formatDate: (value: string) => string; loading?: boolean }
export function FingerprintDetailDrawer({ inspection, open, onOpenChange, formatDate, loading = false }: Props) { const t = useTranslations("tools.fingerprints"); const fingerprint = inspection?.fingerprint; return <DetailDrawer open={open} onOpenChange={onOpenChange} title={fingerprint?.displayName ?? ""} description={t("fingerprinthub.detailsTitle")}>{loading ? <Loading /> : null}{fingerprint ? <div className={DETAIL_DRAWER_COMPACT_BODY_CLASS}><dl className={DETAIL_DRAWER_COMPACT_FIELD_GRID_CLASS}><Fields fingerprint={fingerprint} formatDate={formatDate} /></dl></div> : null}</DetailDrawer> }
function Fields({ fingerprint, formatDate }: { fingerprint: FingerPrintHubFingerprintDetail; formatDate: (value: string) => string }) { const values = Object.entries(fingerprint).filter(([key]) => !["name", "createdAt", "updatedAt", "additionalFields"].includes(key)) as Array<[string, JsonValue | string | null]>; values.push(["createdAt", formatDate(fingerprint.createdAt)], ["updatedAt", formatDate(fingerprint.updatedAt)]); return <>{values.map(([key, value]) => <Field key={key} label={key} value={formatFingerprintFieldValue("fingerprinthub", key, value) ?? null} monospace={getFingerprintTextListPresentation("fingerprinthub", key)?.monospace} />)}{fingerprint.additionalFields.map((field) => <Field key={field.path} label={field.path} value={field.value} />)}</> }
function Loading() { return <div className={DETAIL_DRAWER_COMPACT_BODY_CLASS} aria-busy="true"><div className={DETAIL_DRAWER_COMPACT_FIELD_GRID_CLASS}>{Array.from({ length: 8 }, (_, index) => <Skeleton key={index} className="h-12 w-full" />)}</div></div> }
function Field({ label, value, monospace = false }: { label: string; value: JsonValue | string | null; monospace?: boolean }) { const complex = typeof value === "object" && value !== null; return <div className={cn("min-w-0 space-y-1", complex && "sm:col-span-2")}><dt className={textRole.metadataLabel}>{label}</dt><dd className={cn(textRole.metadataValueStrong, "break-words whitespace-pre-wrap", monospace && textRole.code)}>{complex ? <pre className={cn(textRole.code, "max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-md border bg-muted/30 p-3")}>{JSON.stringify(value, null, 2)}</pre> : value || "-"}</dd></div> }
