import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/overview/agent-globe-card.tsx"), "utf8")

describe("agent-globe-card contract", () => {
  it("uses Cobe as a lightweight visual preview", () => {
    expect(source).toContain("createGlobe")
    expect(source).toContain("CobePreviewGlobe")
    expect(source).toContain("PREVIEW_MARKERS")
    expect(source).not.toContain("COBE: The 5KB WebGL")
  })

  it("binds agent node summary data without requiring coordinates", () => {
    expect(source).toContain("useAgents")
    expect(source).toContain("buildAgentSummary")
    expect(source).toContain('useTranslations("overview.agentGlobe")')
    expect(source).toContain('label: t("metrics.onlineNodes.label")')
    expect(source).toContain('label: t("metrics.abnormalNodes.label")')
    expect(source).not.toContain("高负载数量")
    expect(source).not.toContain("离线数量")
    expect(source).not.toContain("buildDistributedGlobeMarkers")
  })

  it("uses typography foundation for readable copy", () => {
    expect(source).toContain("textRole")
    expect(source).toContain('{t("title")}')
    expect(source).not.toContain("<Globe className=")
  })

  it("keeps the readable shell and Cobe globe synchronized with the active theme", () => {
    expect(source).toContain("useColorTheme")
    expect(source).toContain("currentTheme")
    expect(source).toContain("buildThemeSyncedCobeGlobeTheme")
    expect(source).toContain("hexToCobeColor")
    expect(source).toContain("mixCobeColor")
    expect(source).toContain("markerColor: accentColor")
    expect(source).toContain("arcColor: accentColor")
    expect(source).toContain("glowColor: mixCobeColor")
    expect(source).toContain('data-cobe-theme={theme.id}')
    expect(source).toContain("overview-agent-globe-shell")
    expect(source).toContain("bg-card")
    expect(source).toContain("text-card-foreground")
    expect(source).toContain("bg-popover")
    expect(source).toContain("text-popover-foreground")
    expect(source).not.toContain("OFFICIAL_COBE_GLOBE_THEMES")
    expect(source).not.toContain("markerColor: [0.3, 0.45, 0.85]")
    expect(source).not.toContain("arcColor: [0.3, 0.45, 0.85]")
    expect(source).not.toContain("markerColor: [0.2, 0.8, 0.9]")
    expect(source).not.toContain("arcColor: [0.3, 0.85, 0.95]")
    expect(source).not.toContain("bg-white")
    expect(source).not.toContain("text-slate-")
    expect(source).not.toContain("border-slate-")
    expect(source).not.toContain("baseColor: isDarkTheme")
    expect(source).not.toContain("markerColor: isDarkTheme")
    expect(source).not.toContain("arcColor: isDarkTheme")
  })

  it("defers Cobe sizing to ResizeObserver without forcing initial layout", () => {
    expect(source).toContain("ResizeObserver")
    expect(source).toContain("entry.contentRect.width")
    expect(source).toContain("startGlobe")
    expect(source).not.toContain("canvas.offsetWidth")
  })

  it("keeps internal layout restrained with a divided summary and centered globe", () => {
    expect(source).toContain("overview-reveal")
    expect(source).not.toContain("overview-delay-1")
    expect(source).toContain("overview-number-swap")
    expect(source).not.toContain("relative self-start gap-3")
    expect(source).not.toContain("min-h-[560px]")
    expect(source).toContain("relative z-10 grid flex-1 grid-rows-[auto_1fr] gap-3")
    expect(source).toContain("grid grid-cols-2 border-b pb-4")
    expect(source).not.toContain("grid min-h-[132px] grid-cols-2 border-b pb-4")
    expect(source).toContain("border-r pr-4 last:border-r-0")
    expect(source).toContain("icon: CheckCircle2")
    expect(source).toContain("icon: AlertTriangle")
    expect(source).toContain("flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary")
    expect(source).toContain("textRole.bodyStrong")
    expect(source).toContain("flex min-w-0 items-center justify-center")
    expect(source).toContain("max-w-[240px]")
    expect(source).not.toContain("节点运行状态")
    expect(source).not.toContain("Mock 数据")
    expect(source).not.toContain("getAgentLoad")
    expect(source).not.toContain("getAgentStatus")
    expect(source).not.toContain("rounded-xl border bg-white/80")
    expect(source).not.toContain("text-blue-600")
    expect(source).not.toContain("text-emerald-600")
    expect(source).not.toContain("text-amber-600")
    expect(source).not.toContain("bg-emerald-500")
    expect(source).not.toContain("bg-amber-500")
  })
})
