import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const componentSource = readFileSync(path.resolve(process.cwd(), "components/overview/agent-location-map.tsx"), "utf8")
const dataSource = readFileSync(path.resolve(process.cwd(), "components/overview/agent-location-map-data.ts"), "utf8")
const connectionsSource = readFileSync(path.resolve(process.cwd(), "components/overview/agent-location-map-connections.ts"), "utf8")
const worldMapSource = readFileSync(path.resolve(process.cwd(), "components/overview/world-map.tsx"), "utf8")
const layoutSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-section-layouts.tsx"), "utf8")

describe("agent-location-map contract", () => {
  it("maps the complete backend projection and keeps production coordinate fixtures out", () => {
    expect(dataSource).toContain("AgentLocationMapAgent")
    expect(dataSource).toContain("isValidAgentLocationCoordinate")
    expect(dataSource).toContain("getAgentStatusDistributionStatus")
    expect(dataSource).toContain("getAgentStatusDistributionTone")
    expect(dataSource).toContain("agent.location.latitude")
    expect(dataSource).toContain("agent.location.sourceObservedIp")
    expect(dataSource).not.toContain("MOCK_AGENT_LOCATION_BY_ID")
    expect(dataSource).not.toContain("MOCK_SERVER_LOCATION")
    expect(componentSource).not.toContain("useAgents")
    expect(componentSource).not.toContain("pageSize")
  })

  it("renders one bounded interactive geography surface for all map layers", () => {
    expect(worldMapSource).toContain('import DottedMap from "dotted-map"')
    expect(worldMapSource).toContain('from "react-simple-maps"')
    expect(worldMapSource).toContain('from "world-atlas/countries-110m.json"')
    expect(worldMapSource).toContain("WORLD_MAP_REGION")
    expect(worldMapSource).toContain("createDottedMapPath")
    expect(worldMapSource).toContain("ComposableMap")
    expect(worldMapSource).toContain("ZoomableGroup")
    expect(worldMapSource).toContain("translateExtent")
    expect(worldMapSource).toContain("WORLD_MAP_MAX_ZOOM")
    expect(worldMapSource).toContain("geoEquirectangular")
    expect(worldMapSource).toContain("Geographies")
    expect(worldMapSource).toContain("Geography")
    expect(worldMapSource).toContain("ANTARCTICA_NAMES")
    expect(worldMapSource).toContain("data-world-map-country")
    expect(worldMapSource).toContain("Marker")
    expect(worldMapSource).toContain("useMemo")
    expect(worldMapSource).toContain("TooltipProvider")
    expect(worldMapSource).toContain("data-world-map-marker")
    expect(worldMapSource).toContain("WORLD_MAP_MARKER_HIT_RADIUS")
    expect(worldMapSource).toContain('pointerEvents="all"')
    expect(worldMapSource).toContain("motion.circle")
    expect(worldMapSource).toContain('marker.locationState === "current" && !prefersReducedMotion')
    expect(worldMapSource).toContain("WORLD_MAP_BEACON_COUNT = 2")
    expect(worldMapSource).toContain("WORLD_MAP_BEACON_DURATION_SECONDS")
    expect(worldMapSource).toContain("repeat: Infinity")
    expect(worldMapSource).toContain('kind?: "agent" | "server"')
    expect(worldMapSource).toContain('locationState?: "current" | "expired"')
    expect(worldMapSource).toContain("data-world-map-location-state")
    expect(worldMapSource).toContain('strokeDasharray="1.2 1.2"')
    expect(worldMapSource).toContain("createBoundedConnectionPath")
    expect(worldMapSource).toContain("WORLD_MAP_CONNECTION_INSET")
    expect(worldMapSource).toContain("const WORLD_MAP_INITIAL_ZOOM = 1.05")
    expect(worldMapSource).toContain("<animateMotion")
    expect(worldMapSource).toContain('calcMode="paced"')
    expect(worldMapSource).toContain('repeatCount="indefinite"')
    expect(worldMapSource).toContain('rotate="auto"')
    expect(worldMapSource).toContain("WORLD_MAP_ACTIVE_DISPATCH_HALF_LENGTH")
    expect(worldMapSource).toContain("{prefersReducedMotion ? null : (")
    expect(worldMapSource).not.toContain("strokeDashoffset")
    expect(worldMapSource).not.toContain("getPointAtLength")
    expect(worldMapSource).not.toContain("crossesDateLineToTheRight")
    expect(worldMapSource).not.toContain("createConnectionPaths")
    expect(worldMapSource).not.toContain("dangerouslySetInnerHTML")
  })

  it("keeps the operational panel states explicit", () => {
    expect(componentSource).toContain("useAgentClusterSummary")
    expect(componentSource).toContain("useAgentLocationMap")
    expect(componentSource).toContain("summary.isInitialError")
    expect(componentSource).toContain("summary.isRefetchStale")
    expect(componentSource).toContain("locationMap.isInitialError")
    expect(componentSource).toContain("locationMap.isRefetchStale")
    expect(componentSource).toContain("AgentLocationMapUnavailable")
    expect(componentSource).toContain("AppErrorState")
    expect(componentSource).toContain("buildMapConnections")
    expect(connectionsSource).toContain("serverLocation")
    expect(connectionsSource).toContain('filter((node) => node.status !== "offline")')
    expect(connectionsSource).not.toContain(".slice(")
    expect(componentSource).not.toContain("MAP_CONNECTION_LIMIT")
    expect(connectionsSource).toContain("curveDirection")
    expect(connectionsSource).toContain("hasTaskLoadData")
    expect(componentSource).not.toContain("buildAgentExecutionCapacity")
    expect(componentSource).toContain('t("executionCapacity")')
    expect(componentSource).toContain("summary.data.executionCapacity.availableSlots")
    expect(componentSource).toContain("summary.data.locationCoverage.positionedCount")
    expect(componentSource).toContain('t("inference")')
    expect(componentSource).not.toContain("expiredAgentCount")
    expect(componentSource).not.toContain('t("connectionNotice")')
    expect(componentSource).not.toContain('t("serverUnknown")')
    expect(componentSource).not.toContain("accuracyRadiusKm")
    expect(componentSource).not.toContain('title={t("title")}')
    expect(componentSource).not.toContain('href=\"/settings/agents/\"')
    expect(componentSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_HEADER_CLASS")
    expect(componentSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_BODY_CLASS")
    expect(componentSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_STATUS_LEGEND_CLASS")
    expect(componentSource).toContain("data-slot=\"agent-status-legend\"")
    expect(componentSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_SURFACE_CLASS")
    expect(layoutSource).toContain('export const OVERVIEW_AGENT_LOCATION_MAP_BODY_CLASS = "flex min-w-0 flex-col pt-3 xl:min-h-0 xl:flex-1"')
    expect(layoutSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_STATUS_LEGEND_CLASS")
    expect(layoutSource).toContain("bottom-2 right-2")
    expect(layoutSource).not.toContain("rounded-md border border-border/70 bg-background/95 px-2 py-1 shadow-sm")
    expect(layoutSource).toContain("OVERVIEW_AGENT_LOCATION_MAP_SURFACE_CLASS")
    expect(componentSource).not.toContain("border-b border-border pb-3")
  })
})
