import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const lazySource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-lazy-sections.tsx"), "utf8")
const skeletonSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-sections-skeleton.tsx"), "utf8")
const agentLocationMapSource = readFileSync(path.resolve(process.cwd(), "components/overview/agent-location-map.tsx"), "utf8")
const actionItemsSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-action-items.tsx"), "utf8")
const riskSummarySource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-risk-summary.tsx"), "utf8")
const assetOverviewSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-asset-overview.tsx"), "utf8")
const runtimeDetailsSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-runtime-details.tsx"), "utf8")
const chartSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-area-chart.tsx"), "utf8")
const layoutSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-section-layouts.tsx"), "utf8")
const globalsSource = readFileSync(path.resolve(process.cwd(), "app/globals.css"), "utf8")

describe("overview-lazy-sections contract", () => {
  it("reveals the risk ring once as a whole without enabling pie-sector animation", () => {
    expect(riskSummarySource).toContain("overview-ring-enter")
    expect(riskSummarySource).toContain("isAnimationActive={false}")
    expect(globalsSource).toContain("@keyframes overview-risk-ring-reveal")
    expect(globalsSource).toContain("opacity: 0;")
    expect(globalsSource).toContain("animation: overview-risk-ring-reveal 420ms")
  })

  it("orders risk-led runtime, operational, then asset dashboard surfaces", () => {
    expect(lazySource).toContain("export function OverviewLazySections")
    expect(lazySource).toContain("AgentLocationMap")
    expect(lazySource).not.toContain("OverviewActionItems")
    expect(lazySource).toContain("OverviewRiskSummary")
    expect(lazySource).toContain("OverviewScanQueue")
    expect(lazySource).toContain("OverviewAssetOverview")
    expect(lazySource).toContain("OverviewRuntimeDetails")
    expect(lazySource).toContain("OverviewOperationalGrid")
    expect(lazySource).toContain("OverviewSingleSection")
    expect(lazySource).not.toContain("OverviewSystemReadiness")
    expect(lazySource.indexOf("<OverviewRuntimeDetails")).toBeLessThan(lazySource.indexOf("<OverviewOperationalGrid"))
    expect(lazySource.indexOf("leading={<OverviewRiskSummary")).toBeLessThan(lazySource.indexOf("<OverviewOperationalGrid"))
    expect(lazySource.indexOf("<OverviewOperationalGrid")).toBeLessThan(lazySource.indexOf("<OverviewAssetOverview />"))
    expect(lazySource.indexOf("<AgentLocationMap />")).toBeLessThan(lazySource.indexOf("<OverviewScanQueue />"))
    expect(lazySource).not.toContain("AgentGlobeCard")
    expect(lazySource).not.toContain("OverviewScanStatus")
    expect(lazySource).not.toContain("OverviewServerResourceUsage")
  })

  it("mounts the Agent map and scan queue as the operational panels", () => {
    expect(agentLocationMapSource).toContain('from "@/components/overview/world-map"')
    expect(agentLocationMapSource).toContain("useAgentClusterSummary")
    expect(agentLocationMapSource).toContain("useAgentLocationMap")
    expect(agentLocationMapSource).not.toContain("useAgents")
    expect(agentLocationMapSource).toContain("buildAgentLocationMapNodes")
    expect(agentLocationMapSource).toContain("WorldMap")
    expect(agentLocationMapSource).toContain("markers={markers}")
    expect(lazySource).toContain("<AgentLocationMap />")
    expect(lazySource).toContain("<OverviewScanQueue />")
  })

  it("pairs the dashboard's runtime, asset, and operational regions across loading and resolved states", () => {
    const slots = [
      "OVERVIEW_RUNTIME_REGION_LOADING_SLOT",
      "OVERVIEW_ASSET_REGION_LOADING_SLOT",
      "OVERVIEW_OPERATIONAL_REGION_LOADING_SLOT",
    ]

    for (const slot of slots) {
      expect(lazySource).toContain(slot)
      expect(skeletonSource).toContain(slot)
      expect(layoutSource).toContain(slot)
    }
  })

  it("renders the asset distribution with shared chart colors and labeled horizontal bars", () => {
    expect(assetOverviewSource).toContain('from "@/lib/chart-config"')
    expect(assetOverviewSource).toContain('const ASSET_DISTRIBUTION_BASE_COLOR = "var(--foreground)"')
    expect(assetOverviewSource).toContain("fillOpacity")
    expect(assetOverviewSource).toContain('from "recharts"')
    expect(assetOverviewSource).toContain("ChartContainer")
    expect(assetOverviewSource).toContain("BarChart")
    expect(assetOverviewSource).toContain('layout="vertical"')
    expect(assetOverviewSource).toContain("<Bar")
    expect(assetOverviewSource).toContain("<LabelList")
    expect(assetOverviewSource).toContain("displayValue")
    expect(assetOverviewSource).toContain('hideLabel nameKey="series"')
    expect(assetOverviewSource).toContain("const ASSET_DISTRIBUTION_Y_AXIS_WIDTH = 64")
    expect(assetOverviewSource).toContain('tick={{ dx: -36, textAnchor: "start" }}')
    expect(assetOverviewSource).not.toContain("strokeDasharray")
    expect(assetOverviewSource).not.toContain("overview-asset-distribution-ring")
    expect(assetOverviewSource).not.toContain("ASSET_DISTRIBUTION_NEUTRAL_TONES")
    expect(assetOverviewSource).not.toContain("conic-gradient")
  })

  it("keeps detailed runtime signals source-owned and explicit about unavailable data", () => {
    expect(runtimeDetailsSource).not.toContain("useAgents")
    expect(runtimeDetailsSource).toContain("useScanStatistics")
    expect(runtimeDetailsSource).toContain("useScans")
    expect(runtimeDetailsSource).toContain("export function OverviewScanQueue()")
    expect(runtimeDetailsSource).toContain("export function OverviewRuntimeDetails({ leading")
    expect(runtimeDetailsSource).toContain("useDatabaseHealth")
    expect(runtimeDetailsSource).toContain("useServerRuntimeMetrics")
    expect(runtimeDetailsSource).toContain("scans.isError")
    expect(runtimeDetailsSource).toContain("database.isError")
    expect(runtimeDetailsSource).toContain("resources.isError")
    expect(runtimeDetailsSource).not.toContain("useNotifications")
    expect(runtimeDetailsSource).toContain('data-runtime-card={item.key}')
    expect(runtimeDetailsSource).toContain('from "@/components/scan/scan-status-badge"')
    expect(runtimeDetailsSource).not.toContain("RUNTIME_CARD_NEUTRAL_ICON_CLASS")
    expect(runtimeDetailsSource).toContain('className="size-4 shrink-0 text-muted-foreground"')
    expect(runtimeDetailsSource).toContain('indicatorClassName="bg-muted-foreground"')
    expect(runtimeDetailsSource).toContain("ScanStatusBadge")
    expect(runtimeDetailsSource).not.toContain("getScanStatusMetricTone")
    expect(runtimeDetailsSource).not.toContain("bg-runtime-database")
    expect(runtimeDetailsSource).not.toContain("bg-info")
    expect(runtimeDetailsSource).not.toContain("bg-success")
    expect(runtimeDetailsSource).not.toContain('from "@tabler/icons-react"')
    expect(layoutSource).toContain("OVERVIEW_RUNTIME_DETAILS_GRID_CLASS")
    expect(layoutSource).toContain("xl:grid-cols-[minmax(0,1.5fr)_minmax(0,0.75fr)_minmax(0,0.75fr)]")
    expect(layoutSource).toContain("OVERVIEW_RUNTIME_SCAN_STATUS_GRID_CLASS")
  })

  it("keeps scan, database, and resource signals source-owned", () => {
    expect(runtimeDetailsSource).toContain("scans.data.running")
    expect(runtimeDetailsSource).toContain("scans.data.pending")
    expect(runtimeDetailsSource).toContain("scans.data.failed")
    expect(runtimeDetailsSource).toContain("scans.data.cancelled")
    expect(runtimeDetailsSource).toContain("scans.data.succeeded")
    expect(runtimeDetailsSource).not.toContain("scans.data.total")
    expect(runtimeDetailsSource).toContain('useScans({ page: 1, pageSize: RECENT_SCAN_PAGE_SIZE, orderBy: "createdAt desc" })')
    expect(runtimeDetailsSource).not.toContain("useRunningScans")
    expect(runtimeDetailsSource).toContain("recentScans")
    expect(runtimeDetailsSource).toContain("RecentScanDetails")
    expect(runtimeDetailsSource).toContain("recentScans.scans.map")
    expect(runtimeDetailsSource).toContain("formatScanCreatedAt")
    expect(runtimeDetailsSource).toContain('label: t("scans.recentTitle")')
    expect(runtimeDetailsSource).toContain('t("recentCreatedAt")')
    expect(runtimeDetailsSource).toContain('t("recentStatus")')
    expect(runtimeDetailsSource).toContain("<ScrollArea")
    expect(runtimeDetailsSource).toContain("OVERVIEW_RUNTIME_SCAN_RECENT_ROWS_CLASS")
    expect(runtimeDetailsSource).not.toContain("formatScanStage")
    expect(runtimeDetailsSource).not.toContain("OVERVIEW_RUNTIME_SCAN_RECENT_PROGRESS_CLASS")
    expect(runtimeDetailsSource).toContain("/scan/history/${scan.id}/overview/")
    expect(runtimeDetailsSource).toContain('t("scans.viewHistory")')
    expect(runtimeDetailsSource).toContain('href: "/scan/history/"')
    expect(runtimeDetailsSource).toContain('href: "/settings/database-health/"')
    expect(runtimeDetailsSource).toContain('t("database.viewHealth")')
    expect(runtimeDetailsSource).toContain("TooltipTrigger")
    expect(runtimeDetailsSource).toContain("TooltipContent")
    expect(runtimeDetailsSource).toContain("statuses: [")
    expect(runtimeDetailsSource).toContain("semanticIcons.metric.cpu")
    expect(runtimeDetailsSource).toContain("semanticIcons.metric.memory")
    expect(runtimeDetailsSource).toContain("semanticIcons.metric.disk")
    expect(runtimeDetailsSource).toContain("SegmentedMetricProgress")
    expect(runtimeDetailsSource).toContain("<ServerIcon")
    expect(runtimeDetailsSource).toContain('<div className={OVERVIEW_RUNTIME_RESOURCE_LIST_CLASS}>')
    expect(runtimeDetailsSource).not.toContain('cn("mt-auto", OVERVIEW_RUNTIME_RESOURCE_LIST_CLASS)')
    expect(runtimeDetailsSource).toContain('variant="runtime-card"')
    expect(runtimeDetailsSource).toContain('threshold={SERVER_RESOURCE_VISUAL_ALERT_THRESHOLD}')
    expect(runtimeDetailsSource).toContain('barTone="threshold"')
    expect(runtimeDetailsSource).toContain('valueTone="neutral"')
    expect(runtimeDetailsSource).toContain("resources.data.capacity.cpuCores")
    expect(runtimeDetailsSource).toContain("resources.data.capacity.memoryTotalGb")
    expect(runtimeDetailsSource).toContain("resources.data.capacity.diskTotalGb")
    expect(runtimeDetailsSource).toContain('t("resources.updatedAt"')
    expect(runtimeDetailsSource).toContain('t("database.connectionUsage")')
    expect(runtimeDetailsSource).toContain('t("database.connectionCount")')
    expect(runtimeDetailsSource).toContain('t("database.taskBacklog")')
    expect(runtimeDetailsSource).toContain('t("database.probeLatency")')
    expect(runtimeDetailsSource).toContain("connectionsUsed")
    expect(runtimeDetailsSource).toContain("connectionsMax")
    expect(runtimeDetailsSource).toContain("oldestPendingTaskAgeSec")
    expect(runtimeDetailsSource).toContain("probeLatencyMs")
    expect(runtimeDetailsSource).not.toContain('t("database.backlog")')
  })

  it("keeps the scan status summary neutral while reusing scan history status icons", () => {
    expect(runtimeDetailsSource).not.toContain('key: "agents"')
    expect(runtimeDetailsSource).toContain("OVERVIEW_RUNTIME_SCAN_BODY_CLASS")
    expect(runtimeDetailsSource).toContain("OVERVIEW_RUNTIME_DATABASE_BODY_CLASS")
    expect(runtimeDetailsSource).toContain("ScanStatusBadge")
    expect(runtimeDetailsSource).toContain("ScanRuntimeStatusDetail")
    expect(runtimeDetailsSource).toContain('<dd className={textRole.metricValueDisplay}>{detail.value}</dd>')
    expect(runtimeDetailsSource).toContain('className={cn("min-w-0 truncate", textRole.caption)}')
    expect(runtimeDetailsSource).not.toContain("getScanStatusTextClass(detail.status)")
    expect(runtimeDetailsSource).not.toContain("getScanStatusTextClass(scan.status)")
    expect(layoutSource).not.toContain("OVERVIEW_RUNTIME_SCAN_TOTAL_CLASS")
    expect(layoutSource).toContain("OVERVIEW_RUNTIME_SCAN_RECENT_CLASS")
    expect(layoutSource).toContain("OVERVIEW_RUNTIME_SCAN_RECENT_META_CLASS")
    expect(layoutSource).toContain("grid-cols-[minmax(0,1fr)_minmax(72px,0.65fr)_minmax(0,0.85fr)]")
    expect(layoutSource).not.toContain("border-t border-border pt-3")
    expect(layoutSource).toContain("flex h-full min-h-0 min-w-0 flex-col gap-1")
    expect(layoutSource).toContain("border-b border-border pb-1")
    expect(runtimeDetailsSource).toContain('variant="ghost"')
    expect(runtimeDetailsSource).toContain('<ScanStatusBadge status={scan.status} variant="icon-only" label={statusLabel} />')
    expect(runtimeDetailsSource).not.toContain("runtime-card-prototype")
    expect(runtimeDetailsSource).not.toContain("OverviewRuntimeCardPrototypeSwitcher")
    expect(runtimeDetailsSource).not.toContain("useSearchParams")
  })

  it("keeps action items bounded and independent from notification read state", () => {
    expect(actionItemsSource).toContain("buildPendingItems")
    expect(actionItemsSource).toContain("return items.slice(0, 3)")
    expect(actionItemsSource).toContain('href: "/vulnerabilities/"')
    expect(actionItemsSource).toContain('href: "/scan/history/"')
    expect(actionItemsSource).toContain('href: "/settings/agents/"')
    expect(actionItemsSource).toContain("sourceUpdatedAt")
    expect(actionItemsSource).toContain("dataUpdatedAt")
    expect(actionItemsSource).toContain("<time")
    expect(actionItemsSource).not.toContain("textRole.metricValueDisplay")
    expect(actionItemsSource).not.toContain('action={<span className={textRole.caption}')
    expect(actionItemsSource).not.toContain("useNotifications")
    expect(actionItemsSource).not.toContain("markAllAsRead")
    expect(actionItemsSource).not.toContain("acknowledge")
    expect(actionItemsSource).not.toContain("snooze")
    expect(actionItemsSource).toContain("AppErrorState")
    expect(actionItemsSource).toContain("sourceError")
    expect(actionItemsSource).toContain("assets.refetch()")
    expect(actionItemsSource).toContain('t("emptyDescription")')
  })

  it("keeps review counts visible without an out-of-sync status message", () => {
    expect(riskSummarySource).toContain("useVulnerabilityStats")
    expect(riskSummarySource).toContain("ChartContainer")
    expect(riskSummarySource).toContain("activeShape={renderActiveRiskSector}")
    expect(riskSummarySource).toContain('item.severity === "critical" || item.severity === "high"')
    expect(riskSummarySource).toContain("activeIndex={activeIndices}")
    expect(riskSummarySource).toContain("onMouseEnter")
    expect(riskSummarySource).toContain("ChartTooltipContent")
    expect(riskSummarySource).toContain("OVERVIEW_RISK_RING_LEGEND_CLASS")
    expect(riskSummarySource).toContain('t("severityDistribution")')
    expect(riskSummarySource).toContain('useStatisticsHistory(7)')
    expect(riskSummarySource).toContain("riskTrendData")
    expect(riskSummarySource).toContain("OverviewAreaChart")
    expect(riskSummarySource).toContain('t("trendTitle")')
    expect(riskSummarySource).toContain('t("newToday")')
    expect(riskSummarySource).toContain('t("viewRiskDetails")')
    expect(riskSummarySource).toContain("action={(")
    expect(riskSummarySource).toContain('variant="link"')
    expect(riskSummarySource).toContain("IconChevronRight")
    expect(riskSummarySource.indexOf("action={(")).toBeLessThan(riskSummarySource.indexOf("<div className={OVERVIEW_RISK_SUMMARY_GRID_CLASS}"))
    expect(riskSummarySource).toContain('t("trendUnavailable")')
    expect(riskSummarySource).toContain('showXAxis={false}')
    expect(riskSummarySource).toContain('showYAxis={false}')
    expect(riskSummarySource).toContain("reviewedCount")
    expect(riskSummarySource).toContain("pendingCount")
    expect(riskSummarySource).toContain("Math.max(data?.changeVulns ?? 0, 0)")
    expect(riskSummarySource).toContain("const auditStats = vulnerabilityStats.data")
    expect(riskSummarySource).toContain("{auditStats ? (")
    expect(riskSummarySource).not.toContain("auditStatsAreAligned")
    expect(riskSummarySource).not.toContain('t("auditOutOfSync")')
    expect(riskSummarySource).not.toContain('t("fixed")')
    expect(riskSummarySource).not.toContain("grid grid-cols-2 gap-3 border-t pt-4")
    expect(riskSummarySource).toContain("AppErrorState")
    expect(riskSummarySource).toContain("assets.error")
    expect(riskSummarySource).toContain("onRetry={assets.refetch}")
  })

  it("keeps chart rendering in the shared chart component and sources a seven-day asset trend", () => {
    expect(assetOverviewSource).toContain("useStatisticsHistory(7)")
    expect(assetOverviewSource).toContain("OverviewAreaChart")
    expect(assetOverviewSource).toContain("historyData")
    expect(assetOverviewSource).toContain("formatOverviewDateTick")
    expect(assetOverviewSource).toContain("ASSET_CHART_X_AXIS_PADDING")
    expect(assetOverviewSource).toContain("xAxisTickFormatter")
    expect(assetOverviewSource).toContain("ASSET_CHART_DOT")
    expect(assetOverviewSource).toContain("dot={ASSET_CHART_DOT}")
    expect(assetOverviewSource).toContain("useReducedMotion")
    expect(assetOverviewSource).toContain('"overview-chart-draw"')
    expect(assetOverviewSource).toContain('"overview-chart-path-reveal"')
    expect(assetOverviewSource).toContain("isAnimationActive={false}")
    expect(globalsSource).toContain("@keyframes overview-chart-path-reveal")
    expect(globalsSource).toContain(".overview-chart-draw .recharts-area")
    expect(globalsSource).toContain("clip-path: inset(0 100% 0 0)")
    expect(assetOverviewSource).toContain("AppErrorState")
    expect(assetOverviewSource).toContain("assets.error")
    expect(assetOverviewSource).toContain("onRetry={assets.refetch}")
    expect(assetOverviewSource).not.toContain('render={<Link href="/targets/" />}')
    expect(assetOverviewSource).toContain('from "recharts"')
    expect(chartSource).toContain('from "recharts"')
    expect(chartSource).toContain("ResponsiveContainer")
    expect(chartSource).toContain("AreaChart")
    expect(chartSource).toContain("xAxisTickFormatter")
    expect(chartSource).toContain("showGrid")
    expect(chartSource).toContain("showXAxis")
    expect(chartSource).toContain("showYAxis")
    expect(chartSource).toContain("color = \"var(--primary)\"")
    expect(chartSource).not.toContain("animationDuration")
  })
})
