import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/overview/overview-section-layouts.tsx"), "utf8")

describe("overview-section-layouts contract", () => {
  it("owns the overview row geometry in one shared place", () => {
    expect(source).toContain("export const OVERVIEW_SECTIONS_SHELL_CLASS")
    expect(source).toContain('export const OVERVIEW_SECTIONS_SHELL_CLASS = "divide-y divide-border border-y border-border"')
    expect(source).toContain("export const OVERVIEW_TOP_GRID_CLASS")
    expect(source).toContain("export const OVERVIEW_MIDDLE_GRID_CLASS")
    expect(source).toContain("export const OVERVIEW_SINGLE_SECTION_CLASS")
    expect(source).toContain("export const OVERVIEW_RUNTIME_REGION_LOADING_SLOT")
    expect(source).toContain("export const OVERVIEW_ASSET_REGION_LOADING_SLOT")
    expect(source).toContain("export const OVERVIEW_OPERATIONAL_REGION_LOADING_SLOT")
    expect(source).toContain('export const OVERVIEW_OPERATIONAL_GRID_CLASS = "grid grid-cols-1 items-stretch gap-0 px-4 py-6 lg:px-6 xl:grid-cols-2')
    expect(source).toContain('export const OVERVIEW_LATEST_CRITICAL_TABLE_CLASS = "min-w-[520px]"')
    expect(source).toContain('export const OVERVIEW_CURRENT_TASKS_TABLE_CLASS = "min-w-[620px]"')
    expect(source).toContain("grid grid-cols-1 items-stretch gap-4 px-4 lg:px-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,0.65fr)]")
    expect(source).toContain("grid grid-cols-1 items-stretch gap-4 px-4 lg:px-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(340px,0.65fr)]")
    expect(source).toContain('export function OverviewTopSectionGrid({ children }: { children: ReactNode })')
    expect(source).toContain('export function OverviewMiddleSectionGrid({ children }: { children: ReactNode })')
    expect(source).toContain('export function OverviewSingleSection({ children, className, ...props }: ComponentProps<"div">)')
    expect(source).toContain('export function OverviewOperationalGrid({ children, className, ...props }: ComponentProps<"div">)')
  })

  it("owns the shared section panel shell and per-section split geometry", () => {
    expect(source).toContain("export function OverviewSectionPanel")
    expect(source).not.toContain("from \"@/components/ui/card\"")
    expect(source).not.toContain("CardContent")
    expect(source).not.toContain("bg-card")
    expect(source).toContain('data-slot="overview-section-panel"')
    expect(source).toContain('data-slot="overview-section-header"')
    expect(source).toContain("flex min-w-0 items-start justify-between gap-3")
    expect(source).toContain("@container/panel min-w-0")
    expect(source).not.toContain('CardHeader className="px-6 pb-0"')
    expect(source).toContain("export function OverviewAssetStatusLayout")
    expect(source).toContain("@2xl/panel:grid-cols-[minmax(280px,0.8fr)_minmax(420px,1.2fr)]")
    expect(source).toContain("export function OverviewRiskStatusLayout")
    expect(source).toContain("@2xl/panel:grid-cols-[minmax(220px,280px)_minmax(0,1fr)]")
    expect(source).toContain("export function OverviewServerResourceUsageLayout")
    expect(source).toContain('className="flex h-full min-h-0 flex-col gap-4"')
    expect(source).toContain('className="min-h-0 flex-1"')
    expect(source).toContain("export function OverviewScanStatusLayout")
    expect(source).toContain('className="grid min-w-0 gap-3"')
    expect(source).toContain('className="grid min-w-0 gap-3 pt-1"')
    expect(source).toContain("xl:[&>section+section]:border-l")
    expect(source).toContain("xl:[&>section+section]:pl-8")
    expect(source).toContain("xl:[&>section:first-child]:pr-8")
    expect(source).toContain("xl:[&>div:first-child]:pr-6")
    expect(source).toContain("xl:pr-8 xl:first:border-l-0")
    expect(source).toContain('export const OVERVIEW_RUNTIME_DATABASE_BODY_CLASS = "flex flex-1 flex-col justify-between gap-3"')
  })

  it("owns reusable internal section geometry shared by resolved content and skeletons", () => {
    expect(source).toContain("export const OVERVIEW_ASSET_TOP_METRICS_CLASS")
    expect(source).toContain("export const OVERVIEW_ASSET_TOP_METRIC_ITEM_CLASS")
    expect(source).toContain("export const OVERVIEW_ASSET_METRIC_LABEL_ROW_CLASS")
    expect(source).toContain("export const OVERVIEW_ASSET_DISTRIBUTION_HEADER_GRID_CLASS")
    expect(source).toContain("export const OVERVIEW_ASSET_DISTRIBUTION_ROW_CLASS")
    expect(source).toContain("export const OVERVIEW_TREND_HEADER_CLASS")
    expect(source).toContain("export const OVERVIEW_RISK_RING_LEGEND_CLASS")
    expect(source).toContain("export const OVERVIEW_RISK_LEGEND_CLASS")
    expect(source).toContain("export const OVERVIEW_RISK_LEGEND_ROW_CLASS")
    expect(source).toContain("export const OVERVIEW_RISK_TREND_CHART_CLASS")
    expect(source).toContain("export const OVERVIEW_SERVER_RESOURCE_CHART_CLASS")
    expect(source).toContain("export const OVERVIEW_SERVER_RESOURCE_METRIC_VALUE_ROW_CLASS")
    expect(source).toContain("export const OVERVIEW_SCAN_SUMMARY_GRID_CLASS")
    expect(source).toContain("export const OVERVIEW_SCAN_SUMMARY_ITEM_CLASS")
    expect(source).toContain("export const OVERVIEW_CURRENT_TASKS_HEADER_CLASS")
    expect(source).toContain("export const OVERVIEW_CURRENT_TASKS_TABLE_VIEWPORT_CLASS")
    expect(source).toContain("export const OVERVIEW_RUNTIME_SCAN_STATUS_GRID_CLASS")
    expect(source).toContain("export const OVERVIEW_RUNTIME_SCAN_STATUS_ITEM_CLASS")
    expect(source).toContain("export const OVERVIEW_RUNTIME_SCAN_RECENT_ROWS_CLASS")
    expect(source).toContain('export const OVERVIEW_RUNTIME_SCAN_RECENT_LIST_CLASS = "h-[197px] min-w-0 shrink-0"')
    expect(source).toContain('export const OVERVIEW_AGENT_LOCATION_MAP_SURFACE_CLASS = "relative h-full min-h-0 w-full @7xl/main:h-80"')
    expect(source).toContain('export const OVERVIEW_ASSET_CHART_SHELL_CLASS = "h-56 min-w-0 @7xl/main:h-80"')
    expect(source).toContain('OVERVIEW_RUNTIME_SCAN_RECENT_CLASS = "flex h-full min-h-0 min-w-0 flex-col gap-1"')
    expect(source).toContain('export const OVERVIEW_RUNTIME_SCAN_RECENT_ROWS_CLASS = "grid min-w-0 gap-0.5"')
    expect(source).toContain('OVERVIEW_RUNTIME_SCAN_RECENT_HEADER_CLASS = "flex min-w-0 items-center gap-3"')
    expect(source).toContain('OVERVIEW_RUNTIME_SCAN_RECENT_COLUMN_HEADER_CLASS = "flex min-w-0 items-center gap-3 border-b border-border pb-1"')
    expect(source).not.toContain('OVERVIEW_RUNTIME_SCAN_RECENT_CLASS = "grid min-w-0 gap-2 border-t')
  })
})
