import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/overview/overview-sections-loader.tsx"), "utf8")
const readyProbeSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-sections-ready-probe.tsx"), "utf8")
const dynamicSource = readFileSync(path.resolve(process.cwd(), "components/overview/overview-sections-dynamic.ts"), "utf8")
const overviewGuide = readFileSync(path.resolve(process.cwd(), "components/overview/README.md"), "utf8")

describe("overview-sections-loader contract", () => {
  it("loads the heavy overview sections through next/dynamic with a null dynamic fallback", () => {
    expect(source).toContain('"use client"')
    expect(source).toContain("import dynamic from \"next/dynamic\"")
    expect(dynamicSource).toContain("import(\"@/components/overview/overview-lazy-sections\")")
    expect(dynamicSource).toContain(".then((mod) => mod.OverviewLazySections)")
    expect(source).toContain("loadOverviewLazySections")
    expect(source).toContain("ssr: false")
    expect(source).toContain("loading: () => null")
  })

  it("uses ContentHandoff as the single visible loading owner", () => {
    expect(source).toContain("from \"@/components/shared/loading/content-handoff\"")
    expect(source).toContain("from \"@/components/overview/overview-sections-skeleton\"")
    expect(source).toContain("OverviewSectionsReadyProbe")
    expect(source).toContain("loadOverviewLazySections")
    expect(source).not.toContain("useAssetStatistics")
    expect(source).not.toContain("useScanStatistics")
    expect(source).not.toContain("useAgents")
    expect(readyProbeSource).toContain("useAssetStatistics")
    expect(readyProbeSource).toContain("useStatisticsHistory(7)")
    expect(readyProbeSource).toContain("useServerRuntimeMetrics")
    expect(readyProbeSource).toContain("useScanStatistics")
    expect(readyProbeSource).toContain("useAgentClusterSummary()")
    expect(readyProbeSource).toContain("useAgentLocationMap()")
    expect(readyProbeSource).not.toContain("useAgents")
    expect(readyProbeSource).toContain("useDatabaseHealth")
    expect(readyProbeSource).toContain("useVulnerabilityStats")
    expect(readyProbeSource).toContain("query.isSuccess || query.isError")
    expect(readyProbeSource).toContain("loadOverviewLazySections")
    expect(readyProbeSource).toContain("return null")
    expect(source).toContain("<ContentHandoff")
    expect(source).toContain('owner="overview-sections-loader"')
    expect(source).toContain("isLoading={!isReady}")
    expect(source).toContain("skeleton={<OverviewSectionsSkeleton />}")
    expect(source).not.toContain("mountContentWhileLoading")
    expect(source).toContain("{!isReady ? (")
    expect(source).toContain("<OverviewDynamicSections />")
    expect(source).not.toContain("onReady={() => setIsReady(true)}")
    expect(source).not.toContain("loading: () => <OverviewSectionsSkeleton />")
    expect(source).not.toContain("from \"@/components/ui/card\"")
    expect(source).not.toContain("from \"@/components/ui/skeleton\"")
    expect(source).not.toContain("animate-pulse")
  })

  it("keeps the route-facing loader lightweight", () => {
    expect(source).toContain("export function OverviewSectionsLoader")
    expect(source).toContain("React.useState(false)")
    expect(source).not.toContain("window.requestAnimationFrame")
    expect(source).not.toContain("window.cancelAnimationFrame")
    expect(readyProbeSource).toContain("window.requestAnimationFrame")
    expect(readyProbeSource).toContain("window.cancelAnimationFrame")
    expect(source).not.toContain("from \"recharts\"")
    expect(source).not.toContain("from \"cobe\"")
    expect(source).not.toContain("AgentGlobeCard")
  })

  it("documents the overview lazy-readiness handoff contract", () => {
    expect(overviewGuide).toContain("## Loader Handoff")
    expect(overviewGuide).toContain("The dynamic import fallback stays `null`")
    expect(overviewGuide).toContain("OverviewSectionsLoader` owns the first-screen readiness gate")
    expect(overviewGuide).toContain("OverviewSectionsReadyProbe` returns `null`")
    expect(overviewGuide).toContain("unmounts after readiness")
    expect(overviewGuide).toContain("The required first-screen queries are asset statistics")
    expect(overviewGuide).toContain("global vulnerability review statistics")
    expect(overviewGuide).toContain("database health, and runtime metrics")
    expect(overviewGuide).toContain("Readiness waits for every required query to settle")
    expect(overviewGuide).toContain("Do not mount the full lazy subtree hidden while loading")
    expect(overviewGuide).toContain("derive readiness from a callback that only runs after `ContentHandoff` renders its children")
  })
})
