// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_diagnostics.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineExecutionDiagnosticsService_EstablishExecutionDiagnostics_FullMethodName = "/lunafox.engine.execution.v2.EngineExecutionDiagnosticsService/EstablishExecutionDiagnostics"
	EngineExecutionDiagnosticsService_ReportTerminalDiagnostics_FullMethodName     = "/lunafox.engine.execution.v2.EngineExecutionDiagnosticsService/ReportTerminalDiagnostics"
)

// EngineExecutionDiagnosticsServiceClient is the client API for EngineExecutionDiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineExecutionDiagnosticsService is the generated Engine-to-Agent terminal
// observation side channel. Scope is recovered exclusively from the existing
// authenticated task session; requests never carry control-plane identity.
type EngineExecutionDiagnosticsServiceClient interface {
	EstablishExecutionDiagnostics(ctx context.Context, in *EstablishExecutionDiagnosticsRequest, opts ...grpc.CallOption) (*EstablishExecutionDiagnosticsResponse, error)
	ReportTerminalDiagnostics(ctx context.Context, in *ReportTerminalDiagnosticsRequest, opts ...grpc.CallOption) (*ReportTerminalDiagnosticsResponse, error)
}

type engineExecutionDiagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineExecutionDiagnosticsServiceClient(cc grpc.ClientConnInterface) EngineExecutionDiagnosticsServiceClient {
	return &engineExecutionDiagnosticsServiceClient{cc}
}

func (c *engineExecutionDiagnosticsServiceClient) EstablishExecutionDiagnostics(ctx context.Context, in *EstablishExecutionDiagnosticsRequest, opts ...grpc.CallOption) (*EstablishExecutionDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstablishExecutionDiagnosticsResponse)
	err := c.cc.Invoke(ctx, EngineExecutionDiagnosticsService_EstablishExecutionDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineExecutionDiagnosticsServiceClient) ReportTerminalDiagnostics(ctx context.Context, in *ReportTerminalDiagnosticsRequest, opts ...grpc.CallOption) (*ReportTerminalDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTerminalDiagnosticsResponse)
	err := c.cc.Invoke(ctx, EngineExecutionDiagnosticsService_ReportTerminalDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineExecutionDiagnosticsServiceServer is the server API for EngineExecutionDiagnosticsService service.
// All implementations must embed UnimplementedEngineExecutionDiagnosticsServiceServer
// for forward compatibility.
//
// EngineExecutionDiagnosticsService is the generated Engine-to-Agent terminal
// observation side channel. Scope is recovered exclusively from the existing
// authenticated task session; requests never carry control-plane identity.
type EngineExecutionDiagnosticsServiceServer interface {
	EstablishExecutionDiagnostics(context.Context, *EstablishExecutionDiagnosticsRequest) (*EstablishExecutionDiagnosticsResponse, error)
	ReportTerminalDiagnostics(context.Context, *ReportTerminalDiagnosticsRequest) (*ReportTerminalDiagnosticsResponse, error)
	mustEmbedUnimplementedEngineExecutionDiagnosticsServiceServer()
}

// UnimplementedEngineExecutionDiagnosticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineExecutionDiagnosticsServiceServer struct{}

func (UnimplementedEngineExecutionDiagnosticsServiceServer) EstablishExecutionDiagnostics(context.Context, *EstablishExecutionDiagnosticsRequest) (*EstablishExecutionDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstablishExecutionDiagnostics not implemented")
}
func (UnimplementedEngineExecutionDiagnosticsServiceServer) ReportTerminalDiagnostics(context.Context, *ReportTerminalDiagnosticsRequest) (*ReportTerminalDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTerminalDiagnostics not implemented")
}
func (UnimplementedEngineExecutionDiagnosticsServiceServer) mustEmbedUnimplementedEngineExecutionDiagnosticsServiceServer() {
}
func (UnimplementedEngineExecutionDiagnosticsServiceServer) testEmbeddedByValue() {}

// UnsafeEngineExecutionDiagnosticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineExecutionDiagnosticsServiceServer will
// result in compilation errors.
type UnsafeEngineExecutionDiagnosticsServiceServer interface {
	mustEmbedUnimplementedEngineExecutionDiagnosticsServiceServer()
}

func RegisterEngineExecutionDiagnosticsServiceServer(s grpc.ServiceRegistrar, srv EngineExecutionDiagnosticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedEngineExecutionDiagnosticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineExecutionDiagnosticsService_ServiceDesc, srv)
}

func _EngineExecutionDiagnosticsService_EstablishExecutionDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstablishExecutionDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineExecutionDiagnosticsServiceServer).EstablishExecutionDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineExecutionDiagnosticsService_EstablishExecutionDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineExecutionDiagnosticsServiceServer).EstablishExecutionDiagnostics(ctx, req.(*EstablishExecutionDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineExecutionDiagnosticsService_ReportTerminalDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTerminalDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineExecutionDiagnosticsServiceServer).ReportTerminalDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineExecutionDiagnosticsService_ReportTerminalDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineExecutionDiagnosticsServiceServer).ReportTerminalDiagnostics(ctx, req.(*ReportTerminalDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineExecutionDiagnosticsService_ServiceDesc is the grpc.ServiceDesc for EngineExecutionDiagnosticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineExecutionDiagnosticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lunafox.engine.execution.v2.EngineExecutionDiagnosticsService",
	HandlerType: (*EngineExecutionDiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstablishExecutionDiagnostics",
			Handler:    _EngineExecutionDiagnosticsService_EstablishExecutionDiagnostics_Handler,
		},
		{
			MethodName: "ReportTerminalDiagnostics",
			Handler:    _EngineExecutionDiagnosticsService_ReportTerminalDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lunafox/engine/execution/v2/engine_execution_diagnostics.proto",
}
