// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_reporting.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineExecutionReportingService_ReportProgress_FullMethodName    = "/lunafox.engine.execution.v2.EngineExecutionReportingService/ReportProgress"
	EngineExecutionReportingService_SubmitResultBatch_FullMethodName = "/lunafox.engine.execution.v2.EngineExecutionReportingService/SubmitResultBatch"
)

// EngineExecutionReportingServiceClient is the client API for EngineExecutionReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineExecutionReportingService is the Engine-to-Agent reporting-only
// surface. Scope is selected from the authenticated task session, never from
// request fields.
type EngineExecutionReportingServiceClient interface {
	ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*ReportProgressResponse, error)
	SubmitResultBatch(ctx context.Context, in *SubmitResultBatchRequest, opts ...grpc.CallOption) (*SubmitResultBatchResponse, error)
}

type engineExecutionReportingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineExecutionReportingServiceClient(cc grpc.ClientConnInterface) EngineExecutionReportingServiceClient {
	return &engineExecutionReportingServiceClient{cc}
}

func (c *engineExecutionReportingServiceClient) ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*ReportProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportProgressResponse)
	err := c.cc.Invoke(ctx, EngineExecutionReportingService_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineExecutionReportingServiceClient) SubmitResultBatch(ctx context.Context, in *SubmitResultBatchRequest, opts ...grpc.CallOption) (*SubmitResultBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResultBatchResponse)
	err := c.cc.Invoke(ctx, EngineExecutionReportingService_SubmitResultBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineExecutionReportingServiceServer is the server API for EngineExecutionReportingService service.
// All implementations must embed UnimplementedEngineExecutionReportingServiceServer
// for forward compatibility.
//
// EngineExecutionReportingService is the Engine-to-Agent reporting-only
// surface. Scope is selected from the authenticated task session, never from
// request fields.
type EngineExecutionReportingServiceServer interface {
	ReportProgress(context.Context, *ReportProgressRequest) (*ReportProgressResponse, error)
	SubmitResultBatch(context.Context, *SubmitResultBatchRequest) (*SubmitResultBatchResponse, error)
	mustEmbedUnimplementedEngineExecutionReportingServiceServer()
}

// UnimplementedEngineExecutionReportingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineExecutionReportingServiceServer struct{}

func (UnimplementedEngineExecutionReportingServiceServer) ReportProgress(context.Context, *ReportProgressRequest) (*ReportProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedEngineExecutionReportingServiceServer) SubmitResultBatch(context.Context, *SubmitResultBatchRequest) (*SubmitResultBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitResultBatch not implemented")
}
func (UnimplementedEngineExecutionReportingServiceServer) mustEmbedUnimplementedEngineExecutionReportingServiceServer() {
}
func (UnimplementedEngineExecutionReportingServiceServer) testEmbeddedByValue() {}

// UnsafeEngineExecutionReportingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineExecutionReportingServiceServer will
// result in compilation errors.
type UnsafeEngineExecutionReportingServiceServer interface {
	mustEmbedUnimplementedEngineExecutionReportingServiceServer()
}

func RegisterEngineExecutionReportingServiceServer(s grpc.ServiceRegistrar, srv EngineExecutionReportingServiceServer) {
	// If the following call pancis, it indicates UnimplementedEngineExecutionReportingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineExecutionReportingService_ServiceDesc, srv)
}

func _EngineExecutionReportingService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineExecutionReportingServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineExecutionReportingService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineExecutionReportingServiceServer).ReportProgress(ctx, req.(*ReportProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineExecutionReportingService_SubmitResultBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineExecutionReportingServiceServer).SubmitResultBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineExecutionReportingService_SubmitResultBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineExecutionReportingServiceServer).SubmitResultBatch(ctx, req.(*SubmitResultBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineExecutionReportingService_ServiceDesc is the grpc.ServiceDesc for EngineExecutionReportingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineExecutionReportingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lunafox.engine.execution.v2.EngineExecutionReportingService",
	HandlerType: (*EngineExecutionReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportProgress",
			Handler:    _EngineExecutionReportingService_ReportProgress_Handler,
		},
		{
			MethodName: "SubmitResultBatch",
			Handler:    _EngineExecutionReportingService_SubmitResultBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lunafox/engine/execution/v2/engine_execution_reporting.proto",
}
