// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_input.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope is selected from the authenticated task session. The generated adapter
// fixes role from the closed Registry; hand-written Engine code never sees this
// wire message or role string.
type MaterializeExecutionInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeExecutionInputRequest) Reset() {
	*x = MaterializeExecutionInputRequest{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeExecutionInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeExecutionInputRequest) ProtoMessage() {}

func (x *MaterializeExecutionInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeExecutionInputRequest.ProtoReflect.Descriptor instead.
func (*MaterializeExecutionInputRequest) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescGZIP(), []int{0}
}

func (x *MaterializeExecutionInputRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// path is returned only inside the private SDK/generated-adapter transport
// bridge after Agent publication. Typed Engine handles expose Path(ctx), not a
// readable path field.
type MaterializeExecutionInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeExecutionInputResponse) Reset() {
	*x = MaterializeExecutionInputResponse{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeExecutionInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeExecutionInputResponse) ProtoMessage() {}

func (x *MaterializeExecutionInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeExecutionInputResponse.ProtoReflect.Descriptor instead.
func (*MaterializeExecutionInputResponse) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescGZIP(), []int{1}
}

func (x *MaterializeExecutionInputResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_lunafox_engine_execution_v2_engine_execution_input_proto protoreflect.FileDescriptor

const file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDesc = "" +
	"\n" +
	"8lunafox/engine/execution/v2/engine_execution_input.proto\x12\x1blunafox.engine.execution.v2\"\xc9\x01\n" +
	" MaterializeExecutionInputRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04roleJ\b\b\x02\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x06targetR\apackageR\x05imageR\n" +
	"credentialR\x06secretR\asessionR\x05leaseR\x04pathR\fcontent_typeR\x06digestR\frecord_countR\n" +
	"request_id\"\x82\x01\n" +
	"!MaterializeExecutionInputResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04pathJ\b\b\x02\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x04roleR\fcontent_typeR\x06digestR\frecord_count2\xba\x01\n" +
	"\x1bEngineExecutionInputService\x12\x9a\x01\n" +
	"\x19MaterializeExecutionInput\x12=.lunafox.engine.execution.v2.MaterializeExecutionInputRequest\x1a>.lunafox.engine.execution.v2.MaterializeExecutionInputResponseB7Z5github.com/yyhuni/lunafox/engine-go/protocol;protocolb\x06proto3"

var (
	file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescOnce sync.Once
	file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescData []byte
)

func file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescGZIP() []byte {
	file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescOnce.Do(func() {
		file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDesc)))
	})
	return file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDescData
}

var file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lunafox_engine_execution_v2_engine_execution_input_proto_goTypes = []any{
	(*MaterializeExecutionInputRequest)(nil),  // 0: lunafox.engine.execution.v2.MaterializeExecutionInputRequest
	(*MaterializeExecutionInputResponse)(nil), // 1: lunafox.engine.execution.v2.MaterializeExecutionInputResponse
}
var file_lunafox_engine_execution_v2_engine_execution_input_proto_depIdxs = []int32{
	0, // 0: lunafox.engine.execution.v2.EngineExecutionInputService.MaterializeExecutionInput:input_type -> lunafox.engine.execution.v2.MaterializeExecutionInputRequest
	1, // 1: lunafox.engine.execution.v2.EngineExecutionInputService.MaterializeExecutionInput:output_type -> lunafox.engine.execution.v2.MaterializeExecutionInputResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lunafox_engine_execution_v2_engine_execution_input_proto_init() }
func file_lunafox_engine_execution_v2_engine_execution_input_proto_init() {
	if File_lunafox_engine_execution_v2_engine_execution_input_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lunafox_engine_execution_v2_engine_execution_input_proto_goTypes,
		DependencyIndexes: file_lunafox_engine_execution_v2_engine_execution_input_proto_depIdxs,
		MessageInfos:      file_lunafox_engine_execution_v2_engine_execution_input_proto_msgTypes,
	}.Build()
	File_lunafox_engine_execution_v2_engine_execution_input_proto = out.File
	file_lunafox_engine_execution_v2_engine_execution_input_proto_goTypes = nil
	file_lunafox_engine_execution_v2_engine_execution_input_proto_depIdxs = nil
}
