// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_input.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineExecutionInputService_MaterializeExecutionInput_FullMethodName = "/lunafox.engine.execution.v2.EngineExecutionInputService/MaterializeExecutionInput"
)

// EngineExecutionInputServiceClient is the client API for EngineExecutionInputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineExecutionInputService is the Engine-to-Agent lazy execution-input
// surface. It shares the task-private UDS listener and authenticated session
// with reporting, but has independent RPC and error semantics.
type EngineExecutionInputServiceClient interface {
	MaterializeExecutionInput(ctx context.Context, in *MaterializeExecutionInputRequest, opts ...grpc.CallOption) (*MaterializeExecutionInputResponse, error)
}

type engineExecutionInputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineExecutionInputServiceClient(cc grpc.ClientConnInterface) EngineExecutionInputServiceClient {
	return &engineExecutionInputServiceClient{cc}
}

func (c *engineExecutionInputServiceClient) MaterializeExecutionInput(ctx context.Context, in *MaterializeExecutionInputRequest, opts ...grpc.CallOption) (*MaterializeExecutionInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterializeExecutionInputResponse)
	err := c.cc.Invoke(ctx, EngineExecutionInputService_MaterializeExecutionInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineExecutionInputServiceServer is the server API for EngineExecutionInputService service.
// All implementations must embed UnimplementedEngineExecutionInputServiceServer
// for forward compatibility.
//
// EngineExecutionInputService is the Engine-to-Agent lazy execution-input
// surface. It shares the task-private UDS listener and authenticated session
// with reporting, but has independent RPC and error semantics.
type EngineExecutionInputServiceServer interface {
	MaterializeExecutionInput(context.Context, *MaterializeExecutionInputRequest) (*MaterializeExecutionInputResponse, error)
	mustEmbedUnimplementedEngineExecutionInputServiceServer()
}

// UnimplementedEngineExecutionInputServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineExecutionInputServiceServer struct{}

func (UnimplementedEngineExecutionInputServiceServer) MaterializeExecutionInput(context.Context, *MaterializeExecutionInputRequest) (*MaterializeExecutionInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaterializeExecutionInput not implemented")
}
func (UnimplementedEngineExecutionInputServiceServer) mustEmbedUnimplementedEngineExecutionInputServiceServer() {
}
func (UnimplementedEngineExecutionInputServiceServer) testEmbeddedByValue() {}

// UnsafeEngineExecutionInputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineExecutionInputServiceServer will
// result in compilation errors.
type UnsafeEngineExecutionInputServiceServer interface {
	mustEmbedUnimplementedEngineExecutionInputServiceServer()
}

func RegisterEngineExecutionInputServiceServer(s grpc.ServiceRegistrar, srv EngineExecutionInputServiceServer) {
	// If the following call pancis, it indicates UnimplementedEngineExecutionInputServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineExecutionInputService_ServiceDesc, srv)
}

func _EngineExecutionInputService_MaterializeExecutionInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterializeExecutionInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineExecutionInputServiceServer).MaterializeExecutionInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineExecutionInputService_MaterializeExecutionInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineExecutionInputServiceServer).MaterializeExecutionInput(ctx, req.(*MaterializeExecutionInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineExecutionInputService_ServiceDesc is the grpc.ServiceDesc for EngineExecutionInputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineExecutionInputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lunafox.engine.execution.v2.EngineExecutionInputService",
	HandlerType: (*EngineExecutionInputServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MaterializeExecutionInput",
			Handler:    _EngineExecutionInputService_MaterializeExecutionInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lunafox/engine/execution/v2/engine_execution_input.proto",
}
