// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_diagnostics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EngineExecutionFailedStage is the closed execution-boundary vocabulary. It
// never represents cancellation, timeout, OOM, or a concrete error cause.
type EngineExecutionFailedStage int32

const (
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN                  EngineExecutionFailedStage = 0
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_PLAN_VALIDATION          EngineExecutionFailedStage = 1
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_INPUT_MATERIALIZATION    EngineExecutionFailedStage = 2
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_RESOURCE_MATERIALIZATION EngineExecutionFailedStage = 3
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_CONTEXT_BUILD            EngineExecutionFailedStage = 4
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_IMAGE_PREPARE            EngineExecutionFailedStage = 5
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CREATE         EngineExecutionFailedStage = 6
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_START          EngineExecutionFailedStage = 7
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_WAIT           EngineExecutionFailedStage = 8
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CLEANUP        EngineExecutionFailedStage = 9
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_PROTOCOL_BOOTSTRAP       EngineExecutionFailedStage = 10
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_EXECUTION_PROJECTION     EngineExecutionFailedStage = 11
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_HANDLER                  EngineExecutionFailedStage = 12
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_PROGRESS_REPORT          EngineExecutionFailedStage = 13
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_RESULT_ENCODE            EngineExecutionFailedStage = 14
	EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_RESULT_SUBMIT            EngineExecutionFailedStage = 15
)

// Enum value maps for EngineExecutionFailedStage.
var (
	EngineExecutionFailedStage_name = map[int32]string{
		0:  "ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN",
		1:  "ENGINE_EXECUTION_FAILED_STAGE_PLAN_VALIDATION",
		2:  "ENGINE_EXECUTION_FAILED_STAGE_INPUT_MATERIALIZATION",
		3:  "ENGINE_EXECUTION_FAILED_STAGE_RESOURCE_MATERIALIZATION",
		4:  "ENGINE_EXECUTION_FAILED_STAGE_CONTEXT_BUILD",
		5:  "ENGINE_EXECUTION_FAILED_STAGE_IMAGE_PREPARE",
		6:  "ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CREATE",
		7:  "ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_START",
		8:  "ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_WAIT",
		9:  "ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CLEANUP",
		10: "ENGINE_EXECUTION_FAILED_STAGE_PROTOCOL_BOOTSTRAP",
		11: "ENGINE_EXECUTION_FAILED_STAGE_EXECUTION_PROJECTION",
		12: "ENGINE_EXECUTION_FAILED_STAGE_HANDLER",
		13: "ENGINE_EXECUTION_FAILED_STAGE_PROGRESS_REPORT",
		14: "ENGINE_EXECUTION_FAILED_STAGE_RESULT_ENCODE",
		15: "ENGINE_EXECUTION_FAILED_STAGE_RESULT_SUBMIT",
	}
	EngineExecutionFailedStage_value = map[string]int32{
		"ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN":                  0,
		"ENGINE_EXECUTION_FAILED_STAGE_PLAN_VALIDATION":          1,
		"ENGINE_EXECUTION_FAILED_STAGE_INPUT_MATERIALIZATION":    2,
		"ENGINE_EXECUTION_FAILED_STAGE_RESOURCE_MATERIALIZATION": 3,
		"ENGINE_EXECUTION_FAILED_STAGE_CONTEXT_BUILD":            4,
		"ENGINE_EXECUTION_FAILED_STAGE_IMAGE_PREPARE":            5,
		"ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CREATE":         6,
		"ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_START":          7,
		"ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_WAIT":           8,
		"ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CLEANUP":        9,
		"ENGINE_EXECUTION_FAILED_STAGE_PROTOCOL_BOOTSTRAP":       10,
		"ENGINE_EXECUTION_FAILED_STAGE_EXECUTION_PROJECTION":     11,
		"ENGINE_EXECUTION_FAILED_STAGE_HANDLER":                  12,
		"ENGINE_EXECUTION_FAILED_STAGE_PROGRESS_REPORT":          13,
		"ENGINE_EXECUTION_FAILED_STAGE_RESULT_ENCODE":            14,
		"ENGINE_EXECUTION_FAILED_STAGE_RESULT_SUBMIT":            15,
	}
)

func (x EngineExecutionFailedStage) Enum() *EngineExecutionFailedStage {
	p := new(EngineExecutionFailedStage)
	*p = x
	return p
}

func (x EngineExecutionFailedStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineExecutionFailedStage) Descriptor() protoreflect.EnumDescriptor {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[0].Descriptor()
}

func (EngineExecutionFailedStage) Type() protoreflect.EnumType {
	return &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[0]
}

func (x EngineExecutionFailedStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineExecutionFailedStage.Descriptor instead.
func (EngineExecutionFailedStage) EnumDescriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{0}
}

// EngineExecutionErrorType is the closed, low-cardinality reason catalog. It
// carries no raw error, path, credential, or tool output.
type EngineExecutionErrorType int32

const (
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED                     EngineExecutionErrorType = 0
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_EXECUTION_FAILED                EngineExecutionErrorType = 1
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_PLAN_VALIDATION_FAILED          EngineExecutionErrorType = 2
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_INPUT_MATERIALIZATION_FAILED    EngineExecutionErrorType = 3
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_RESOURCE_MATERIALIZATION_FAILED EngineExecutionErrorType = 4
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CONTEXT_BUILD_FAILED            EngineExecutionErrorType = 5
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_IMAGE_PREPARE_FAILED            EngineExecutionErrorType = 6
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CREATE_FAILED         EngineExecutionErrorType = 7
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_START_FAILED          EngineExecutionErrorType = 8
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_WAIT_FAILED           EngineExecutionErrorType = 9
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CLEANUP_FAILED        EngineExecutionErrorType = 10
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_PROTOCOL_BOOTSTRAP_FAILED       EngineExecutionErrorType = 11
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_HANDLER_FAILED                  EngineExecutionErrorType = 12
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_PROGRESS_REPORT_FAILED          EngineExecutionErrorType = 13
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_RESULT_ENCODE_FAILED            EngineExecutionErrorType = 14
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_RESULT_SUBMIT_FAILED            EngineExecutionErrorType = 15
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_TIMEOUT                         EngineExecutionErrorType = 16
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_CANCELLED                       EngineExecutionErrorType = 17
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_OOM_KILLED                      EngineExecutionErrorType = 18
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_AGENT_SESSION_FAILED            EngineExecutionErrorType = 19
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_INVALID_OUTCOME                 EngineExecutionErrorType = 20
	EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_RESULT_PROTOCOL_FAILED          EngineExecutionErrorType = 21
)

// Enum value maps for EngineExecutionErrorType.
var (
	EngineExecutionErrorType_name = map[int32]string{
		0:  "ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED",
		1:  "ENGINE_EXECUTION_ERROR_TYPE_EXECUTION_FAILED",
		2:  "ENGINE_EXECUTION_ERROR_TYPE_PLAN_VALIDATION_FAILED",
		3:  "ENGINE_EXECUTION_ERROR_TYPE_INPUT_MATERIALIZATION_FAILED",
		4:  "ENGINE_EXECUTION_ERROR_TYPE_RESOURCE_MATERIALIZATION_FAILED",
		5:  "ENGINE_EXECUTION_ERROR_TYPE_CONTEXT_BUILD_FAILED",
		6:  "ENGINE_EXECUTION_ERROR_TYPE_IMAGE_PREPARE_FAILED",
		7:  "ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CREATE_FAILED",
		8:  "ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_START_FAILED",
		9:  "ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_WAIT_FAILED",
		10: "ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CLEANUP_FAILED",
		11: "ENGINE_EXECUTION_ERROR_TYPE_PROTOCOL_BOOTSTRAP_FAILED",
		12: "ENGINE_EXECUTION_ERROR_TYPE_HANDLER_FAILED",
		13: "ENGINE_EXECUTION_ERROR_TYPE_PROGRESS_REPORT_FAILED",
		14: "ENGINE_EXECUTION_ERROR_TYPE_RESULT_ENCODE_FAILED",
		15: "ENGINE_EXECUTION_ERROR_TYPE_RESULT_SUBMIT_FAILED",
		16: "ENGINE_EXECUTION_ERROR_TYPE_TIMEOUT",
		17: "ENGINE_EXECUTION_ERROR_TYPE_CANCELLED",
		18: "ENGINE_EXECUTION_ERROR_TYPE_OOM_KILLED",
		19: "ENGINE_EXECUTION_ERROR_TYPE_AGENT_SESSION_FAILED",
		20: "ENGINE_EXECUTION_ERROR_TYPE_INVALID_OUTCOME",
		21: "ENGINE_EXECUTION_ERROR_TYPE_RESULT_PROTOCOL_FAILED",
	}
	EngineExecutionErrorType_value = map[string]int32{
		"ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED":                     0,
		"ENGINE_EXECUTION_ERROR_TYPE_EXECUTION_FAILED":                1,
		"ENGINE_EXECUTION_ERROR_TYPE_PLAN_VALIDATION_FAILED":          2,
		"ENGINE_EXECUTION_ERROR_TYPE_INPUT_MATERIALIZATION_FAILED":    3,
		"ENGINE_EXECUTION_ERROR_TYPE_RESOURCE_MATERIALIZATION_FAILED": 4,
		"ENGINE_EXECUTION_ERROR_TYPE_CONTEXT_BUILD_FAILED":            5,
		"ENGINE_EXECUTION_ERROR_TYPE_IMAGE_PREPARE_FAILED":            6,
		"ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CREATE_FAILED":         7,
		"ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_START_FAILED":          8,
		"ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_WAIT_FAILED":           9,
		"ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CLEANUP_FAILED":        10,
		"ENGINE_EXECUTION_ERROR_TYPE_PROTOCOL_BOOTSTRAP_FAILED":       11,
		"ENGINE_EXECUTION_ERROR_TYPE_HANDLER_FAILED":                  12,
		"ENGINE_EXECUTION_ERROR_TYPE_PROGRESS_REPORT_FAILED":          13,
		"ENGINE_EXECUTION_ERROR_TYPE_RESULT_ENCODE_FAILED":            14,
		"ENGINE_EXECUTION_ERROR_TYPE_RESULT_SUBMIT_FAILED":            15,
		"ENGINE_EXECUTION_ERROR_TYPE_TIMEOUT":                         16,
		"ENGINE_EXECUTION_ERROR_TYPE_CANCELLED":                       17,
		"ENGINE_EXECUTION_ERROR_TYPE_OOM_KILLED":                      18,
		"ENGINE_EXECUTION_ERROR_TYPE_AGENT_SESSION_FAILED":            19,
		"ENGINE_EXECUTION_ERROR_TYPE_INVALID_OUTCOME":                 20,
		"ENGINE_EXECUTION_ERROR_TYPE_RESULT_PROTOCOL_FAILED":          21,
	}
)

func (x EngineExecutionErrorType) Enum() *EngineExecutionErrorType {
	p := new(EngineExecutionErrorType)
	*p = x
	return p
}

func (x EngineExecutionErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineExecutionErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[1].Descriptor()
}

func (EngineExecutionErrorType) Type() protoreflect.EnumType {
	return &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[1]
}

func (x EngineExecutionErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineExecutionErrorType.Descriptor instead.
func (EngineExecutionErrorType) EnumDescriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{1}
}

// EngineExecutionDiagnosticAvailability distinguishes valid Engine evidence
// from a missing or rejected terminal diagnostic upload.
type EngineExecutionDiagnosticAvailability int32

const (
	EngineExecutionDiagnosticAvailability_ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNSPECIFIED EngineExecutionDiagnosticAvailability = 0
	EngineExecutionDiagnosticAvailability_ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_AVAILABLE   EngineExecutionDiagnosticAvailability = 1
	EngineExecutionDiagnosticAvailability_ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNAVAILABLE EngineExecutionDiagnosticAvailability = 2
)

// Enum value maps for EngineExecutionDiagnosticAvailability.
var (
	EngineExecutionDiagnosticAvailability_name = map[int32]string{
		0: "ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNSPECIFIED",
		1: "ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_AVAILABLE",
		2: "ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNAVAILABLE",
	}
	EngineExecutionDiagnosticAvailability_value = map[string]int32{
		"ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNSPECIFIED": 0,
		"ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_AVAILABLE":   1,
		"ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNAVAILABLE": 2,
	}
)

func (x EngineExecutionDiagnosticAvailability) Enum() *EngineExecutionDiagnosticAvailability {
	p := new(EngineExecutionDiagnosticAvailability)
	*p = x
	return p
}

func (x EngineExecutionDiagnosticAvailability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineExecutionDiagnosticAvailability) Descriptor() protoreflect.EnumDescriptor {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[2].Descriptor()
}

func (EngineExecutionDiagnosticAvailability) Type() protoreflect.EnumType {
	return &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[2]
}

func (x EngineExecutionDiagnosticAvailability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineExecutionDiagnosticAvailability.Descriptor instead.
func (EngineExecutionDiagnosticAvailability) EnumDescriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{2}
}

// EngineExecutionResultState describes typed result-delivery evidence only.
// It is unrelated to scan coverage or the number of assets a tool found.
type EngineExecutionResultState int32

const (
	EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_UNSPECIFIED EngineExecutionResultState = 0
	EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_COMPLETE    EngineExecutionResultState = 1
	EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_PARTIAL     EngineExecutionResultState = 2
	EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_NONE        EngineExecutionResultState = 3
	EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_UNKNOWN     EngineExecutionResultState = 4
)

// Enum value maps for EngineExecutionResultState.
var (
	EngineExecutionResultState_name = map[int32]string{
		0: "ENGINE_EXECUTION_RESULT_STATE_UNSPECIFIED",
		1: "ENGINE_EXECUTION_RESULT_STATE_COMPLETE",
		2: "ENGINE_EXECUTION_RESULT_STATE_PARTIAL",
		3: "ENGINE_EXECUTION_RESULT_STATE_NONE",
		4: "ENGINE_EXECUTION_RESULT_STATE_UNKNOWN",
	}
	EngineExecutionResultState_value = map[string]int32{
		"ENGINE_EXECUTION_RESULT_STATE_UNSPECIFIED": 0,
		"ENGINE_EXECUTION_RESULT_STATE_COMPLETE":    1,
		"ENGINE_EXECUTION_RESULT_STATE_PARTIAL":     2,
		"ENGINE_EXECUTION_RESULT_STATE_NONE":        3,
		"ENGINE_EXECUTION_RESULT_STATE_UNKNOWN":     4,
	}
)

func (x EngineExecutionResultState) Enum() *EngineExecutionResultState {
	p := new(EngineExecutionResultState)
	*p = x
	return p
}

func (x EngineExecutionResultState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineExecutionResultState) Descriptor() protoreflect.EnumDescriptor {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[3].Descriptor()
}

func (EngineExecutionResultState) Type() protoreflect.EnumType {
	return &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[3]
}

func (x EngineExecutionResultState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineExecutionResultState.Descriptor instead.
func (EngineExecutionResultState) EnumDescriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{3}
}

// EngineExecutionDiagnosticLimit keeps the fixed diagnostic cardinality in the
// wire contract so every participant enforces the same upper bound.
type EngineExecutionDiagnosticLimit int32

const (
	EngineExecutionDiagnosticLimit_ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_UNSPECIFIED       EngineExecutionDiagnosticLimit = 0
	EngineExecutionDiagnosticLimit_ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_RESULT_TYPE_COUNT EngineExecutionDiagnosticLimit = 16
)

// Enum value maps for EngineExecutionDiagnosticLimit.
var (
	EngineExecutionDiagnosticLimit_name = map[int32]string{
		0:  "ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_UNSPECIFIED",
		16: "ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_RESULT_TYPE_COUNT",
	}
	EngineExecutionDiagnosticLimit_value = map[string]int32{
		"ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_UNSPECIFIED":       0,
		"ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_RESULT_TYPE_COUNT": 16,
	}
)

func (x EngineExecutionDiagnosticLimit) Enum() *EngineExecutionDiagnosticLimit {
	p := new(EngineExecutionDiagnosticLimit)
	*p = x
	return p
}

func (x EngineExecutionDiagnosticLimit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineExecutionDiagnosticLimit) Descriptor() protoreflect.EnumDescriptor {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[4].Descriptor()
}

func (EngineExecutionDiagnosticLimit) Type() protoreflect.EnumType {
	return &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes[4]
}

func (x EngineExecutionDiagnosticLimit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineExecutionDiagnosticLimit.Descriptor instead.
func (EngineExecutionDiagnosticLimit) EnumDescriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{4}
}

// ResultTypeWatermark is the fixed per-canonical-result-type delivery state.
// Unconfirmed batches are derived as submitted_batches - acknowledged_batches;
// no individual result, payload, or failed-batch record is retained.
type ResultTypeWatermark struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResultType          string                 `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	ReceivedItems       uint64                 `protobuf:"varint,2,opt,name=received_items,json=receivedItems,proto3" json:"received_items,omitempty"`
	EncodedItems        uint64                 `protobuf:"varint,3,opt,name=encoded_items,json=encodedItems,proto3" json:"encoded_items,omitempty"`
	SubmittedItems      uint64                 `protobuf:"varint,4,opt,name=submitted_items,json=submittedItems,proto3" json:"submitted_items,omitempty"`
	AcknowledgedItems   uint64                 `protobuf:"varint,5,opt,name=acknowledged_items,json=acknowledgedItems,proto3" json:"acknowledged_items,omitempty"`
	SubmittedBatches    uint64                 `protobuf:"varint,6,opt,name=submitted_batches,json=submittedBatches,proto3" json:"submitted_batches,omitempty"`
	AcknowledgedBatches uint64                 `protobuf:"varint,7,opt,name=acknowledged_batches,json=acknowledgedBatches,proto3" json:"acknowledged_batches,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResultTypeWatermark) Reset() {
	*x = ResultTypeWatermark{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultTypeWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultTypeWatermark) ProtoMessage() {}

func (x *ResultTypeWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultTypeWatermark.ProtoReflect.Descriptor instead.
func (*ResultTypeWatermark) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{0}
}

func (x *ResultTypeWatermark) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *ResultTypeWatermark) GetReceivedItems() uint64 {
	if x != nil {
		return x.ReceivedItems
	}
	return 0
}

func (x *ResultTypeWatermark) GetEncodedItems() uint64 {
	if x != nil {
		return x.EncodedItems
	}
	return 0
}

func (x *ResultTypeWatermark) GetSubmittedItems() uint64 {
	if x != nil {
		return x.SubmittedItems
	}
	return 0
}

func (x *ResultTypeWatermark) GetAcknowledgedItems() uint64 {
	if x != nil {
		return x.AcknowledgedItems
	}
	return 0
}

func (x *ResultTypeWatermark) GetSubmittedBatches() uint64 {
	if x != nil {
		return x.SubmittedBatches
	}
	return 0
}

func (x *ResultTypeWatermark) GetAcknowledgedBatches() uint64 {
	if x != nil {
		return x.AcknowledgedBatches
	}
	return 0
}

// EngineTerminalDiagnosticSnapshot is the Engine-generated observation. A
// successful snapshot omits failed_stage and error_type; a failed snapshot
// sets both, using UNKNOWN and EXECUTION_FAILED when its boundary is unknown.
type EngineTerminalDiagnosticSnapshot struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	FailedStage           *EngineExecutionFailedStage `protobuf:"varint,1,opt,name=failed_stage,json=failedStage,proto3,enum=lunafox.engine.execution.v2.EngineExecutionFailedStage,oneof" json:"failed_stage,omitempty"`
	ErrorType             *EngineExecutionErrorType   `protobuf:"varint,2,opt,name=error_type,json=errorType,proto3,enum=lunafox.engine.execution.v2.EngineExecutionErrorType,oneof" json:"error_type,omitempty"`
	ResultTypeWatermarks  []*ResultTypeWatermark      `protobuf:"bytes,3,rep,name=result_type_watermarks,json=resultTypeWatermarks,proto3" json:"result_type_watermarks,omitempty"`
	CompatibilityRevision string                      `protobuf:"bytes,4,opt,name=compatibility_revision,json=compatibilityRevision,proto3" json:"compatibility_revision,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EngineTerminalDiagnosticSnapshot) Reset() {
	*x = EngineTerminalDiagnosticSnapshot{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineTerminalDiagnosticSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineTerminalDiagnosticSnapshot) ProtoMessage() {}

func (x *EngineTerminalDiagnosticSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineTerminalDiagnosticSnapshot.ProtoReflect.Descriptor instead.
func (*EngineTerminalDiagnosticSnapshot) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *EngineTerminalDiagnosticSnapshot) GetFailedStage() EngineExecutionFailedStage {
	if x != nil && x.FailedStage != nil {
		return *x.FailedStage
	}
	return EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN
}

func (x *EngineTerminalDiagnosticSnapshot) GetErrorType() EngineExecutionErrorType {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED
}

func (x *EngineTerminalDiagnosticSnapshot) GetResultTypeWatermarks() []*ResultTypeWatermark {
	if x != nil {
		return x.ResultTypeWatermarks
	}
	return nil
}

func (x *EngineTerminalDiagnosticSnapshot) GetCompatibilityRevision() string {
	if x != nil {
		return x.CompatibilityRevision
	}
	return ""
}

// EngineExecutionDiagnostics is the Agent-owned final terminal snapshot. It
// combines a validated Engine observation with Agent runtime facts without
// exposing raw diagnostics or making the side channel part of task success.
type EngineExecutionDiagnostics struct {
	state                 protoimpl.MessageState                `protogen:"open.v1"`
	Availability          EngineExecutionDiagnosticAvailability `protobuf:"varint,1,opt,name=availability,proto3,enum=lunafox.engine.execution.v2.EngineExecutionDiagnosticAvailability" json:"availability,omitempty"`
	ResultState           EngineExecutionResultState            `protobuf:"varint,2,opt,name=result_state,json=resultState,proto3,enum=lunafox.engine.execution.v2.EngineExecutionResultState" json:"result_state,omitempty"`
	FailedStage           *EngineExecutionFailedStage           `protobuf:"varint,3,opt,name=failed_stage,json=failedStage,proto3,enum=lunafox.engine.execution.v2.EngineExecutionFailedStage,oneof" json:"failed_stage,omitempty"`
	ErrorType             *EngineExecutionErrorType             `protobuf:"varint,4,opt,name=error_type,json=errorType,proto3,enum=lunafox.engine.execution.v2.EngineExecutionErrorType,oneof" json:"error_type,omitempty"`
	ResultTypeWatermarks  []*ResultTypeWatermark                `protobuf:"bytes,5,rep,name=result_type_watermarks,json=resultTypeWatermarks,proto3" json:"result_type_watermarks,omitempty"`
	CompatibilityRevision string                                `protobuf:"bytes,6,opt,name=compatibility_revision,json=compatibilityRevision,proto3" json:"compatibility_revision,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EngineExecutionDiagnostics) Reset() {
	*x = EngineExecutionDiagnostics{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineExecutionDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineExecutionDiagnostics) ProtoMessage() {}

func (x *EngineExecutionDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineExecutionDiagnostics.ProtoReflect.Descriptor instead.
func (*EngineExecutionDiagnostics) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{2}
}

func (x *EngineExecutionDiagnostics) GetAvailability() EngineExecutionDiagnosticAvailability {
	if x != nil {
		return x.Availability
	}
	return EngineExecutionDiagnosticAvailability_ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNSPECIFIED
}

func (x *EngineExecutionDiagnostics) GetResultState() EngineExecutionResultState {
	if x != nil {
		return x.ResultState
	}
	return EngineExecutionResultState_ENGINE_EXECUTION_RESULT_STATE_UNSPECIFIED
}

func (x *EngineExecutionDiagnostics) GetFailedStage() EngineExecutionFailedStage {
	if x != nil && x.FailedStage != nil {
		return *x.FailedStage
	}
	return EngineExecutionFailedStage_ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN
}

func (x *EngineExecutionDiagnostics) GetErrorType() EngineExecutionErrorType {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return EngineExecutionErrorType_ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED
}

func (x *EngineExecutionDiagnostics) GetResultTypeWatermarks() []*ResultTypeWatermark {
	if x != nil {
		return x.ResultTypeWatermarks
	}
	return nil
}

func (x *EngineExecutionDiagnostics) GetCompatibilityRevision() string {
	if x != nil {
		return x.CompatibilityRevision
	}
	return ""
}

// EstablishExecutionDiagnostics is the mandatory, non-negotiated hard-cut
// session confirmation. It carries only the fixed matching revision: task and
// execution scope continue to come exclusively from the authenticated UDS
// session rather than request fields.
type EstablishExecutionDiagnosticsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CompatibilityRevision string                 `protobuf:"bytes,1,opt,name=compatibility_revision,json=compatibilityRevision,proto3" json:"compatibility_revision,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EstablishExecutionDiagnosticsRequest) Reset() {
	*x = EstablishExecutionDiagnosticsRequest{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishExecutionDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishExecutionDiagnosticsRequest) ProtoMessage() {}

func (x *EstablishExecutionDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishExecutionDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*EstablishExecutionDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{3}
}

func (x *EstablishExecutionDiagnosticsRequest) GetCompatibilityRevision() string {
	if x != nil {
		return x.CompatibilityRevision
	}
	return ""
}

// An empty response confirms only that this authenticated session belongs to
// the required matching revision. It is not capability negotiation.
type EstablishExecutionDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishExecutionDiagnosticsResponse) Reset() {
	*x = EstablishExecutionDiagnosticsResponse{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishExecutionDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishExecutionDiagnosticsResponse) ProtoMessage() {}

func (x *EstablishExecutionDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishExecutionDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*EstablishExecutionDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{4}
}

// ReportTerminalDiagnosticsRequest carries only the Engine observation. Task
// and execution identity are intentionally absent and recovered from session.
type ReportTerminalDiagnosticsRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Snapshot      *EngineTerminalDiagnosticSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTerminalDiagnosticsRequest) Reset() {
	*x = ReportTerminalDiagnosticsRequest{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTerminalDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTerminalDiagnosticsRequest) ProtoMessage() {}

func (x *ReportTerminalDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTerminalDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*ReportTerminalDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{5}
}

func (x *ReportTerminalDiagnosticsRequest) GetSnapshot() *EngineTerminalDiagnosticSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// An empty response means only that the side-channel observation was accepted.
type ReportTerminalDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTerminalDiagnosticsResponse) Reset() {
	*x = ReportTerminalDiagnosticsResponse{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTerminalDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTerminalDiagnosticsResponse) ProtoMessage() {}

func (x *ReportTerminalDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTerminalDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*ReportTerminalDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP(), []int{6}
}

var File_lunafox_engine_execution_v2_engine_execution_diagnostics_proto protoreflect.FileDescriptor

const file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDesc = "" +
	"\n" +
	">lunafox/engine/execution/v2/engine_execution_diagnostics.proto\x12\x1blunafox.engine.execution.v2\"\xfb\x03\n" +
	"\x13ResultTypeWatermark\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12%\n" +
	"\x0ereceived_items\x18\x02 \x01(\x04R\rreceivedItems\x12#\n" +
	"\rencoded_items\x18\x03 \x01(\x04R\fencodedItems\x12'\n" +
	"\x0fsubmitted_items\x18\x04 \x01(\x04R\x0esubmittedItems\x12-\n" +
	"\x12acknowledged_items\x18\x05 \x01(\x04R\x11acknowledgedItems\x12+\n" +
	"\x11submitted_batches\x18\x06 \x01(\x04R\x10submittedBatches\x121\n" +
	"\x14acknowledged_batches\x18\a \x01(\x04R\x13acknowledgedBatchesJ\b\b\b\x10\x80\x80\x80\x80\x02R\x04itemR\x05itemsR\apayloadR\bpayloadsR\x06resultR\aresultsR\x0efailed_batchesR\x05errorR\amessageR\x0fdisplay_messageR\vtool_outputR\x06stdoutR\x06stderrR\x04pathR\n" +
	"credentialR\x06secretR\x04taskR\x04scanR\texecutionR\x05agent\"\xf4\x04\n" +
	" EngineTerminalDiagnosticSnapshot\x12_\n" +
	"\ffailed_stage\x18\x01 \x01(\x0e27.lunafox.engine.execution.v2.EngineExecutionFailedStageH\x00R\vfailedStage\x88\x01\x01\x12Y\n" +
	"\n" +
	"error_type\x18\x02 \x01(\x0e25.lunafox.engine.execution.v2.EngineExecutionErrorTypeH\x01R\terrorType\x88\x01\x01\x12f\n" +
	"\x16result_type_watermarks\x18\x03 \x03(\v20.lunafox.engine.execution.v2.ResultTypeWatermarkR\x14resultTypeWatermarks\x125\n" +
	"\x16compatibility_revision\x18\x04 \x01(\tR\x15compatibilityRevisionB\x0f\n" +
	"\r_failed_stageB\r\n" +
	"\v_error_typeJ\b\b\x05\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x05agentR\asessionR\n" +
	"credentialR\x06secretR\x05errorR\amessageR\x0fdisplay_messageR\vtool_outputR\x06stdoutR\x06stderrR\x04pathR\afailureR\fresult_stateR\favailabilityR\aoutcomeR\texit_codeR\n" +
	"oom_killedR\atimeout\"\xb2\x06\n" +
	"\x1aEngineExecutionDiagnostics\x12f\n" +
	"\favailability\x18\x01 \x01(\x0e2B.lunafox.engine.execution.v2.EngineExecutionDiagnosticAvailabilityR\favailability\x12Z\n" +
	"\fresult_state\x18\x02 \x01(\x0e27.lunafox.engine.execution.v2.EngineExecutionResultStateR\vresultState\x12_\n" +
	"\ffailed_stage\x18\x03 \x01(\x0e27.lunafox.engine.execution.v2.EngineExecutionFailedStageH\x00R\vfailedStage\x88\x01\x01\x12Y\n" +
	"\n" +
	"error_type\x18\x04 \x01(\x0e25.lunafox.engine.execution.v2.EngineExecutionErrorTypeH\x01R\terrorType\x88\x01\x01\x12f\n" +
	"\x16result_type_watermarks\x18\x05 \x03(\v20.lunafox.engine.execution.v2.ResultTypeWatermarkR\x14resultTypeWatermarks\x125\n" +
	"\x16compatibility_revision\x18\x06 \x01(\tR\x15compatibilityRevisionB\x0f\n" +
	"\r_failed_stageB\r\n" +
	"\v_error_typeJ\b\b\a\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x05agentR\asessionR\n" +
	"credentialR\x06secretR\x05errorR\amessageR\x0fdisplay_messageR\vtool_outputR\x06stdoutR\x06stderrR\x04pathR\afailureR\texit_codeR\n" +
	"oom_killedR\atimeoutR\x13unconfirmed_batchesR\x0efailed_batches\"\xab\x02\n" +
	"$EstablishExecutionDiagnosticsRequest\x125\n" +
	"\x16compatibility_revision\x18\x01 \x01(\tR\x15compatibilityRevisionJ\b\b\x02\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x05agentR\asessionR\n" +
	"credentialR\x06secretR\x05errorR\amessageR\x0fdisplay_messageR\vtool_outputR\x06stdoutR\x06stderrR\x04pathR\afailureR\favailabilityR\fresult_stateR\texit_codeR\n" +
	"oom_killedR\atimeout\"'\n" +
	"%EstablishExecutionDiagnosticsResponse\"\xcb\x02\n" +
	" ReportTerminalDiagnosticsRequest\x12Y\n" +
	"\bsnapshot\x18\x01 \x01(\v2=.lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshotR\bsnapshotJ\b\b\x02\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x05agentR\asessionR\n" +
	"credentialR\x06secretR\x05errorR\amessageR\x0fdisplay_messageR\vtool_outputR\x06stdoutR\x06stderrR\x04pathR\afailureR\favailabilityR\fresult_stateR\texit_codeR\n" +
	"oom_killedR\atimeout\"#\n" +
	"!ReportTerminalDiagnosticsResponse*\xcd\x06\n" +
	"\x1aEngineExecutionFailedStage\x12)\n" +
	"%ENGINE_EXECUTION_FAILED_STAGE_UNKNOWN\x10\x00\x121\n" +
	"-ENGINE_EXECUTION_FAILED_STAGE_PLAN_VALIDATION\x10\x01\x127\n" +
	"3ENGINE_EXECUTION_FAILED_STAGE_INPUT_MATERIALIZATION\x10\x02\x12:\n" +
	"6ENGINE_EXECUTION_FAILED_STAGE_RESOURCE_MATERIALIZATION\x10\x03\x12/\n" +
	"+ENGINE_EXECUTION_FAILED_STAGE_CONTEXT_BUILD\x10\x04\x12/\n" +
	"+ENGINE_EXECUTION_FAILED_STAGE_IMAGE_PREPARE\x10\x05\x122\n" +
	".ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CREATE\x10\x06\x121\n" +
	"-ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_START\x10\a\x120\n" +
	",ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_WAIT\x10\b\x123\n" +
	"/ENGINE_EXECUTION_FAILED_STAGE_CONTAINER_CLEANUP\x10\t\x124\n" +
	"0ENGINE_EXECUTION_FAILED_STAGE_PROTOCOL_BOOTSTRAP\x10\n" +
	"\x126\n" +
	"2ENGINE_EXECUTION_FAILED_STAGE_EXECUTION_PROJECTION\x10\v\x12)\n" +
	"%ENGINE_EXECUTION_FAILED_STAGE_HANDLER\x10\f\x121\n" +
	"-ENGINE_EXECUTION_FAILED_STAGE_PROGRESS_REPORT\x10\r\x12/\n" +
	"+ENGINE_EXECUTION_FAILED_STAGE_RESULT_ENCODE\x10\x0e\x12/\n" +
	"+ENGINE_EXECUTION_FAILED_STAGE_RESULT_SUBMIT\x10\x0f*\xac\t\n" +
	"\x18EngineExecutionErrorType\x12+\n" +
	"'ENGINE_EXECUTION_ERROR_TYPE_UNSPECIFIED\x10\x00\x120\n" +
	",ENGINE_EXECUTION_ERROR_TYPE_EXECUTION_FAILED\x10\x01\x126\n" +
	"2ENGINE_EXECUTION_ERROR_TYPE_PLAN_VALIDATION_FAILED\x10\x02\x12<\n" +
	"8ENGINE_EXECUTION_ERROR_TYPE_INPUT_MATERIALIZATION_FAILED\x10\x03\x12?\n" +
	";ENGINE_EXECUTION_ERROR_TYPE_RESOURCE_MATERIALIZATION_FAILED\x10\x04\x124\n" +
	"0ENGINE_EXECUTION_ERROR_TYPE_CONTEXT_BUILD_FAILED\x10\x05\x124\n" +
	"0ENGINE_EXECUTION_ERROR_TYPE_IMAGE_PREPARE_FAILED\x10\x06\x127\n" +
	"3ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CREATE_FAILED\x10\a\x126\n" +
	"2ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_START_FAILED\x10\b\x125\n" +
	"1ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_WAIT_FAILED\x10\t\x128\n" +
	"4ENGINE_EXECUTION_ERROR_TYPE_CONTAINER_CLEANUP_FAILED\x10\n" +
	"\x129\n" +
	"5ENGINE_EXECUTION_ERROR_TYPE_PROTOCOL_BOOTSTRAP_FAILED\x10\v\x12.\n" +
	"*ENGINE_EXECUTION_ERROR_TYPE_HANDLER_FAILED\x10\f\x126\n" +
	"2ENGINE_EXECUTION_ERROR_TYPE_PROGRESS_REPORT_FAILED\x10\r\x124\n" +
	"0ENGINE_EXECUTION_ERROR_TYPE_RESULT_ENCODE_FAILED\x10\x0e\x124\n" +
	"0ENGINE_EXECUTION_ERROR_TYPE_RESULT_SUBMIT_FAILED\x10\x0f\x12'\n" +
	"#ENGINE_EXECUTION_ERROR_TYPE_TIMEOUT\x10\x10\x12)\n" +
	"%ENGINE_EXECUTION_ERROR_TYPE_CANCELLED\x10\x11\x12*\n" +
	"&ENGINE_EXECUTION_ERROR_TYPE_OOM_KILLED\x10\x12\x124\n" +
	"0ENGINE_EXECUTION_ERROR_TYPE_AGENT_SESSION_FAILED\x10\x13\x12/\n" +
	"+ENGINE_EXECUTION_ERROR_TYPE_INVALID_OUTCOME\x10\x14\x126\n" +
	"2ENGINE_EXECUTION_ERROR_TYPE_RESULT_PROTOCOL_FAILED\x10\x15*\xd3\x01\n" +
	"%EngineExecutionDiagnosticAvailability\x128\n" +
	"4ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNSPECIFIED\x10\x00\x126\n" +
	"2ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_AVAILABLE\x10\x01\x128\n" +
	"4ENGINE_EXECUTION_DIAGNOSTIC_AVAILABILITY_UNAVAILABLE\x10\x02*\xf5\x01\n" +
	"\x1aEngineExecutionResultState\x12-\n" +
	")ENGINE_EXECUTION_RESULT_STATE_UNSPECIFIED\x10\x00\x12*\n" +
	"&ENGINE_EXECUTION_RESULT_STATE_COMPLETE\x10\x01\x12)\n" +
	"%ENGINE_EXECUTION_RESULT_STATE_PARTIAL\x10\x02\x12&\n" +
	"\"ENGINE_EXECUTION_RESULT_STATE_NONE\x10\x03\x12)\n" +
	"%ENGINE_EXECUTION_RESULT_STATE_UNKNOWN\x10\x04*\x8c\x01\n" +
	"\x1eEngineExecutionDiagnosticLimit\x121\n" +
	"-ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_UNSPECIFIED\x10\x00\x127\n" +
	"3ENGINE_EXECUTION_DIAGNOSTIC_LIMIT_RESULT_TYPE_COUNT\x10\x102\xe9\x02\n" +
	"!EngineExecutionDiagnosticsService\x12\xa6\x01\n" +
	"\x1dEstablishExecutionDiagnostics\x12A.lunafox.engine.execution.v2.EstablishExecutionDiagnosticsRequest\x1aB.lunafox.engine.execution.v2.EstablishExecutionDiagnosticsResponse\x12\x9a\x01\n" +
	"\x19ReportTerminalDiagnostics\x12=.lunafox.engine.execution.v2.ReportTerminalDiagnosticsRequest\x1a>.lunafox.engine.execution.v2.ReportTerminalDiagnosticsResponseB7Z5github.com/yyhuni/lunafox/engine-go/protocol;protocolb\x06proto3"

var (
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescOnce sync.Once
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescData []byte
)

func file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescGZIP() []byte {
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescOnce.Do(func() {
		file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDesc)))
	})
	return file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDescData
}

var file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_goTypes = []any{
	(EngineExecutionFailedStage)(0),               // 0: lunafox.engine.execution.v2.EngineExecutionFailedStage
	(EngineExecutionErrorType)(0),                 // 1: lunafox.engine.execution.v2.EngineExecutionErrorType
	(EngineExecutionDiagnosticAvailability)(0),    // 2: lunafox.engine.execution.v2.EngineExecutionDiagnosticAvailability
	(EngineExecutionResultState)(0),               // 3: lunafox.engine.execution.v2.EngineExecutionResultState
	(EngineExecutionDiagnosticLimit)(0),           // 4: lunafox.engine.execution.v2.EngineExecutionDiagnosticLimit
	(*ResultTypeWatermark)(nil),                   // 5: lunafox.engine.execution.v2.ResultTypeWatermark
	(*EngineTerminalDiagnosticSnapshot)(nil),      // 6: lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshot
	(*EngineExecutionDiagnostics)(nil),            // 7: lunafox.engine.execution.v2.EngineExecutionDiagnostics
	(*EstablishExecutionDiagnosticsRequest)(nil),  // 8: lunafox.engine.execution.v2.EstablishExecutionDiagnosticsRequest
	(*EstablishExecutionDiagnosticsResponse)(nil), // 9: lunafox.engine.execution.v2.EstablishExecutionDiagnosticsResponse
	(*ReportTerminalDiagnosticsRequest)(nil),      // 10: lunafox.engine.execution.v2.ReportTerminalDiagnosticsRequest
	(*ReportTerminalDiagnosticsResponse)(nil),     // 11: lunafox.engine.execution.v2.ReportTerminalDiagnosticsResponse
}
var file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_depIdxs = []int32{
	0,  // 0: lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshot.failed_stage:type_name -> lunafox.engine.execution.v2.EngineExecutionFailedStage
	1,  // 1: lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshot.error_type:type_name -> lunafox.engine.execution.v2.EngineExecutionErrorType
	5,  // 2: lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshot.result_type_watermarks:type_name -> lunafox.engine.execution.v2.ResultTypeWatermark
	2,  // 3: lunafox.engine.execution.v2.EngineExecutionDiagnostics.availability:type_name -> lunafox.engine.execution.v2.EngineExecutionDiagnosticAvailability
	3,  // 4: lunafox.engine.execution.v2.EngineExecutionDiagnostics.result_state:type_name -> lunafox.engine.execution.v2.EngineExecutionResultState
	0,  // 5: lunafox.engine.execution.v2.EngineExecutionDiagnostics.failed_stage:type_name -> lunafox.engine.execution.v2.EngineExecutionFailedStage
	1,  // 6: lunafox.engine.execution.v2.EngineExecutionDiagnostics.error_type:type_name -> lunafox.engine.execution.v2.EngineExecutionErrorType
	5,  // 7: lunafox.engine.execution.v2.EngineExecutionDiagnostics.result_type_watermarks:type_name -> lunafox.engine.execution.v2.ResultTypeWatermark
	6,  // 8: lunafox.engine.execution.v2.ReportTerminalDiagnosticsRequest.snapshot:type_name -> lunafox.engine.execution.v2.EngineTerminalDiagnosticSnapshot
	8,  // 9: lunafox.engine.execution.v2.EngineExecutionDiagnosticsService.EstablishExecutionDiagnostics:input_type -> lunafox.engine.execution.v2.EstablishExecutionDiagnosticsRequest
	10, // 10: lunafox.engine.execution.v2.EngineExecutionDiagnosticsService.ReportTerminalDiagnostics:input_type -> lunafox.engine.execution.v2.ReportTerminalDiagnosticsRequest
	9,  // 11: lunafox.engine.execution.v2.EngineExecutionDiagnosticsService.EstablishExecutionDiagnostics:output_type -> lunafox.engine.execution.v2.EstablishExecutionDiagnosticsResponse
	11, // 12: lunafox.engine.execution.v2.EngineExecutionDiagnosticsService.ReportTerminalDiagnostics:output_type -> lunafox.engine.execution.v2.ReportTerminalDiagnosticsResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_init() }
func file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_init() {
	if File_lunafox_engine_execution_v2_engine_execution_diagnostics_proto != nil {
		return
	}
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[1].OneofWrappers = []any{}
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_goTypes,
		DependencyIndexes: file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_depIdxs,
		EnumInfos:         file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_enumTypes,
		MessageInfos:      file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_msgTypes,
	}.Build()
	File_lunafox_engine_execution_v2_engine_execution_diagnostics_proto = out.File
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_goTypes = nil
	file_lunafox_engine_execution_v2_engine_execution_diagnostics_proto_depIdxs = nil
}
