// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_reporting.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportProgressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is a single non-empty bounded UTF-8 progress event.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProgressRequest) Reset() {
	*x = ReportProgressRequest{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressRequest) ProtoMessage() {}

func (x *ReportProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportProgressRequest) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *ReportProgressRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// An empty response means only that the Server-backed operation completed OK.
type ReportProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProgressResponse) Reset() {
	*x = ReportProgressResponse{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressResponse) ProtoMessage() {}

func (x *ReportProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportProgressResponse) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescGZIP(), []int{1}
}

type SubmitResultBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result_type is an explicit canonical Server-owned result descriptor ID.
	ResultType string `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	// items are bounded, independently serialized canonical result items. The
	// bytes are preserved exactly for an allowed same-session replay.
	Items         [][]byte `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultBatchRequest) Reset() {
	*x = SubmitResultBatchRequest{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultBatchRequest) ProtoMessage() {}

func (x *SubmitResultBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultBatchRequest) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitResultBatchRequest) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *SubmitResultBatchRequest) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// An empty response means only that the Server-backed whole-batch operation
// completed OK.
type SubmitResultBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultBatchResponse) Reset() {
	*x = SubmitResultBatchResponse{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultBatchResponse) ProtoMessage() {}

func (x *SubmitResultBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultBatchResponse) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescGZIP(), []int{3}
}

var File_lunafox_engine_execution_v2_engine_execution_reporting_proto protoreflect.FileDescriptor

const file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDesc = "" +
	"\n" +
	"<lunafox/engine/execution/v2/engine_execution_reporting.proto\x12\x1blunafox.engine.execution.v2\"\xe6\x01\n" +
	"\x15ReportProgressRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageJ\b\b\x02\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x06targetR\apackageR\x05imageR\n" +
	"request_idR\bsequenceR\x05levelR\n" +
	"emitted_atR\aentriesR\asummaryR\bacceptedR\x05countR\asuccessR\n" +
	"credentialR\x06secretR\afailureR\bterminal\"\x18\n" +
	"\x16ReportProgressResponse\"\x95\x02\n" +
	"\x18SubmitResultBatchRequest\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12\x14\n" +
	"\x05items\x18\x02 \x03(\fR\x05itemsJ\b\b\x03\x10\x80\x80\x80\x80\x02R\x04taskR\x04scanR\texecutionR\x06targetR\apackageR\x05imageR\n" +
	"request_idR\bsequenceR\asummaryR\bacceptedR\tduplicateR\ainvalidR\bfilteredR\vunsupportedR\x05totalR\asuccessR\n" +
	"credentialR\x06secretR\afailureR\bterminal\"\x1b\n" +
	"\x19SubmitResultBatchResponse2\xa1\x02\n" +
	"\x1fEngineExecutionReportingService\x12y\n" +
	"\x0eReportProgress\x122.lunafox.engine.execution.v2.ReportProgressRequest\x1a3.lunafox.engine.execution.v2.ReportProgressResponse\x12\x82\x01\n" +
	"\x11SubmitResultBatch\x125.lunafox.engine.execution.v2.SubmitResultBatchRequest\x1a6.lunafox.engine.execution.v2.SubmitResultBatchResponseB7Z5github.com/yyhuni/lunafox/engine-go/protocol;protocolb\x06proto3"

var (
	file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescOnce sync.Once
	file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescData []byte
)

func file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescGZIP() []byte {
	file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescOnce.Do(func() {
		file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDesc)))
	})
	return file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDescData
}

var file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lunafox_engine_execution_v2_engine_execution_reporting_proto_goTypes = []any{
	(*ReportProgressRequest)(nil),     // 0: lunafox.engine.execution.v2.ReportProgressRequest
	(*ReportProgressResponse)(nil),    // 1: lunafox.engine.execution.v2.ReportProgressResponse
	(*SubmitResultBatchRequest)(nil),  // 2: lunafox.engine.execution.v2.SubmitResultBatchRequest
	(*SubmitResultBatchResponse)(nil), // 3: lunafox.engine.execution.v2.SubmitResultBatchResponse
}
var file_lunafox_engine_execution_v2_engine_execution_reporting_proto_depIdxs = []int32{
	0, // 0: lunafox.engine.execution.v2.EngineExecutionReportingService.ReportProgress:input_type -> lunafox.engine.execution.v2.ReportProgressRequest
	2, // 1: lunafox.engine.execution.v2.EngineExecutionReportingService.SubmitResultBatch:input_type -> lunafox.engine.execution.v2.SubmitResultBatchRequest
	1, // 2: lunafox.engine.execution.v2.EngineExecutionReportingService.ReportProgress:output_type -> lunafox.engine.execution.v2.ReportProgressResponse
	3, // 3: lunafox.engine.execution.v2.EngineExecutionReportingService.SubmitResultBatch:output_type -> lunafox.engine.execution.v2.SubmitResultBatchResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lunafox_engine_execution_v2_engine_execution_reporting_proto_init() }
func file_lunafox_engine_execution_v2_engine_execution_reporting_proto_init() {
	if File_lunafox_engine_execution_v2_engine_execution_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lunafox_engine_execution_v2_engine_execution_reporting_proto_goTypes,
		DependencyIndexes: file_lunafox_engine_execution_v2_engine_execution_reporting_proto_depIdxs,
		MessageInfos:      file_lunafox_engine_execution_v2_engine_execution_reporting_proto_msgTypes,
	}.Build()
	File_lunafox_engine_execution_v2_engine_execution_reporting_proto = out.File
	file_lunafox_engine_execution_v2_engine_execution_reporting_proto_goTypes = nil
	file_lunafox_engine_execution_v2_engine_execution_reporting_proto_depIdxs = nil
}
