// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: lunafox/engine/execution/v2/engine_execution_context.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EngineExecutionContext is the passive, major-selected binary protobuf
// startup snapshot mounted into an Engine Container. During disposable
// pre-release development this major is rebuilt in place; after the first
// stable release, breaking Engine-visible changes require a new major.
type EngineExecutionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target contains only the business target type and canonical value.
	Target *CanonicalTarget `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// compatibility_revision is the fixed post-cut revision shared by every
	// Engine execution participant. Engines reject a missing or mismatched value
	// before opening the reporting session.
	CompatibilityRevision string `protobuf:"bytes,2,opt,name=compatibility_revision,json=compatibilityRevision,proto3" json:"compatibility_revision,omitempty"`
	// config contains section enablement and validated scalar parameters.
	Config *EngineExecutionConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// config_resources contains one materialized file for each declared
	// section/parameter resource binding.
	ConfigResources []*ConfigResource `protobuf:"bytes,4,rep,name=config_resources,json=configResources,proto3" json:"config_resources,omitempty"`
	// platform_resources contains logical resources needed by this execution.
	PlatformResources []*PlatformResource `protobuf:"bytes,5,rep,name=platform_resources,json=platformResources,proto3" json:"platform_resources,omitempty"`
	// limits contains only progress and result transport limits.
	Limits        *ExecutionLimits `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineExecutionContext) Reset() {
	*x = EngineExecutionContext{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineExecutionContext) ProtoMessage() {}

func (x *EngineExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineExecutionContext.ProtoReflect.Descriptor instead.
func (*EngineExecutionContext) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{0}
}

func (x *EngineExecutionContext) GetTarget() *CanonicalTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EngineExecutionContext) GetCompatibilityRevision() string {
	if x != nil {
		return x.CompatibilityRevision
	}
	return ""
}

func (x *EngineExecutionContext) GetConfig() *EngineExecutionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *EngineExecutionContext) GetConfigResources() []*ConfigResource {
	if x != nil {
		return x.ConfigResources
	}
	return nil
}

func (x *EngineExecutionContext) GetPlatformResources() []*PlatformResource {
	if x != nil {
		return x.PlatformResources
	}
	return nil
}

func (x *EngineExecutionContext) GetLimits() *ExecutionLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// CanonicalTarget is the business type/value Target projection.
type CanonicalTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalTarget) Reset() {
	*x = CanonicalTarget{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalTarget) ProtoMessage() {}

func (x *CanonicalTarget) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalTarget.ProtoReflect.Descriptor instead.
func (*CanonicalTarget) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{1}
}

func (x *CanonicalTarget) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CanonicalTarget) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// EngineExecutionConfig is a closed repeated section/parameter model. It
// avoids a generic map while allowing each Engine's validated scalar schema.
type EngineExecutionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*ConfigSection       `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineExecutionConfig) Reset() {
	*x = EngineExecutionConfig{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineExecutionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineExecutionConfig) ProtoMessage() {}

func (x *EngineExecutionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineExecutionConfig.ProtoReflect.Descriptor instead.
func (*EngineExecutionConfig) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{2}
}

func (x *EngineExecutionConfig) GetSections() []*ConfigSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ConfigSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Params        []*ConfigValue         `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSection) Reset() {
	*x = ConfigSection{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSection) ProtoMessage() {}

func (x *ConfigSection) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSection.ProtoReflect.Descriptor instead.
func (*ConfigSection) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSection) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *ConfigSection) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ConfigSection) GetParams() []*ConfigValue {
	if x != nil {
		return x.Params
	}
	return nil
}

// ConfigValue admits only the closed value kinds supported by engine.v5 config.
type ConfigValue struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ParamKey string                 `protobuf:"bytes,1,opt,name=param_key,json=paramKey,proto3" json:"param_key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigValue_StringValue
	//	*ConfigValue_IntegerValue
	//	*ConfigValue_BooleanValue
	//	*ConfigValue_StringArrayValue
	Value         isConfigValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigValue) GetParamKey() string {
	if x != nil {
		return x.ParamKey
	}
	return ""
}

func (x *ConfigValue) GetValue() isConfigValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ConfigValue) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *ConfigValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *ConfigValue) GetStringArrayValue() *StringArrayValue {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_StringArrayValue); ok {
			return x.StringArrayValue
		}
	}
	return nil
}

type isConfigValue_Value interface {
	isConfigValue_Value()
}

type ConfigValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ConfigValue_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type ConfigValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type ConfigValue_StringArrayValue struct {
	StringArrayValue *StringArrayValue `protobuf:"bytes,5,opt,name=string_array_value,json=stringArrayValue,proto3,oneof"`
}

func (*ConfigValue_StringValue) isConfigValue_Value() {}

func (*ConfigValue_IntegerValue) isConfigValue_Value() {}

func (*ConfigValue_BooleanValue) isConfigValue_Value() {}

func (*ConfigValue_StringArrayValue) isConfigValue_Value() {}

type StringArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArrayValue) Reset() {
	*x = StringArrayValue{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayValue) ProtoMessage() {}

func (x *StringArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayValue.ProtoReflect.Descriptor instead.
func (*StringArrayValue) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{5}
}

func (x *StringArrayValue) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// ConfigResource is partitioned by the original section ID and parameter key.
type ConfigResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	ParamKey      string                 `protobuf:"bytes,2,opt,name=param_key,json=paramKey,proto3" json:"param_key,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResource) Reset() {
	*x = ConfigResource{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResource) ProtoMessage() {}

func (x *ConfigResource) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResource.ProtoReflect.Descriptor instead.
func (*ConfigResource) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigResource) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *ConfigResource) GetParamKey() string {
	if x != nil {
		return x.ParamKey
	}
	return ""
}

func (x *ConfigResource) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigResource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// PlatformResource is partitioned by one canonical platform-owned logical ID.
type PlatformResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformResource) Reset() {
	*x = PlatformResource{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformResource) ProtoMessage() {}

func (x *PlatformResource) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformResource.ProtoReflect.Descriptor instead.
func (*PlatformResource) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{7}
}

func (x *PlatformResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PlatformResource) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PlatformResource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ExecutionLimits deliberately excludes max_execution_duration and deadlines.
type ExecutionLimits struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProgressMessageMaxBytes uint32                 `protobuf:"varint,1,opt,name=progress_message_max_bytes,json=progressMessageMaxBytes,proto3" json:"progress_message_max_bytes,omitempty"`
	ResultBatchMaxItems     uint32                 `protobuf:"varint,2,opt,name=result_batch_max_items,json=resultBatchMaxItems,proto3" json:"result_batch_max_items,omitempty"`
	ResultBatchMaxBytes     uint32                 `protobuf:"varint,3,opt,name=result_batch_max_bytes,json=resultBatchMaxBytes,proto3" json:"result_batch_max_bytes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ExecutionLimits) Reset() {
	*x = ExecutionLimits{}
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLimits) ProtoMessage() {}

func (x *ExecutionLimits) ProtoReflect() protoreflect.Message {
	mi := &file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLimits.ProtoReflect.Descriptor instead.
func (*ExecutionLimits) Descriptor() ([]byte, []int) {
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionLimits) GetProgressMessageMaxBytes() uint32 {
	if x != nil {
		return x.ProgressMessageMaxBytes
	}
	return 0
}

func (x *ExecutionLimits) GetResultBatchMaxItems() uint32 {
	if x != nil {
		return x.ResultBatchMaxItems
	}
	return 0
}

func (x *ExecutionLimits) GetResultBatchMaxBytes() uint32 {
	if x != nil {
		return x.ResultBatchMaxBytes
	}
	return 0
}

var File_lunafox_engine_execution_v2_engine_execution_context_proto protoreflect.FileDescriptor

const file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDesc = "" +
	"\n" +
	":lunafox/engine/execution/v2/engine_execution_context.proto\x12\x1blunafox.engine.execution.v2\"\xf9\x05\n" +
	"\x16EngineExecutionContext\x12D\n" +
	"\x06target\x18\x01 \x01(\v2,.lunafox.engine.execution.v2.CanonicalTargetR\x06target\x125\n" +
	"\x16compatibility_revision\x18\x02 \x01(\tR\x15compatibilityRevision\x12J\n" +
	"\x06config\x18\x03 \x01(\v22.lunafox.engine.execution.v2.EngineExecutionConfigR\x06config\x12V\n" +
	"\x10config_resources\x18\x04 \x03(\v2+.lunafox.engine.execution.v2.ConfigResourceR\x0fconfigResources\x12\\\n" +
	"\x12platform_resources\x18\x05 \x03(\v2-.lunafox.engine.execution.v2.PlatformResourceR\x11platformResources\x12D\n" +
	"\x06limits\x18\x06 \x01(\v2,.lunafox.engine.execution.v2.ExecutionLimitsR\x06limitsJ\b\b\a\x10\x80\x80\x80\x80\x02R\texecutionR\x04taskR\rworkflow_stepR\tworkspaceR\x0fcontext_versionR\x16max_execution_durationR\bdeadlineR\x11absolute_deadlineR\thost_pathR\n" +
	"cache_pathR\x05mountR\x06mountsR\n" +
	"credentialR\x03udsR\rruntime_imageR\apackageR\fresult_typesR\x10result_allow_setR\x10generic_bindingsR\x16control_plane_identityR\x06inputs\"k\n" +
	"\x0fCanonicalTarget\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueJ\b\b\x03\x10\x80\x80\x80\x80\x02R\bresourceR\ttarget_idR\x0ftarget_resource\"i\n" +
	"\x15EngineExecutionConfig\x12F\n" +
	"\bsections\x18\x01 \x03(\v2*.lunafox.engine.execution.v2.ConfigSectionR\bsectionsJ\b\b\x02\x10\x80\x80\x80\x80\x02\"\xa5\x01\n" +
	"\rConfigSection\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x00R\aenabled\x88\x01\x01\x12@\n" +
	"\x06params\x18\x03 \x03(\v2(.lunafox.engine.execution.v2.ConfigValueR\x06paramsB\n" +
	"\n" +
	"\b_enabledJ\b\b\x04\x10\x80\x80\x80\x80\x02\"\x8f\x02\n" +
	"\vConfigValue\x12\x1b\n" +
	"\tparam_key\x18\x01 \x01(\tR\bparamKey\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rinteger_value\x18\x03 \x01(\x03H\x00R\fintegerValue\x12%\n" +
	"\rboolean_value\x18\x04 \x01(\bH\x00R\fbooleanValue\x12]\n" +
	"\x12string_array_value\x18\x05 \x01(\v2-.lunafox.engine.execution.v2.StringArrayValueH\x00R\x10stringArrayValueB\a\n" +
	"\x05valueJ\b\b\x06\x10\x80\x80\x80\x80\x02\"*\n" +
	"\x10StringArrayValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xcb\x01\n" +
	"\x0eConfigResource\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\x12\x1b\n" +
	"\tparam_key\x18\x02 \x01(\tR\bparamKey\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04pathJ\b\b\x05\x10\x80\x80\x80\x80\x02R\x04fileR\x04kindR\bresourceR\frecord_countR\rsha256_digestR\thost_path\"\xb2\x01\n" +
	"\x10PlatformResource\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04pathJ\b\b\x04\x10\x80\x80\x80\x80\x02R\x04fileR\x04kindR\bresourceR\frecord_countR\rsha256_digestR\thost_path\"\xc2\x01\n" +
	"\x0fExecutionLimits\x12;\n" +
	"\x1aprogress_message_max_bytes\x18\x01 \x01(\rR\x17progressMessageMaxBytes\x123\n" +
	"\x16result_batch_max_items\x18\x02 \x01(\rR\x13resultBatchMaxItems\x123\n" +
	"\x16result_batch_max_bytes\x18\x03 \x01(\rR\x13resultBatchMaxBytesJ\b\b\x04\x10\x80\x80\x80\x80\x02B7Z5github.com/yyhuni/lunafox/engine-go/protocol;protocolb\x06proto3"

var (
	file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescOnce sync.Once
	file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescData []byte
)

func file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescGZIP() []byte {
	file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescOnce.Do(func() {
		file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDesc)))
	})
	return file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDescData
}

var file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lunafox_engine_execution_v2_engine_execution_context_proto_goTypes = []any{
	(*EngineExecutionContext)(nil), // 0: lunafox.engine.execution.v2.EngineExecutionContext
	(*CanonicalTarget)(nil),        // 1: lunafox.engine.execution.v2.CanonicalTarget
	(*EngineExecutionConfig)(nil),  // 2: lunafox.engine.execution.v2.EngineExecutionConfig
	(*ConfigSection)(nil),          // 3: lunafox.engine.execution.v2.ConfigSection
	(*ConfigValue)(nil),            // 4: lunafox.engine.execution.v2.ConfigValue
	(*StringArrayValue)(nil),       // 5: lunafox.engine.execution.v2.StringArrayValue
	(*ConfigResource)(nil),         // 6: lunafox.engine.execution.v2.ConfigResource
	(*PlatformResource)(nil),       // 7: lunafox.engine.execution.v2.PlatformResource
	(*ExecutionLimits)(nil),        // 8: lunafox.engine.execution.v2.ExecutionLimits
}
var file_lunafox_engine_execution_v2_engine_execution_context_proto_depIdxs = []int32{
	1, // 0: lunafox.engine.execution.v2.EngineExecutionContext.target:type_name -> lunafox.engine.execution.v2.CanonicalTarget
	2, // 1: lunafox.engine.execution.v2.EngineExecutionContext.config:type_name -> lunafox.engine.execution.v2.EngineExecutionConfig
	6, // 2: lunafox.engine.execution.v2.EngineExecutionContext.config_resources:type_name -> lunafox.engine.execution.v2.ConfigResource
	7, // 3: lunafox.engine.execution.v2.EngineExecutionContext.platform_resources:type_name -> lunafox.engine.execution.v2.PlatformResource
	8, // 4: lunafox.engine.execution.v2.EngineExecutionContext.limits:type_name -> lunafox.engine.execution.v2.ExecutionLimits
	3, // 5: lunafox.engine.execution.v2.EngineExecutionConfig.sections:type_name -> lunafox.engine.execution.v2.ConfigSection
	4, // 6: lunafox.engine.execution.v2.ConfigSection.params:type_name -> lunafox.engine.execution.v2.ConfigValue
	5, // 7: lunafox.engine.execution.v2.ConfigValue.string_array_value:type_name -> lunafox.engine.execution.v2.StringArrayValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_lunafox_engine_execution_v2_engine_execution_context_proto_init() }
func file_lunafox_engine_execution_v2_engine_execution_context_proto_init() {
	if File_lunafox_engine_execution_v2_engine_execution_context_proto != nil {
		return
	}
	file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[3].OneofWrappers = []any{}
	file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes[4].OneofWrappers = []any{
		(*ConfigValue_StringValue)(nil),
		(*ConfigValue_IntegerValue)(nil),
		(*ConfigValue_BooleanValue)(nil),
		(*ConfigValue_StringArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDesc), len(file_lunafox_engine_execution_v2_engine_execution_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lunafox_engine_execution_v2_engine_execution_context_proto_goTypes,
		DependencyIndexes: file_lunafox_engine_execution_v2_engine_execution_context_proto_depIdxs,
		MessageInfos:      file_lunafox_engine_execution_v2_engine_execution_context_proto_msgTypes,
	}.Build()
	File_lunafox_engine_execution_v2_engine_execution_context_proto = out.File
	file_lunafox_engine_execution_v2_engine_execution_context_proto_goTypes = nil
	file_lunafox_engine_execution_v2_engine_execution_context_proto_depIdxs = nil
}
