import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/search/search-page-sections.tsx"), "utf8")
const initialShellSource = readFileSync(path.resolve(process.cwd(), "components/search/search-initial-page-shell.tsx"), "utf8")

describe("search-page-sections contract", () => {
  it("owns the strict query form and result handoff at the route surface", () => {
    expect(source).toContain("export function SearchPageContent")
    expect(source).toContain("ContentHandoff")
    expect(source).toContain('from "./search-initial-page-shell"')
    expect(source).toContain("<form")
    expect(source).toContain('type="search"')
    expect(source).toContain('aria-invalid={Boolean(state.queryError)}')
    expect(source).not.toContain('from "next/dynamic"')
    expect(source).not.toContain("smart-filter-input")
    expect(source).not.toContain("vulnerability")
  })

  it("keeps the initial search shell owned by the resolved page", () => {
    expect(initialShellSource).toContain("export function SearchInitialPageShell")
    expect(initialShellSource).toContain("animated?: boolean")
    expect(source).toContain("<SearchInitialPageShell animated>")
    expect(initialShellSource).toContain("export function SearchInitialHeading")
    expect(initialShellSource).toContain("export function SearchQuickTags")
    expect(initialShellSource).toContain("export function SearchAssetBarShell")
    expect(initialShellSource).toContain("export const QUICK_SEARCH_TAGS")
    expect(initialShellSource).toContain("animate-in fade-in slide-in-from-bottom-4 duration-300")
  })

  it("keeps search results under a single route-owned loading surface instead of chunk-local raw rectangles", () => {
    expect(source).toContain('from "./search-websites-data-table"')
    expect(source).toContain('from "./search-results-table"')
    expect(source).toContain("function AssetSearchBar")
    expect(source).toContain('from "./search-syntax-guidance"')
    expect(source).toContain("<SearchSyntaxGuidance")
    expect(source).toContain("onFocus={openSyntaxGuidance}")
    expect(source).toContain("onClick={openSyntaxGuidance}")
    expect(source).toContain("onBlur={scheduleCloseSyntaxGuidance}")
    expect(source).toContain("getGlobalAssetSearchInlineCompletion")
    expect(source).toContain("onKeyDown={handleInputKeyDown}")
    expect(initialShellSource).toContain("max-w-4xl")
    expect(initialShellSource).toContain("radius-control-prominent flex h-9")
    expect(source).toContain("radius-none w-40")
    expect(source).toContain("border-0 border-r")
    expect(source).toContain('placeholder={state.t("searchPlaceholder")}')
    expect(source).toContain('value={state.query}')
    expect(source).toContain("onChange={handleInputChange}")
    expect(source).toContain('onValueChange={state.handleAssetTypeChange}')
    expect(source).toContain('inline-flex min-w-0 items-center gap-1.5')
    expect(source).toContain('<semanticIcons.concept.website className="h-4 w-4 shrink-0 text-muted-foreground" />')
    expect(source).toContain('<semanticIcons.concept.endpoint className="h-4 w-4 shrink-0 text-muted-foreground" />')
    expect(source).toContain('isLoading={state.searchState === "searching" || state.isLoading}')
    expect(source).toContain('owner="search-results-content"')
    expect(source).toContain("SearchResultsLoadingState")
    expect(source).toContain("SearchWebsitesDataTableLoadingState")
    expect(source).toContain('showWebsiteExport={state.assetType === "website"}')
    expect(source).toContain("SearchResultsToolbarRegion")
    expect(source).toContain("SearchResultsBodyRegion")
    expect(source).toContain("SearchResultsPaginationRegion")
    expect(source).toContain('getLoadingStructureSlotAttributes("search-results-toolbar")')
    expect(source).toContain('getLoadingStructureSlotAttributes("search-results-body")')
    expect(source).toContain('getLoadingStructureSlotAttributes("search-results-pagination")')
    expect(source).toContain("SelectShellSkeleton")
    expect(source).toContain("CompactPaginationSkeleton")
    expect(source).toContain('<CompactPaginationSkeleton mode="cursor"')
    expect(source).toContain("<SearchResultsPaginationRegion>")
    expect(source).not.toContain('owner="search-results-loading"')
    expect(source).toContain('className="flex h-full flex-col"')
    expect(source).toContain('skeletonClassName="flex h-full flex-col"')
    expect(source).toContain('contentClassName="flex h-full flex-col"')
    expect(source).not.toContain('loading: () => <Skeleton className="h-32 w-full" />')
    expect(source).not.toContain('loading: () => <Skeleton className="h-64 w-full" />')
    expect(source).not.toContain('loading: () => <Skeleton className="h-10 w-full" />')
  })

  it("aligns resolved and loading search text to the shared Input gutter", () => {
    expect(source).toContain('<PopoverAnchor className="relative flex min-w-0 flex-1">')
    expect(source).toContain('radius-none h-9 min-w-0 border-0 bg-transparent px-3 text-sm')
    expect(source).toContain('radius-none h-9 border-0 bg-transparent px-3 text-sm')
    expect(source).toContain('absolute left-3 h-4 w-32')
    expect(source).not.toContain("px-5")
    expect(source).not.toContain("left-5")
  })

  it("keeps website export beside the global search while endpoint results stay unchanged", () => {
    expect(source).toContain("SearchWebsiteExportMenu")
    expect(source).toContain("websiteResultModel")
    expect(source).toContain('state.assetType === "website"')
    expect(source).not.toContain("totalPages")
    expect(source).not.toContain("vulnerabilit")
  })
})
