#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/release.manifest.yaml"
VERIFY_CONTRACT=0
VERIFY_ENV_FILE=""

usage() {
	cat <<'USAGE'
用法:
  RELEASE_VERSION=1.2.3 \
  AGENT_IMAGE_REF='docker.io/yyhuni/lunafox-agent@sha256:...' \
  WORKER_IMAGE_REF='docker.io/yyhuni/lunafox-worker@sha256:...' \
  ./scripts/ci/generate-release-manifest.sh [--output <path>] [--verify-contract] [--verify-env <path>]

说明:
  - 从环境变量生成 release manifest（单一发布源）。
  - agentVersion / workerVersion 自动等于 RELEASE_VERSION。
  - image ref 必须是 digest 格式（@sha256:...）。
  - --verify-contract 会调用 scripts/ci/verify-release-contract.sh 进行二次校验。
USAGE
}

fail() {
	echo "✗ $*" >&2
	exit 1
}

normalize_version() {
	local value="$1"
	value="$(echo "$value" | xargs)"
	value="${value#v}"
	value="${value#V}"
	echo "$value"
}

validate_semver() {
	local value="$1"
	local name="$2"
	if ! echo "$value" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([+-][-0-9A-Za-z.+_]+)?$'; then
		fail "$name 格式非法: $value"
	fi
}

validate_digest_ref() {
	local value="$1"
	local name="$2"
	if ! echo "$value" | grep -Eq '^.+@sha256:[a-f0-9]{64}$'; then
		fail "$name 必须是 digest 引用（@sha256:...）: $value"
	fi
}

while [ "$#" -gt 0 ]; do
	case "$1" in
	-o | --output)
		[ "$#" -ge 2 ] || fail "$1 缺少参数"
		OUTPUT_FILE="$2"
		shift 2
		;;
	--verify-contract)
		VERIFY_CONTRACT=1
		shift
		;;
	--verify-env)
		[ "$#" -ge 2 ] || fail "$1 缺少参数"
		VERIFY_ENV_FILE="$2"
		VERIFY_CONTRACT=1
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		fail "不支持的参数: $1"
		;;
	esac
done

release_version="$(normalize_version "${RELEASE_VERSION:-}")"
agent_image_ref="$(echo "${AGENT_IMAGE_REF:-}" | xargs)"
worker_image_ref="$(echo "${WORKER_IMAGE_REF:-}" | xargs)"

[ -n "$release_version" ] || fail "缺少环境变量 RELEASE_VERSION"
[ -n "$agent_image_ref" ] || fail "缺少环境变量 AGENT_IMAGE_REF"
[ -n "$worker_image_ref" ] || fail "缺少环境变量 WORKER_IMAGE_REF"

validate_semver "$release_version" "RELEASE_VERSION"
validate_digest_ref "$agent_image_ref" "AGENT_IMAGE_REF"
validate_digest_ref "$worker_image_ref" "WORKER_IMAGE_REF"

if [ -z "$OUTPUT_FILE" ]; then
	fail "--output 不能为空"
fi

if [[ "$OUTPUT_FILE" != /* ]]; then
	OUTPUT_FILE="$ROOT_DIR/$OUTPUT_FILE"
fi

output_dir="$(dirname "$OUTPUT_FILE")"
mkdir -p "$output_dir"

tmp_file="$(mktemp "$output_dir/.release.manifest.XXXXXX.tmp")"
cat >"$tmp_file" <<EOF
# Auto-generated by scripts/ci/generate-release-manifest.sh
# Do not edit manually in CI.

releaseVersion: "$release_version"
agentVersion: "$release_version"
workerVersion: "$release_version"

agentImageRef: "$agent_image_ref"
workerImageRef: "$worker_image_ref"
EOF
mv "$tmp_file" "$OUTPUT_FILE"

if [ "$VERIFY_CONTRACT" -eq 1 ]; then
	verify_script="$ROOT_DIR/scripts/ci/verify-release-contract.sh"
	[ -f "$verify_script" ] || fail "未找到校验脚本: $verify_script"
	env_file_for_verify="$VERIFY_ENV_FILE"
	if [ -z "$env_file_for_verify" ]; then
		# 传入一个不存在的 env 文件路径，只做 manifest 本体校验。
		env_file_for_verify="$ROOT_DIR/.tmp-non-existent.env"
	fi
	bash "$verify_script" "$OUTPUT_FILE" "$env_file_for_verify"
fi

echo "✓ 已生成 release manifest: $OUTPUT_FILE"
