import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/app-sidebar.tsx"), "utf8")

describe("app-sidebar contract", () => {
  it("preserves current source markers", () => {
    expect(source).toContain("export function AppSidebar")
    expect(source).toContain("className")
    expect(source).toContain("from \"react\"")
  })

  it("registers support author as direct footer navigation", () => {
    expect(source).toContain("supportAuthor")
    expect(source).toContain("/settings/support/")
    expect(source).toContain("const SupportAuthorIcon = semanticIcons.navigation.support")
    expect(source).not.toContain('title: t("supportAuthor")')
  })

  it("resolves stable product resources through the canonical concept registry", () => {
    expect(source).toContain("semanticIcons.concept.organization")
    expect(source).toContain("semanticIcons.concept.target")
    expect(source).toContain("semanticIcons.concept.vulnerability")
    expect(source).toContain("semanticIcons.concept.scan")
    expect(source).toContain("semanticIcons.concept.scheduledScan")
    expect(source).toContain("semanticIcons.concept.workflow")
    expect(source).toContain("semanticIcons.concept.wordlist")
    expect(source).toContain("semanticIcons.concept.fingerprint")
    expect(source).toContain("semanticIcons.concept.nucleiRepository")
    expect(source).toContain("semanticIcons.concept.systemLog")
    expect(source).toContain("semanticIcons.concept.database")
    expect(source).not.toContain("semanticIcons.navigation.target")
    expect(source).not.toContain("semanticIcons.navigation.organization")
    expect(source).not.toContain("semanticIcons.concept.engine")
  })

  it("renders the product brand block inside the sidebar header", () => {
    expect(source).toContain("SidebarHeader")
    expect(source).toContain("SidebarGroupLabel")
    expect(source).toContain("LunaFoxMark")
    expect(source).toContain('t("appName")')
    expect(source).toContain('t("communityEditionAbbreviation")')
    expect(source).not.toContain('t("communityEdition")')
    expect(source).not.toContain("TooltipContent")
    expect(source).not.toContain("TooltipTrigger")
    expect(source).toContain("border-b-0")
    expect(source).toContain('from "@/lib/typography"')
    expect(source).toContain("textRole")
    expect(source).not.toContain("Security Console")
  })

  it("keeps the product brand block compact and optically aligned", () => {
    expect(source).toContain("min-h-12")
    expect(source).toContain("size-7")
    expect(source).toContain("size-8 shrink-0 items-center justify-center")
    expect(source).toContain("gap-2")
    expect(source).toContain("w-full")
    expect(source).toContain("h-8")
    expect(source).toContain("px-2.5")
    expect(source).toContain("overflow-hidden rounded-lg")
    expect(source).toContain("group-data-[collapsible=icon]:size-8")
    expect(source).toContain("group-data-[collapsible=icon]:gap-0")
    expect(source).toContain("group-data-[collapsible=icon]:p-0")
    expect(source).not.toContain("group-data-[collapsible=icon]:justify-center")
    expect(source).not.toContain("min-h-16")
    expect(source).not.toContain("min-h-14")
    expect(source).not.toContain('className="size-8 shrink-0"')
  })

  it("groups Overview and Search under the Workspace heading", () => {
    const headerStart = source.indexOf("<SidebarHeader")
    const headerEnd = source.indexOf("</SidebarHeader>")
    const headerSource = source.slice(headerStart, headerEnd)

    expect(source).toContain("semanticIcons.navigation.search")
    expect(source).toContain('url: "/search/"')
    expect(source).toContain("label: t('workspace')")
    expect(source).not.toContain('variant="outline"')
    expect(headerSource).not.toContain('"/search/"')
  })

  it("keeps brand collapse polish off layout-bound transition properties", () => {
    expect(source).not.toContain("transition-[width,height,padding,color,background-color]")
    expect(source).not.toContain("transition-[max-width,opacity]")
  })

  it("uses four task-oriented groups with System Settings as the remaining semantic submenu parent", () => {
    expect(source).toContain("function AppSidebarNavigationGroup")
    expect(source).toContain("label: t('workspace')")
    expect(source).toContain("label: t('assetsAndRisk')")
    expect(source).toContain("label: t('scanning')")
    expect(source).toContain("label: t('tools')")
    expect(source).toContain("label: t('system')")
    expect(source).toContain("title: t('systemSettings')")
    expect(source).not.toContain("label: t('scanResources')")
    expect(source).not.toContain("title: t('tools')")
    expect(source).not.toContain("title: t('runtimeStatus')")
    expect(source).toContain("{group.label ? <SidebarGroupLabel>{group.label}</SidebarGroupLabel> : null}")
    expect(source).not.toContain("label: t('assetManagement')")
    expect(source).not.toContain("label: t('riskAndScanning')")
    expect(source).not.toContain("label: t('toolsAndCapabilities')")
    expect(source).not.toContain("label={t('systemOperations')}")
    expect(source).not.toContain("label={t('systemConfiguration')}")
    expect(source).not.toContain("title: t('scheduling')")
    expect(source).not.toContain("group-data-[collapsible=icon]:px-0 h-8 items-center px-2")
  })

  it("keeps System Settings disclosure-only and promotes scan, tool, and runtime workspaces to direct routes", () => {
    const scanningStart = source.indexOf("label: t('scanning')")
    const toolsStart = source.indexOf("label: t('tools')")
    const systemStart = source.indexOf("label: t('system')")
    const systemSettingsStart = source.indexOf("title: t('systemSettings')")
    const scanningSource = source.slice(scanningStart, toolsStart)
    const toolsSource = source.slice(toolsStart, systemStart)
    const systemDirectRoutesSource = source.slice(systemStart, systemSettingsStart)

    expect(scanningSource).toContain("title: t('scheduledScan')")
    expect(scanningSource).toContain('url: "/scan/scheduled/"')
    expect(scanningSource).toContain("title: t('scanConfiguration')")
    expect(scanningSource).toContain('url: "/scan/config/workflows/"')
    expect(scanningSource).not.toContain("title: t('engines')")
    expect(scanningSource).not.toContain("title: t('scanWorkflow')")
    expect(source).not.toContain("title: t('scanPlans')")
    expect(toolsSource.match(/items:/g)).toHaveLength(1)
    expect(toolsSource).not.toContain('url: "/tools/engines/"')
    expect(toolsSource).not.toContain("spaceMapping")
    expect(toolsSource).not.toContain("space-mapping")
    expect(toolsSource).toContain('url: "/tools/wordlists/"')
    expect(toolsSource).toContain('url: "/tools/fingerprints/fingerprinthub/"')
    expect(toolsSource).toContain('url: "/tools/nuclei/"')
    expect(systemDirectRoutesSource).toContain("title: t('nodesManagement')")
    expect(systemDirectRoutesSource).toContain('url: "/settings/agents/"')
    expect(systemDirectRoutesSource).toContain("title: t('systemLogs')")
    expect(systemDirectRoutesSource).toContain('url: "/settings/system-logs/"')
    expect(systemDirectRoutesSource).toContain("title: t('databaseHealth')")
    expect(systemDirectRoutesSource).toContain('url: "/settings/database-health/"')
    expect(systemDirectRoutesSource).not.toContain("title: t('runtimeStatus')")
    expect(source).toContain('url: "/settings/notifications/"')
    expect(source).toContain("const itemKey = item.url ?? item.title")
    expect(source).toContain("function isSidebarNavigationItemActive")
  })

  it("hides Login Visual until the GitHub project action unlocks the authenticated account", () => {
    expect(source).toContain('from "@/hooks/use-login-visual"')
    expect(source).toContain("const { unlocked: loginVisualUnlocked } = useLoginVisualDiscoverability()")
    expect(source).toContain("...(loginVisualUnlocked ? [{")
    expect(source).toContain('url: "/settings/login-visual/"')
  })

  it("uses the NavUser-owned skeleton for the warmup footer", () => {
    expect(source).toContain("NavUserSkeleton")
    expect(source).toContain("warmup ? <NavUserSkeleton /> : <NavUser")
    expect(source).not.toContain('from "@/components/ui/skeleton"')
    expect(source).not.toContain('className="flex items-center gap-3 rounded-lg px-2.5 py-2"')
  })

  it("keeps support author and the about action in the fixed footer above the account owner", () => {
    const footerStart = source.indexOf("<SidebarFooter>")
    const footerEnd = source.indexOf("</SidebarFooter>")
    const supportAuthor = source.indexOf('href="/settings/support/"')
    const aboutDialog = source.indexOf("<AboutDialog>")
    const userOwner = source.indexOf("warmup ? <NavUserSkeleton")

    expect(supportAuthor).toBeGreaterThan(footerStart)
    expect(supportAuthor).toBeLessThan(aboutDialog)
    expect(aboutDialog).toBeGreaterThan(footerStart)
    expect(aboutDialog).toBeLessThan(footerEnd)
    expect(userOwner).toBeGreaterThan(aboutDialog)
    expect(source).not.toContain('<SidebarGroup className="mt-auto">')
  })

  it("keeps collapsible navigation triggers on the static shared menu button", () => {
    expect(source).toContain('<CollapsibleTrigger render={<SidebarMenuButton/>}>')
    expect(source).not.toContain('motion="disclosure"')
    expect(source).toContain('<IconChevronRight className="ml-auto"')
    expect(source).not.toContain("group-data-[state=open]/collapsible:rotate-90 ml-auto transition-transform")
  })

  it("exposes collapsible child links through one static collapsed-sidebar menu", () => {
    expect(source).toContain("useSidebar")
    expect(source).toContain('const isCollapsedDesktop = state === "collapsed" && !isMobile')
    expect(source).toContain("function CollapsedSidebarSubmenu")
    expect(source).toContain("const [collapsedMenu, setCollapsedMenu] = React.useState<AppSidebarCollapsedMenuState | null>(null)")
    expect(source).toContain("<CollapsedSidebarSubmenu")
    expect(source).toContain('data-sidebar-collapsed-submenu="true"')
    expect(source).not.toContain("transition-transform duration-150")
    expect(source).not.toContain("outline-none transition-colors hover:bg-sidebar-accent")
    expect(source).toContain("translate3d(${menu.left}px, ${menu.top}px, 0)")
    expect(source).toContain("const MenuIcon = menu.icon")
    expect(source).toContain('<MenuIcon className="size-4 shrink-0"')
    expect(source).toContain("}, 180)")
    expect(source).toContain("onCollapsedMenuOpen({")
    expect(source).toContain('from "@/lib/ui/overlay-styles"')
    expect(source).toContain("left: rect.right + shellOverlaySideOffsets.sidebarDesktop")
    expect(source).toContain("onFocus={openCollapsedMenu}")
    expect(source).toContain("href={subItem.url}")
    expect(source).toContain("prefetch={sidebarLinkPrefetch}")
    expect(source).not.toContain("<Popover open={isCollapsedMenuOpen}")
  })

  it("avoids mounting closed sidebar collapsible content during initial shell hydration", () => {
    expect(source).toContain("function AppSidebarCollapsibleNavItem")
    expect(source).toContain("const [isOpen, setIsOpen] = React.useState(isActive)")
    expect(source).toContain("if (isActive)")
    expect(source).toContain("setIsOpen(true)")
    expect(source).toContain("const shouldRenderSubItems = isOpen || isActive")
    expect(source).toContain("{shouldRenderSubItems ? (")
    expect(source).toContain("<CollapsibleContent>")
  })

  it("aligns the collapsible child rail to the first and last child buttons", () => {
    expect(source).toContain("relative my-2 pl-6")
    expect(source).not.toContain("relative my-2 pl-8")
    expect(source).toContain("before:top-1")
    expect(source).toContain("before:bottom-1")
    expect(source).not.toContain("before:bottom-3")
    expect(source).not.toContain("before:inset-y-3")
    expect(source).toContain("before:left-4")
    expect(source).toContain("before:bg-sidebar-border/60")
    expect(source).not.toContain("border-pink")
    expect(source).not.toContain("bg-pink")
  })

  it("does not render the edge rail collapse handle", () => {
    expect(source).not.toContain("<SidebarRail />")
  })

  it("does not expose development demo navigation", () => {
    expect(source).not.toContain("showDevTools")
    expect(source).not.toContain("devToolGroups")
    expect(source).not.toContain("component-gallery")
    expect(source).not.toContain("component-demos")
    expect(source).not.toContain("button-demo")
    expect(source).not.toContain("badge-demo")
    expect(source).not.toContain("/tools/nudges/")
    expect(source).not.toContain("/tools/github-buttons/")
    expect(source).not.toContain("/prototypes/")
    expect(source).not.toContain("/scan/workflow/demo/")
  })

  it("keeps the singleton fingerprint tools navigation entry", () => {
    expect(source).not.toContain("/tools/space-mapping/")
    expect(source).toContain("/tools/wordlists/")
    expect(source).toContain("/tools/fingerprints/fingerprinthub/")
    expect(source).not.toMatch(/\/tools\/fingerprints\/(?:arl|ehole|fingers|goby|wappalyzer)\//)
    expect(source).not.toContain('url: "/tools/fingerprints/"')
    expect(source).toContain("/tools/nuclei/")
  })

  it("uses canonical overview navigation for the product brand block", () => {
    expect(source).toContain('href="/overview/"')
    expect(source).not.toContain('href="/"')
  })

  it("uses semantic icon mapping for stable navigation concepts", () => {
    expect(source).toContain("semanticIcons")
    expect(source).toContain("semanticIcons.navigation.overview")
    expect(source).toContain("semanticIcons.concept.organization")
    expect(source).toContain("semanticIcons.concept.target")
    expect(source).toContain("semanticIcons.concept.agent")
    expect(source).toContain("semanticIcons.concept.systemLog")
    expect(source).toContain("semanticIcons.concept.database")
    expect(source).toContain("semanticIcons.concept.workflow")
    expect(source).not.toContain("semanticIcons.concept.spaceMapping")
    expect(source).toContain("semanticIcons.concept.wordlist")
    expect(source).toContain("semanticIcons.concept.fingerprint")
    expect(source).toContain("semanticIcons.concept.nucleiRepository")
    expect(source).toContain("const AboutIcon = semanticIcons.navigation.about")
    expect(source).not.toContain("IconOverview")
    expect(source).not.toContain("IconUsers")
    expect(source).not.toContain("IconListDetails")
    expect(source).not.toContain("IconServer")
  })

  it("uses semantic helper typography in the brand microcopy instead of uppercase tracking patches", () => {
    expect(source).toContain("textRole.helperText")
    expect(source).not.toContain("tracking-[0.2em] uppercase")
    expect(source).not.toContain("tracking-[0.24em] uppercase")
    expect(source).not.toContain("text-[9px]")
  })

  it("keeps the framework automatic prefetch policy for sidebar links", () => {
    expect(source).toContain("const sidebarLinkPrefetch = null")
    expect(source).not.toContain("const sidebarLinkPrefetch = false")
    expect(source).toContain("<Link")
    expect(source).toContain("prefetch={sidebarLinkPrefetch}")
  })

  it("provides collapsed desktop navigation labels through the shared tooltip", () => {
    expect(source).toContain("tooltip={item.title}")
    expect(source).toContain("tooltip={t('supportAuthor')}")
    expect(source).toContain("tooltip={t('about')}")
  })

  it("wires link-local optimistic selection into every navigable sidebar link", () => {
    expect(source).toContain("SidebarNavigationPendingIndicator")
    expect(source.match(/<SidebarNavigationPendingIndicator/g)).toHaveLength(3)
    expect(source).toContain("href={item.url}")
    expect(source).toContain("href={subItem.url}")
    expect(source).toContain("isActive={isActive}")
    expect(source).toContain("isActive={isSubActive}")
    expect(source).not.toContain("ProtectedSidebarNavigationPending")
    expect(source).not.toContain("pendingFallback")
    expect(source).not.toContain("RouteFallback")
  })
})
