import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/github-star-button.tsx"), "utf8")

describe("github-star-button contract", () => {
  it("preserves current source markers", () => {
    expect(source).toContain("export function GithubStarButton")
    expect(source).toContain("className")
    expect(source).toContain("from \"react\"")
  })

  it("uses shared button, typography, and bounded header styling", () => {
    expect(source).toContain("Button")
    expect(source).toContain("textRole.monoLabel")
    expect(source).toContain('size="sm"')
    expect(source).toContain('variant="ghost"')
    expect(source).toContain('className="size-4"')
    expect(source).toContain("hidden tabular-nums text-muted-foreground sm:inline")
    expect(source).not.toContain("textRole.badgeSubtle")
    expect(source).not.toContain('variant="surface"')
    expect(source).not.toContain("tracking-widest")
    expect(source).not.toContain("uppercase")
    expect(source).not.toContain("group-hover:translate-x")
    expect(source).not.toContain("min-w-[120px]")
  })

  it("opens a repository popover before linking to GitHub", () => {
    expect(source).toContain('from "@/components/ui/popover"')
    expect(source).toContain("Popover")
    expect(source).toContain("PopoverTrigger")
    expect(source).toContain("PopoverContent")
    expect(source).toContain('aria-label={t("openPopover")}')
    expect(source).toContain('aria-label={t("openRepository")}')
    expect(source).toContain("GitBranch")
    expect(source).toContain("LunaFoxMark")
    expect(source).toContain("NEXT_PUBLIC_IMAGE_TAG")
    expect(source).toContain("appVersion")
    expect(source).toContain('from "@/lib/ui/overlay-styles"')
    expect(source).toContain("sideOffset={shellOverlaySideOffsets.header}")
    expect(source).not.toContain("IconGitBranch")
    expect(source).not.toContain("v1.0.0")
    expect(source).not.toContain('t("supportHint")')
    expect(source).not.toContain('t("milestoneHint")')
    expect(source).not.toContain('t("footer")')
    expect(source).not.toContain('t("tagline")')
    expect(source).not.toContain('t("description")')
  })

  it("refreshes repository metadata whenever the popover opens", () => {
    expect(source).toContain("handlePopoverOpenChange")
    expect(source).toContain("onOpenChange={handlePopoverOpenChange}")
    expect(source).toContain("if (!open)")
    expect(source).toContain("setIsRefreshing(true)")
    expect(source).toContain("latestRequestRef")
    expect(source).toContain("requestId !== latestRequestRef.current")
    expect(source).toContain("fetchGithubRepoSnapshot()")
    expect(source).toContain("writeGithubRepoCache(snapshot)")
    expect(source).toContain("aria-busy={isRefreshing || undefined}")
  })

  it("links to the GitHub repository from browser-fetched repo data with session caching", () => {
    expect(source).toContain('const GITHUB_REPO = "yyhuni/xingrin"')
    expect(source).toContain('const GITHUB_REPO_URL = `https://github.com/${GITHUB_REPO}`')
    expect(source).toContain("fetchGithubRepoSnapshotFrom(`https://api.github.com/repos/${GITHUB_REPO}`)")
    expect(source).toContain('"use client"')
    expect(source).toContain("useEffect")
    expect(source).toContain("parseGithubRepoSnapshot")
    expect(source).toContain("full_name")
    expect(source).toContain("html_url")
    expect(source).toContain("description")
    expect(source).toContain("stargazers_count")
    expect(source).toContain("forks_count")
    expect(source).toContain("subscribers_count")
    expect(source).toContain("open_issues_count")
    expect(source).toContain("GITHUB_REPO_CACHE_KEY")
    expect(source).toContain("repo?.name")
    expect(source).toContain('GITHUB_REPO.split("/").at(-1)')
    expect(source).toContain('href={repoUrl}')
    expect(source).toContain('target="_blank"')
    expect(source).toContain('rel="noopener noreferrer"')
    expect(source).toContain('readSessionValue(GITHUB_REPO_CACHE_KEY)')
    expect(source).toContain('writeSessionValue(GITHUB_REPO_CACHE_KEY')
    expect(source).not.toContain("GITHUB_STARS_CACHE_KEY")
  })

  it("unlocks Login Visual when the repository link is activated without changing GitHub navigation", () => {
    expect(source).toContain('from "@/lib/login-visual-unlock"')
    expect(source).toContain('from "@/hooks/use-login-visual"')
    expect(source).toContain("unlockLoginVisual()")
    expect(source).toContain("useUnlockLoginVisualDiscoverability()")
    expect(source).toContain("unlockDiscoverability.mutateAsync()")
    expect(source).toContain("setUnlockDialogOpen(true)")
    expect(source).toContain('<Dialog open={unlockDialogOpen}')
    expect(source).toContain('t("unlock.title")')
    expect(source).toContain('onClick={handleRepositoryOpen}')
    expect(source).toContain('target="_blank"')
  })

  it("falls back to the same-origin repository API and caches any successful source", () => {
    expect(source).toContain('const GITHUB_REPO_FALLBACK_API = "/api/github/repo"')
    expect(source).toContain("fetchGithubRepoSnapshot")
    expect(source).toContain("fetchGithubRepoSnapshotFrom(GITHUB_REPO_FALLBACK_API)")
    expect(source).toContain("cachedFallback")
    expect(source).toContain("writeGithubRepoCache")
  })

  it("fetches repository metadata in development", () => {
    expect(source).not.toContain('if (process.env.NODE_ENV === "development") return')
  })

  it("uses close-range sprint milestones to keep the next star goal actionable", () => {
    expect(source).toContain("GITHUB_STAR_SPRINT_SIZE")
    expect(source).toContain("const GITHUB_STAR_SPRINT_SIZE = 50")
    expect(source).toContain("resolveGithubStarMilestone")
    expect(source).toContain("Math.ceil((stars + 1) / GITHUB_STAR_SPRINT_SIZE) * GITHUB_STAR_SPRINT_SIZE")
    expect(source).toContain("starsRemaining")
    expect(source).toContain("starProgress")
    expect(source).toContain('t("remaining"')
    expect(source).toContain('t("sprintCta"')
    expect(source).not.toContain('t("goal"')
    expect(source).not.toContain("Math.ceil((stars + 1) / 500) * 500")
    expect(source).toContain("justify-between")
    expect(source).toContain("flex-1 overflow-hidden radius-pill bg-muted")
    expect(source).toContain("transition-[width]")
  })
})
