// Code generated by engine-manifest-artifact-gen. DO NOT EDIT.
// Source: strict engine.v5 engine.json.

package main

import (
	"context"
	"errors"
	"os"
	"sync"

	engineexecutionpb "github.com/yyhuni/lunafox/engine-go/protocol"
	"github.com/yyhuni/lunafox/engine-go/sdk"
	enginecontract "github.com/yyhuni/lunafox/engines/port_scan/contract"
)

const lunafoxEngineRunFailureMessage = "engine execution failed\n"

func Run(handler enginecontract.Handler) {
	if err := lunafoxRun(handler); err != nil {
		_, _ = os.Stderr.WriteString(lunafoxEngineRunFailureMessage)
		os.Exit(1)
	}
}

func lunafoxRun(handler enginecontract.Handler) (runErr error) {
	if handler == nil {
		return errors.New("engine handler is required")
	}
	return sdk.Run(func(handlerContext context.Context, snapshot *engineexecutionpb.EngineExecutionContext, reporter sdk.Reporter, inputSet interface {
		SubdomainsPath(context.Context) (string, error)
		HostPortsPath(context.Context) (string, error)
		WebsiteURLsPath(context.Context) (string, error)
		EndpointURLsPath(context.Context) (string, error)
	}) error {
		if reporter == nil {
			return errors.New("engine reporter is required")
		}
		diagnostics, err := reporter.GeneratedDiagnostics()
		if err != nil {
			return err
		}
		progress := engineProgressPort{reporter: reporter, diagnostics: diagnostics}
		results, err := newEngineResults(reporter, diagnostics)
		if err != nil {
			return diagnostics.WrapFailure(sdk.GeneratedFailureExecutionProjection, err)
		}
		execution, err := lunafoxProjectExecution(snapshot, inputSet, progress, results)
		if err != nil {
			return diagnostics.WrapFailure(sdk.GeneratedFailureExecutionProjection, err)
		}
		return diagnostics.WrapFailure(sdk.GeneratedFailureHandler, handler(handlerContext, execution))
	})
}

type engineProgressPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
}

func (port engineProgressPort) Report(ctx context.Context, message string) error {
	if port.reporter == nil || port.diagnostics == nil {
		return errors.New("engine progress port is required")
	}
	return port.diagnostics.WrapFailure(sdk.GeneratedFailureProgressReport, port.reporter.ReportProgress(ctx, message))
}

type engineSubdomainResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineSubdomainResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.subdomain.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.subdomain.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineSubdomainResultPort) Submit(ctx context.Context, items <-chan enginecontract.Subdomain) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Subdomain
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.subdomain.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeSubdomain(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.subdomain.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineEndpointResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineEndpointResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.endpoint.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.endpoint.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineEndpointResultPort) Submit(ctx context.Context, items <-chan enginecontract.Endpoint) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Endpoint
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.endpoint.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeEndpoint(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.endpoint.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineHostPortResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineHostPortResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.host_port.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.host_port.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineHostPortResultPort) Submit(ctx context.Context, items <-chan enginecontract.HostPort) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.HostPort
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.host_port.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeHostPort(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.host_port.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineWebsiteResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineWebsiteResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.website.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.website.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineWebsiteResultPort) Submit(ctx context.Context, items <-chan enginecontract.Website) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Website
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.website.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeWebsite(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.website.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineWebsiteTechnologyResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineWebsiteTechnologyResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.website_technology.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.website_technology.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineWebsiteTechnologyResultPort) Submit(ctx context.Context, items <-chan enginecontract.WebsiteTechnology) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.WebsiteTechnology
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.website_technology.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeWebsiteTechnology(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.website_technology.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineScreenshotResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineScreenshotResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.screenshot.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.screenshot.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineScreenshotResultPort) Submit(ctx context.Context, items <-chan enginecontract.Screenshot) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Screenshot
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.screenshot.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeScreenshot(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.screenshot.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineDirectoryResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineDirectoryResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.directory.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.directory.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineDirectoryResultPort) Submit(ctx context.Context, items <-chan enginecontract.Directory) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Directory
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.directory.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeDirectory(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.directory.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

type engineVulnerabilityResultPort struct {
	reporter    sdk.Reporter
	diagnostics sdk.GeneratedDiagnostics
	once        sync.Once
	sink        sdk.ResultSink
	sinkErr     error
}

func (port *engineVulnerabilityResultPort) ensureSink() error {
	if port == nil {
		return errors.New("engine result port is required")
	}
	port.once.Do(func() {
		if port.reporter == nil || port.diagnostics == nil {
			port.sinkErr = errors.New("engine result dependencies are required")
			return
		}
		if err := port.diagnostics.RegisterResultType("asset.vulnerability.v1"); err != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
			return
		}
		port.sink, port.sinkErr = port.reporter.ResultSink("asset.vulnerability.v1")
		if port.sinkErr != nil {
			port.sinkErr = port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, port.sinkErr)
		}
	})
	return port.sinkErr
}

func (port *engineVulnerabilityResultPort) Submit(ctx context.Context, items <-chan enginecontract.Vulnerability) error {
	if ctx == nil {
		return errors.New("engine result context is required")
	}
	if items == nil {
		return errors.New("engine result items channel is required")
	}
	if err := port.ensureSink(); err != nil {
		return err
	}
	encodeContext, cancelEncode := context.WithCancel(ctx)
	defer cancelEncode()
	encoded := make(chan []byte)
	encodeErr := make(chan error, 1)
	go func() {
		defer close(encoded)
		for {
			var item enginecontract.Vulnerability
			var open bool
			select {
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			case item, open = <-items:
			}
			if !open {
				encodeErr <- nil
				return
			}
			if err := port.diagnostics.ObserveResultReceived("asset.vulnerability.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			payload, err := enginecontract.EncodeVulnerability(item)
			if err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			if err := port.diagnostics.ObserveResultEncoded("asset.vulnerability.v1"); err != nil {
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
				return
			}
			select {
			case encoded <- []byte(payload):
			case <-encodeContext.Done():
				encodeErr <- port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, encodeContext.Err())
				return
			}
		}
	}()
	submitErr := port.sink.Submit(encodeContext, encoded)
	if submitErr != nil {
		cancelEncode()
		<-encodeErr
		return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, submitErr)
	}
	return <-encodeErr
}

func newEngineResults(reporter sdk.Reporter, diagnostics sdk.GeneratedDiagnostics) (enginecontract.Results, error) {
	if reporter == nil || diagnostics == nil {
		return enginecontract.Results{}, errors.New("engine result dependencies are required")
	}
	var results enginecontract.Results
	results.Subdomains = &engineSubdomainResultPort{reporter: reporter, diagnostics: diagnostics}
	results.Endpoints = &engineEndpointResultPort{reporter: reporter, diagnostics: diagnostics}
	results.HostPorts = &engineHostPortResultPort{reporter: reporter, diagnostics: diagnostics}
	results.Websites = &engineWebsiteResultPort{reporter: reporter, diagnostics: diagnostics}
	results.WebsiteTechnologies = &engineWebsiteTechnologyResultPort{reporter: reporter, diagnostics: diagnostics}
	results.Screenshots = &engineScreenshotResultPort{reporter: reporter, diagnostics: diagnostics}
	results.Directories = &engineDirectoryResultPort{reporter: reporter, diagnostics: diagnostics}
	results.Vulnerabilities = &engineVulnerabilityResultPort{reporter: reporter, diagnostics: diagnostics}
	return results, nil
}

type lunafoxExecutionInputSet interface {
	SubdomainsPath(context.Context) (string, error)
	HostPortsPath(context.Context) (string, error)
	WebsiteURLsPath(context.Context) (string, error)
	EndpointURLsPath(context.Context) (string, error)
}

func lunafoxProjectExecution(snapshot *engineexecutionpb.EngineExecutionContext, inputSet lunafoxExecutionInputSet, progress enginecontract.Progress, results enginecontract.Results) (*enginecontract.Execution, error) {
	if snapshot == nil {
		return nil, errors.New("Engine API v2 Context is required")
	}
	if progress == nil {
		return nil, errors.New("engine progress port is required")
	}
	target, err := lunafoxProjectTarget(snapshot.GetTarget())
	if err != nil {
		return nil, err
	}
	input, err := lunafoxProjectInput(inputSet)
	if err != nil {
		return nil, err
	}
	config, err := lunafoxProjectConfig(snapshot.GetConfig())
	if err != nil {
		return nil, err
	}
	if err := lunafoxProjectConfigResources(snapshot.GetConfigResources(), &config); err != nil {
		return nil, err
	}
	platformResources, err := lunafoxProjectPlatformResources(snapshot.GetPlatformResources())
	if err != nil {
		return nil, err
	}
	return &enginecontract.Execution{
		Target:            target,
		Input:             input,
		Config:            config,
		PlatformResources: platformResources,
		Workspace:         engineexecutionpb.WorkspacePath,
		Progress:          progress,
		Results:           results,
	}, nil
}

func lunafoxProjectTarget(target *engineexecutionpb.CanonicalTarget) (enginecontract.Target, error) {
	if target == nil || target.GetType() == "" || target.GetValue() == "" {
		return enginecontract.Target{}, errors.New("complete canonical Target is required")
	}
	switch target.GetType() {
	case "domain":
	case "ip":
	case "cidr":
	default:
		return enginecontract.Target{}, errors.New("Target type is not supported by this Engine")
	}
	return enginecontract.Target{Type: enginecontract.TargetType(target.GetType()), Value: target.GetValue()}, nil
}

func lunafoxProjectInput(inputSet lunafoxExecutionInputSet) (enginecontract.Input, error) {
	if inputSet == nil {
		return enginecontract.Input{}, errors.New("engine input handles are required")
	}
	return enginecontract.Input{
		Subdomains:   engineSubdomainsInput{path: inputSet.SubdomainsPath},
		HostPorts:    engineHostPortsInput{path: inputSet.HostPortsPath},
		WebsiteURLs:  engineWebsiteURLsInput{path: inputSet.WebsiteURLsPath},
		EndpointURLs: engineEndpointURLsInput{path: inputSet.EndpointURLsPath},
	}, nil
}

type engineSubdomainsInput struct {
	path func(context.Context) (string, error)
}

func (input engineSubdomainsInput) Path(ctx context.Context) (string, error) {
	if input.path == nil {
		return "", errors.New("engine input handle is required")
	}
	return input.path(ctx)
}

type engineHostPortsInput struct {
	path func(context.Context) (string, error)
}

func (input engineHostPortsInput) Path(ctx context.Context) (string, error) {
	if input.path == nil {
		return "", errors.New("engine input handle is required")
	}
	return input.path(ctx)
}

type engineWebsiteURLsInput struct {
	path func(context.Context) (string, error)
}

func (input engineWebsiteURLsInput) Path(ctx context.Context) (string, error) {
	if input.path == nil {
		return "", errors.New("engine input handle is required")
	}
	return input.path(ctx)
}

type engineEndpointURLsInput struct {
	path func(context.Context) (string, error)
}

func (input engineEndpointURLsInput) Path(ctx context.Context) (string, error) {
	if input.path == nil {
		return "", errors.New("engine input handle is required")
	}
	return input.path(ctx)
}

func lunafoxProjectConfig(config *engineexecutionpb.EngineExecutionConfig) (enginecontract.Config, error) {
	if config == nil || len(config.GetSections()) != 2 {
		return enginecontract.Config{}, errors.New("Engine config sections do not match the Engine Definition")
	}
	var projected enginecontract.Config
	var seenNaabuActive bool
	var seenNaabuPassive bool
	for _, section := range config.GetSections() {
		if section == nil {
			return enginecontract.Config{}, errors.New("Engine config section is required")
		}
		switch section.GetSectionId() {
		case "naabu_active":
			if seenNaabuActive {
				return enginecontract.Config{}, errors.New("duplicate Engine config section")
			}
			seenNaabuActive = true
			value, err := lunafoxProjectNaabuActiveConfig(section)
			if err != nil {
				return enginecontract.Config{}, err
			}
			projected.NaabuActive = value
		case "naabu_passive":
			if seenNaabuPassive {
				return enginecontract.Config{}, errors.New("duplicate Engine config section")
			}
			seenNaabuPassive = true
			value, err := lunafoxProjectNaabuPassiveConfig(section)
			if err != nil {
				return enginecontract.Config{}, err
			}
			projected.NaabuPassive = value
		default:
			return enginecontract.Config{}, errors.New("Engine config contains an undeclared section")
		}
	}
	if !seenNaabuActive {
		return enginecontract.Config{}, errors.New("Engine config is missing a declared section")
	}
	if !seenNaabuPassive {
		return enginecontract.Config{}, errors.New("Engine config is missing a declared section")
	}
	return projected, nil
}

func lunafoxProjectNaabuActiveConfig(section *engineexecutionpb.ConfigSection) (enginecontract.NaabuActiveConfig, error) {
	if section.Enabled == nil {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config enabled presence is required")
	}
	projected := enginecontract.NaabuActiveConfig{Enabled: section.GetEnabled()}
	if !section.GetEnabled() {
		if len(section.GetParams()) != 0 {
			return enginecontract.NaabuActiveConfig{}, errors.New("disabled Engine config section must not contain scalar parameters")
		}
		return projected, nil
	}
	var seenTimeout bool
	var seenThreads bool
	var seenPortMode bool
	var seenPorts bool
	var seenTopPorts bool
	var seenRate bool
	for _, param := range section.GetParams() {
		if param == nil || param.GetValue() == nil {
			return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar value is required")
		}
		switch param.GetParamKey() {
		case "timeout":
			if seenTimeout {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenTimeout = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_IntegerValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.Timeout = typed.IntegerValue
		case "threads":
			if seenThreads {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenThreads = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_IntegerValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.Threads = typed.IntegerValue
		case "port-mode":
			if seenPortMode {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenPortMode = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_StringValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.PortMode = typed.StringValue
		case "ports":
			if seenPorts {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenPorts = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_StringValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.Ports = typed.StringValue
		case "top-ports":
			if seenTopPorts {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenTopPorts = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_StringValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.TopPorts = typed.StringValue
		case "rate":
			if seenRate {
				return enginecontract.NaabuActiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenRate = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_IntegerValue)
			if !ok {
				return enginecontract.NaabuActiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.Rate = typed.IntegerValue
		default:
			return enginecontract.NaabuActiveConfig{}, errors.New("Engine config contains an undeclared or resource-valued scalar parameter")
		}
	}
	if !seenTimeout {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	if !seenThreads {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	if !seenPortMode {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	if !seenPorts {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	if !seenTopPorts {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	if !seenRate {
		return enginecontract.NaabuActiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	return projected, nil
}

func lunafoxProjectNaabuPassiveConfig(section *engineexecutionpb.ConfigSection) (enginecontract.NaabuPassiveConfig, error) {
	if section.Enabled == nil {
		return enginecontract.NaabuPassiveConfig{}, errors.New("Engine config enabled presence is required")
	}
	projected := enginecontract.NaabuPassiveConfig{Enabled: section.GetEnabled()}
	if !section.GetEnabled() {
		if len(section.GetParams()) != 0 {
			return enginecontract.NaabuPassiveConfig{}, errors.New("disabled Engine config section must not contain scalar parameters")
		}
		return projected, nil
	}
	var seenTimeout bool
	for _, param := range section.GetParams() {
		if param == nil || param.GetValue() == nil {
			return enginecontract.NaabuPassiveConfig{}, errors.New("Engine config scalar value is required")
		}
		switch param.GetParamKey() {
		case "timeout":
			if seenTimeout {
				return enginecontract.NaabuPassiveConfig{}, errors.New("duplicate Engine config scalar parameter")
			}
			seenTimeout = true
			typed, ok := param.GetValue().(*engineexecutionpb.ConfigValue_IntegerValue)
			if !ok {
				return enginecontract.NaabuPassiveConfig{}, errors.New("Engine config scalar type does not match the Engine Definition")
			}
			projected.Timeout = typed.IntegerValue
		default:
			return enginecontract.NaabuPassiveConfig{}, errors.New("Engine config contains an undeclared or resource-valued scalar parameter")
		}
	}
	if !seenTimeout {
		return enginecontract.NaabuPassiveConfig{}, errors.New("Engine config is missing a required scalar parameter")
	}
	return projected, nil
}

func lunafoxProjectConfigResources(resources []*engineexecutionpb.ConfigResource, config *enginecontract.Config) error {
	if config == nil {
		return errors.New("Engine config resources do not match the Engine Definition")
	}
	for _, resource := range resources {
		if resource == nil || resource.GetPath() == "" || resource.GetContentType() == "" {
			return errors.New("complete Engine config resource binding is required")
		}
		switch {
		default:
			return errors.New("Engine config contains an undeclared resource binding")
		}
	}
	return nil
}

func lunafoxProjectPlatformResources(resources []*engineexecutionpb.PlatformResource) (enginecontract.PlatformResources, error) {
	if len(resources) != 0 {
		return enginecontract.PlatformResources{}, errors.New("Engine platform resources do not match the Engine Definition")
	}
	var projected enginecontract.PlatformResources
	for _, resource := range resources {
		if resource == nil || resource.GetPath() == "" || resource.GetContentType() == "" {
			return enginecontract.PlatformResources{}, errors.New("complete Engine platform resource binding is required")
		}
		switch resource.GetResourceId() {
		default:
			return enginecontract.PlatformResources{}, errors.New("Engine platform resource is not declared by this Engine")
		}
	}
	return projected, nil
}
