import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "app/targets/[id]/layout.tsx"), "utf8")
const shellLayoutSource = readFileSync(path.resolve(process.cwd(), "app/targets/[id]/target-detail-shell-layout.tsx"), "utf8")

describe("layout contract", () => {
  it("preserves current source markers", () => {
    expect(source).toContain("export default function TargetLayout")
    expect(source).toContain("className")
    expect(source).toContain("from \"react\"")
  })

  it("uses shared content tabs for secondary asset navigation", () => {
    expect(source).toContain('<TabsList variant="content">')
    expect(source).toContain('variant="content" render=')
    expect(source).not.toContain('variant="content" asChild')
    expect(source).not.toContain('variant="minimal-tab"')
  })

  it("stops dynamic breadcrumbs at the active primary target workspace", () => {
    expect(source).toContain("const breadcrumbPrimaryLabels = {")
    expect(source).toContain("const breadcrumbItems = [")
    expect(source).toContain('href: "/targets/"')
    expect(source).toContain("href: primaryPaths.overview")
    expect(source).toContain("{ label: breadcrumbPrimaryLabels[primaryTab] },")
    expect(source).toContain('<TargetDetailShellHeader aria-label={t("breadcrumb.targetDetail")}>')
    expect(shellLayoutSource).toContain('<nav')
    expect(source).toContain('<Link href={item.href}')
    expect(source).toContain('aria-current="page"')
    expect(source).not.toContain("breadcrumbSecondaryLabels")
    expect(source).not.toContain("relationBreadcrumb")
    expect(source).not.toContain("TargetDetailBreadcrumbContext")
    expect(source).not.toContain('<span className="text-muted-foreground">{t("breadcrumb.targetDetail")}</span>')
  })

  it("keeps website detail sections under the Assets target workspace", () => {
    expect(source).toContain('const isWebsiteDetailRoute = /^\\/targets\\/[^/]+\\/websites\\/[^/]+/.test(pathname);')
    expect(source).toContain('if (isWebsiteDetailRoute)\n            return "assets";')
    expect(source).toContain('const showSecondaryNav = primaryTab === "settings" || (primaryTab === "assets" && !isWebsiteDetailRoute);')
  })

  it("adds routed blacklist and scheduled scan settings workspaces", () => {
    expect(source).toContain('const TARGET_SETTINGS_SECONDARY_TAB_ORDER = ["blacklist", "scheduled-scans"] as const;')
    expect(source).toContain('settings: `${basePath}/settings/`')
    expect(source).toContain('"scheduled-scans": `${basePath}/settings/scheduled-scans/`')
    expect(source).toContain('value="blacklist"')
    expect(source).toContain('value="scheduled-scans"')
    expect(source).toContain('activeSecondaryTabIndex={activeSecondaryTabIndex}')
  })

  it("uses the shared tab count badge instead of page-local badge geometry", () => {
    expect(source).toContain("TabsCountBadge")
    expect(source).toContain('from "@/components/ui/tabs"')
    expect(source).not.toContain('from "@/components/ui/badge"')
    expect(source).not.toContain("rounded-full px-1.5 text-xs")
  })

  it("keeps canonical icons only in directory and screenshot primary tabs", () => {
    expect(source).toContain("const DirectoryIcon = semanticIcons.concept.directory;")
    expect(source).toContain("const ScreenshotIcon = semanticIcons.concept.screenshot;")
    expect(source).toContain("<DirectoryIcon className=\"h-4 w-4\"/>")
    expect(source).toContain("<ScreenshotIcon className=\"h-4 w-4\"/>")
    expect(source).not.toContain("<WebsiteIcon")
    expect(source).not.toContain("<SubdomainIcon")
    expect(source).not.toContain("<IpIcon")
    expect(source).not.toContain("<EndpointIcon")
    expect(source).not.toContain("FolderSearch")
    expect(source).not.toContain("Image as ImageIcon")
  })

  it("keeps one complete shell owner mounted across target metadata and child readiness", () => {
    expect(source).toContain("const renderShellLoadingState = ()")
    expect(source).toContain("skeleton={renderShellLoadingState()}")
    expect(source).toContain("if (isLoading) {")
    expect(source).toContain("return null;")
    expect(source).not.toContain("DetailMetadataBootHandoffBlocker")
    expect(source).not.toContain('data-boot-handoff-pending="true"')
    expect(source.indexOf('return (<HiddenReadinessRouteBoundary key={`target-detail-shell-${id}`}')).toBeLessThan(source.indexOf("if (isLoading) {"))
    expect(source).not.toContain('return renderShellLoadingState("target-detail-shell")')
    expect(source).not.toContain('if (isLoading && primaryTab === "overview")')
    expect(source).not.toContain("DetailTabRailSkeleton")
    expect(source).not.toContain("DetailMetadataTextPlaceholder")
    expect(source).not.toContain("isChromeLoading")
  })

  it("uses one feature-local shell structure for loading and resolved target chrome", () => {
    expect(source).toContain('from "./target-detail-shell-layout"')
    expect(source).toContain("TargetDetailShellLoadingState")
    expect(source).toContain("TargetDetailShellLayout")
    expect(source).toContain("TargetDetailShellHeader")
    expect(source).toContain("TargetDetailShellPrimaryTabs")
    expect(source).toContain("TargetDetailShellSecondaryTabs")
    expect(source).toContain("TargetDetailShellContent")
    expect(source).not.toContain("DetailPageShellSkeleton")
    expect(shellLayoutSource).toContain("export function TargetDetailShellLayout")
    expect(shellLayoutSource).toContain("export function TargetDetailShellLoadingState")
    expect(shellLayoutSource).toContain("getLoadingStructureSlotAttributes")
    expect(shellLayoutSource).toContain('"target-detail-shell-header"')
    expect(shellLayoutSource).toContain('"target-detail-shell-primary-tabs"')
    expect(shellLayoutSource).toContain('"target-detail-shell-content"')
    expect(shellLayoutSource).toContain("TabsList")
    expect(shellLayoutSource).toContain("TabsTrigger")
    expect(source).toContain("HiddenReadinessRouteBoundary")
    expect(source).toContain("DetailShellReadyProvider")
    expect(source).not.toContain('initiallyDeferSkeleton={primaryTab === "overview"}')
    expect(source).toContain('owner="target-detail-shell"')
    expect(source).toContain('owner="target-detail-shell" layer="workspace" intent="data"')
    expect(source).toContain('transitionMode="replace"')
    expect(source).toContain("onReady, deferInitialSkeleton")
    expect(source).toContain("secondaryTabLabels={secondaryTabLabels}")
    expect(source).toContain('secondaryTab === "endpoints"')
    expect(source).toContain('from "@/components/endpoints/endpoints-detail-view-sections"')
    expect(source).toContain("<EndpointsDetailViewRouteFallback rowCount={ENDPOINTS_DETAIL_FALLBACK_ROW_COUNT} />")
    expect(source).toContain('from "@/components/websites/website-relation-evidence-view"')
    expect(source).toContain('from "@/components/subdomains/subdomains-detail-view-sections"')
    expect(source).toContain('from "@/components/ip-addresses/ip-addresses-view-sections"')
    expect(source).toContain('from "@/components/directories/directories-view-sections"')
    expect(source).toContain('from "@/components/screenshots/screenshots-gallery-sections"')
    expect(source).toContain('from "@/components/target/target-settings-sections"')
    expect(source).toContain('from "@/components/vulnerabilities/vulnerabilities-detail-view-sections"')
    expect(source).toContain("<WebsiteRelationEvidenceLoadingState />")
    expect(source).toContain("isWebsiteDetailRoute ? <WebsiteRelationDetailLoadingState /> : <WebsiteRelationEvidenceLoadingState />")
    expect(source).toContain("<SubdomainsDetailViewRouteFallback rowCount={DETAIL_FALLBACK_TABLE_ROW_COUNT} />")
    expect(source).toContain("<IPAddressesViewRouteFallback rowCount={ipAddressesFallbackRowCount} />")
    expect(source).toContain("const INITIAL_DIRECTORY_FALLBACK_ROW_COUNT = 1")
    expect(source).toContain("<DirectoriesViewRouteFallback rowCount={INITIAL_DIRECTORY_FALLBACK_ROW_COUNT} totalSize={0} showBulkAdd />")
    expect(source).not.toContain("Math.min(counts.websites")
    expect(source).not.toContain("Math.min(counts.directories")
    expect(source).toContain("const INITIAL_SCREENSHOT_FALLBACK_ITEM_COUNT = 3;")
    expect(source).toContain("<ScreenshotsGalleryRouteFallback itemCount={INITIAL_SCREENSHOT_FALLBACK_ITEM_COUNT} showSelectionAction />")
    expect(source).not.toContain("ScreenshotsGallerySkeleton")
    expect(source).toContain("const INITIAL_DETAIL_FALLBACK_ROW_COUNT = 2;")
    expect(source).toContain('section={settingsSection}')
    expect(source).toContain("const settingsSection = secondaryTab === \"scheduled-scans\" ? \"scheduled-scans\" : \"blacklist\";")
    expect(source).toContain("<VulnerabilitiesDetailViewRouteFallback rowCount={INITIAL_DETAIL_FALLBACK_ROW_COUNT} />")
    expect(source).not.toContain('from "@/components/endpoints/endpoints-detail-view-skeleton"')
    expect(source).not.toContain('from "@/components/websites/websites-view-skeleton"')
    expect(source).not.toContain('from "@/components/subdomains/subdomains-detail-view-skeleton"')
    expect(source).not.toContain('from "@/components/ip-addresses/ip-addresses-view-skeleton"')
    expect(source).not.toContain('from "@/components/directories/directories-view-skeleton"')
    expect(source).not.toContain('from "@/components/vulnerabilities/vulnerabilities-detail-view-skeleton"')
    expect(source).not.toContain('from "@/components/target/target-settings-skeleton"')
    expect(source).not.toContain("WebSitesViewSkeleton")
    expect(source).not.toContain("SubdomainsDetailViewSkeleton")
    expect(source).not.toContain("IPAddressesViewSkeleton")
    expect(source).not.toContain("DirectoriesViewSkeleton")
    expect(source).not.toContain("EndpointsDetailViewSkeleton")
    expect(source).not.toContain("VulnerabilitiesDetailViewSkeleton")
    expect(source).not.toContain("TargetSettingsSkeleton")
    expect(source).not.toContain("columns={isEndpointRoute ? 8")
    expect(source).not.toContain('owner="target-detail-child-view"')
    expect(source).not.toContain("mobileRows={isEndpointRoute ? 6 : undefined}")
    expect(source).not.toContain('if (primaryTab === "overview") {\n        return (<HiddenReadinessRouteBoundary')
    expect(source).not.toContain("return resolvedLayout;")
    expect(source).not.toContain('return renderShellLoadingState("target-detail-shell")')
  })

  it("keeps the shared shell surface viewport-bounded while child routes own their scroll height", () => {
    expect(source).toContain("TARGET_DETAIL_SHELL_HANDOFF_CLASS")
    expect(source).toContain("className={TARGET_DETAIL_SHELL_HANDOFF_CLASS}")
    expect(source).toContain("skeletonClassName={TARGET_DETAIL_SHELL_HANDOFF_CLASS}")
    expect(source).toContain("contentClassName={TARGET_DETAIL_SHELL_HANDOFF_CLASS}")
    expect(shellLayoutSource).toContain('export const TARGET_DETAIL_SHELL_HANDOFF_CLASS = "flex h-full min-h-0 flex-1 flex-col"')
    expect(shellLayoutSource).toContain('"flex h-full min-h-0 flex-1 flex-col gap-4 py-4 md:gap-6 md:py-6"')
    expect(shellLayoutSource).toContain('className={cn("flex min-h-0 flex-1 flex-col", className)}')
    expect(shellLayoutSource).toContain('<Skeleton className="h-5 w-16 shrink-0 rounded-full" />')
  })

  it("derives the IP route fallback rows from the target summary", () => {
    expect(source).toContain("const DETAIL_FALLBACK_MAX_ROWS = 10;")
    expect(source).toContain("const DETAIL_FALLBACK_MIN_ROWS = 1;")
    expect(source).toContain("function getDetailFallbackRowCount(total: number | undefined)")
    expect(source).toContain("const ipAddressesFallbackRowCount = getDetailFallbackRowCount(targetSummary?.ips);")
    expect(source).toContain("<IPAddressesViewRouteFallback rowCount={ipAddressesFallbackRowCount} />")
    expect(source).not.toContain("<IPAddressesViewRouteFallback rowCount={DETAIL_FALLBACK_TABLE_ROW_COUNT} />")
  })

  it("uses stable child fallback geometry and activates the current shell tab", () => {
    expect(source).toContain('const TARGET_PRIMARY_TAB_ORDER = ["overview", "assets", "directories", "screenshots", "vulnerabilities", "settings"] as const;')
    expect(source).toContain("const activePrimaryTabIndex = TARGET_PRIMARY_TAB_ORDER.indexOf(primaryTab);")
    expect(source).toContain("const primaryTabLabels = TARGET_PRIMARY_TAB_ORDER.map((tab) => breadcrumbPrimaryLabels[tab]);")
    expect(source).toContain("primaryTabLabels={primaryTabLabels}")
    expect(source).toContain("activePrimaryTabIndex={activePrimaryTabIndex}")
    expect(source).toContain('<div className="px-4 lg:px-6"><ScreenshotsGalleryRouteFallback itemCount={INITIAL_SCREENSHOT_FALLBACK_ITEM_COUNT} showSelectionAction /></div>')
    expect(source).toContain('<div className="px-4 lg:px-6"><VulnerabilitiesDetailViewRouteFallback rowCount={INITIAL_DETAIL_FALLBACK_ROW_COUNT} /></div>')
    expect(source).toContain('<div className="flex min-h-0 flex-1 flex-col px-4 lg:px-6"><TargetSettingsRouteFallback rowCount={INITIAL_DETAIL_FALLBACK_ROW_COUNT} section={settingsSection} /></div>')
    expect(source).not.toContain("screenshotsFallbackItemCount")
    expect(source).not.toContain("vulnerabilitiesFallbackRowCount")
  })

  it("renders target-detail failures through the shared app error owner instead of raw transport messages", () => {
    expect(source).toContain('from "@/components/shared/feedback/app-error-state"')
    expect(source).toContain("<AppErrorState")
    expect(source).toContain('createAppError("resource-not-found"')
    expect(source).toContain('normalizedError?.kind === "resource-not-found"')
    expect(source).toContain('t("notFound.title")')
    expect(source).toContain('t("notFound.message", { id })')
    expect(source).not.toContain("{error.message")
    expect(source).not.toContain("error.message ||")
  })
})
