export type { IconProps as TablerIconProps, TablerIcon } from "@tabler/icons-react"
export {
  semanticIcons,
  type SemanticConceptIcon,
  type SemanticIconCategory,
} from "./semantic-icons"

export type Icon = import("@tabler/icons-react").TablerIcon
export type LucideIcon = import("@tabler/icons-react").TablerIcon

// Core UI Icons - exported under existing names to keep consumers stable.
export {
  IconActivity as Activity,
  IconAlarm as AlarmClock,
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArrowDownRight as ArrowDownRight,
  IconArrowLeft as ArrowLeft,
  IconArrowRight as ArrowRight,
  IconArrowUpRight as ArrowUpRight,
  IconBan as Ban,
  IconBell as Bell,
  IconBellOff as BellOff,
  IconBox as Box,
  IconBuilding as Building2,
  IconCalendar as Calendar,
  IconCamera as Camera,
  IconChartBar as BarChart3,
  IconCheck as Check,
  IconCircleCheck as CheckCircle,
  IconCircleCheck as CheckCircle2,
  IconCheck as CheckIcon,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronLeft as ChevronLeft,
  IconChevronLeft as ChevronLeftIcon,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUp,
  IconChevronUp as ChevronUpIcon,
  IconSelector as ChevronsUpDown,
  IconCircle as Circle,
  IconCircleFilled as CircleIcon,
  IconCircleCheck as CircleCheckIcon,
  IconClock as Clock,
  IconCopy as Copy,
  IconCpu as Cpu,
  IconCrosshair as Crosshair,
  IconDatabase as Database,
  IconAlignLeft as AlignLeft,
  IconHexagon as Hexagon,
  IconDownload as Download,
  IconEdit as Edit,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconFileCode as FileCode,
  IconFileText as FileText,
  IconFilter as Filter,
  IconFocusCentered as FocusCentered,
  IconFingerprint as Fingerprint,
  IconFolder as Folder,
  IconFolderOpen as FolderOpen,
  IconFolderSearch as FolderSearch,
  IconGitBranch as GitBranch,
  IconGlobe as Globe,
  IconDisc as HardDrive,
  IconHash as Hash,
  IconHeart as Heart,
  IconHelpCircle as HelpCircle,
  IconHistory as History,
  IconPhoto as Image,
  IconInfoCircle as Info,
  IconLayoutDashboard as LayoutOverview,
  IconGridDots as LayoutGrid,
  IconLink as Link,
  IconLink as Link2,
  IconNetwork as Network,
  IconScan as Scan,
  IconLoader2 as Loader2,
  IconLoader2 as Loader2Icon,
  IconLock as Lock,
  IconDots as MoreHorizontal,
  IconPackage as Package,
  IconPackage as PackageOpen,
  IconLayoutSidebarLeftCollapse as PanelLeftCloseIcon,
  IconLayoutSidebarLeftExpand as PanelLeftIcon,
  IconPencil as Pencil,
  IconPlayerPlay as Play,
  IconPlus as Plus,
  IconRefresh as RefreshCw,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconServer as Server,
  IconSettings as Settings,
  IconShieldCheck as ShieldCheck,
  IconShieldExclamation as ShieldAlert,
  IconShield as Shield,
  IconCellSignal5 as Signal,
  IconRadar as Radar,
  IconTarget as Target,
  IconTerminal as Terminal,
  IconTrash as Trash2,
  IconUpload as Upload,
  IconUpload as UploadIcon,
  IconUser as User,
  IconWavesElectricity as Waves,
  IconTool as Wrench,
  IconX as X,
  IconCircleX as XCircle,
  IconX as XIcon,
  IconBolt as Zap,
  IconInfoCircle as InfoIcon,
  IconLayersSelected as Layers,
  IconDeviceScreen as Monitor,
  IconAlertOctagon as OctagonXIcon,
  IconPlayerPause as PauseCircle,
  IconRadio as Radio,
  IconAdjustmentsHorizontal as Sliders,
  IconTag as Tag,
  IconAlertTriangle as TriangleAlertIcon,
} from "@tabler/icons-react"

// Icon-prefixed variants used throughout app and prototype components.
export {
  IconActivity,
  IconArrowUp,
  IconAlertTriangle,
  IconAutomation,
  IconBrandDiscord,
  IconBrandGithub,
  IconBrandSlack,
  IconBug,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircleX,
  IconCloud,
  IconCode,
  IconCpu,
  IconLayoutDashboard as IconOverview,
  IconDatabase,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFileExport,
  IconFileText,
  IconFolder,
  IconInfoCircle,
  IconLanguage,
  IconColumns as IconLayoutColumns,
  IconListDetails,
  IconLoader2,
  IconMail,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconRadar,
  IconRadar2,
  IconRefresh,
  IconRocket,
  IconScan,
  IconSearch,
  IconServer,
  IconSettings,
  IconShield,
  IconShieldCheck,
  IconShieldPlus,
  IconStack2,
  IconStar,
  IconStarFilled,
  IconTarget,
  IconTerminal,
  IconTool,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconUsers,
  IconWorld,
  IconWorldSearch,
  IconX,
  IconBan,
  IconBook,
  IconBuilding,
  IconCalendar,
  IconCalendarEvent,
  IconCircleCheck,
  IconCircleFilled as IconCircleDot,
  IconCircleHalf2,
  IconClock,
  IconCloudOff,
  IconCoffee,
  IconDownload,
  IconFilter,
  IconHeart,
  IconActivityHeartbeat as IconHeartbeat,
  IconKey,
  IconGridDots as IconLayoutGrid,
  IconList,
  IconLock,
  IconLogout,
  IconMessageReport,
  IconMoon,
  IconSun,
  IconTerminal2,
  IconTrophy,
  IconUpload,
  IconUser,
  IconGlobe,
  IconMenu,
  IconBrowser,
  IconGift,
  IconMinus as Minus,
  IconGripVertical as GripVerticalIcon,
} from "@tabler/icons-react"
