import {
  IconActivity,
  IconAlertTriangle,
  IconAutomation,
  IconBan,
  IconBell,
  IconBug,
  IconBuilding,
  IconCamera,
  IconCalendarClock,
  IconCalendarEvent,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCopy,
  IconCpu,
  IconDatabase,
  IconDisc,
  IconDeviceFloppy,
  IconDots,
  IconDownload,
  IconEdit,
  IconEye,
  IconFilter,
  IconFingerprint,
  IconFolder,
  IconTopologyStar,
  IconWorld,
  IconHeart,
  IconInfoCircle,
  IconKey,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconNetwork,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconRadar,
  IconRefresh,
  IconRobot,
  IconSearch,
  IconServer,
  IconShield,
  IconStack2,
  IconTerminal2,
  IconTool,
  IconTrash,
  IconTarget,
  IconUpload,
  IconUser,
  IconWorldSearch,
  IconX,
} from "@tabler/icons-react"

/**
 * Semantic icon map for production UI.
 *
 * Pages should consume these semantic entries for product concepts and repeated
 * actions instead of choosing raw icon names locally.
 */
export const semanticIcons = {
  concept: {
    organization: IconBuilding,
    target: IconTarget,
    domain: IconWorld,
    ip: IconServer,
    cidr: IconTopologyStar,
    website: IconWorld,
    subdomain: IconWorldSearch,
    endpoint: IconLink,
    directory: IconFolder,
    screenshot: IconCamera,
    asset: IconStack2,
    vulnerability: IconBug,
    scan: IconRadar,
    scheduledScan: IconCalendarEvent,
    workflow: IconActivity,
    agent: IconServer,
    agentTopology: IconTopologyStar,
    automaticAssignment: IconAutomation,
    server: IconServer,
    tool: IconTool,
    engine: IconCpu,
    database: IconDatabase,
    fingerprint: IconFingerprint,
    wordlist: IconList,
    nucleiRepository: IconFolder,
    notification: IconBell,
    mcp: IconNetwork,
    apiKey: IconKey,
    blacklist: IconBan,
    systemLog: IconTerminal2,
  },
  // Persisted scan provenance is a distinct semantic group from scan actions
  // and lifecycle statuses, so callers can change presentation without
  // assigning an action or status meaning to the trigger source.
  triggerSource: {
    manual: IconUser,
    scheduled: IconCalendarClock,
    ai: IconRobot,
  },
  navigation: {
    overview: IconLayoutDashboard,
    search: IconSearch,
    support: IconHeart,
    about: IconInfoCircle,
  },
  action: {
    add: IconPlus,
    edit: IconEdit,
    delete: IconTrash,
    view: IconEye,
    search: IconSearch,
    filter: IconFilter,
    copy: IconCopy,
    refresh: IconRefresh,
    run: IconPlayerPlay,
    pause: IconPlayerPause,
    stop: IconPlayerStop,
    cancel: IconX,
    save: IconDeviceFloppy,
    upload: IconUpload,
    download: IconDownload,
    more: IconDots,
    schedule: IconCalendarEvent,
  },
  status: {
    enabled: IconCircleCheck,
    disabled: IconBan,
    running: IconActivity,
    paused: IconPlayerPause,
    success: IconCircleCheck,
    cancelled: IconBan,
    failed: IconCircleX,
    warning: IconAlertTriangle,
    error: IconAlertTriangle,
    unknown: IconInfoCircle,
    risk: IconShield,
  },
  metric: {
    latestScan: IconClock,
    serverResources: IconCpu,
    enabledScans: IconCircleCheck,
    cpu: IconCpu,
    memory: IconStack2,
    disk: IconDisc,
    taskSlots: IconStack2,
  },
} as const

export type SemanticIconCategory = keyof typeof semanticIcons
export type SemanticConceptIcon = keyof typeof semanticIcons.concept
