export type BusinessDemoItem = {
  slug: string
  title: string
  group: string
  modulePath: string
  loader: () => Promise<Record<string, unknown>>
}

export const businessDemoItems: BusinessDemoItem[] = [
  {
    slug: "about-dialog",
    title: "About Dialog",
    group: "root",
    modulePath: "@/components/about-dialog",
    loader: () => import("@/components/about-dialog"),
  },
  {
    slug: "animate-ui-components-backgrounds-gravity-stars",
    title: "Gravity Stars",
    group: "animate-ui",
    modulePath: "@/components/animate-ui/components/backgrounds/gravity-stars",
    loader: () => import("@/components/animate-ui/components/backgrounds/gravity-stars"),
  },
  {
    slug: "app-sidebar",
    title: "App Sidebar",
    group: "root",
    modulePath: "@/components/app-sidebar",
    loader: () => import("@/components/app-sidebar"),
  },
  {
    slug: "auth-auth-guard",
    title: "Auth Guard",
    group: "auth",
    modulePath: "@/components/auth/auth-guard",
    loader: () => import("@/components/auth/auth-guard"),
  },
  {
    slug: "auth-auth-layout",
    title: "Auth Layout",
    group: "auth",
    modulePath: "@/components/auth/auth-layout",
    loader: () => import("@/components/auth/auth-layout"),
  },
  {
    slug: "auth-change-password-dialog",
    title: "Change Password Dialog",
    group: "auth",
    modulePath: "@/components/auth/change-password-dialog",
    loader: () => import("@/components/auth/change-password-dialog"),
  },
  {
    slug: "auth-login-boot-screen",
    title: "Login Boot Screen",
    group: "auth",
    modulePath: "@/components/auth/login-boot-screen",
    loader: () => import("@/components/auth/login-boot-screen"),
  },
  {
    slug: "base-node",
    title: "Base Node",
    group: "root",
    modulePath: "@/components/base-node",
    loader: () => import("@/components/base-node"),
  },
  {
    slug: "color-theme-init",
    title: "Color Theme Init",
    group: "root",
    modulePath: "@/components/color-theme-init",
    loader: () => import("@/components/color-theme-init"),
  },
  {
    slug: "common-bauhaus-page-header",
    title: "Bauhaus Page Header",
    group: "common",
    modulePath: "@/components/common/bauhaus-page-header",
    loader: () => import("@/components/common/bauhaus-page-header"),
  },
  {
    slug: "common-bulk-add-urls-dialog",
    title: "Bulk Add Urls Dialog",
    group: "common",
    modulePath: "@/components/common/bulk-add-urls-dialog",
    loader: () => import("@/components/common/bulk-add-urls-dialog"),
  },
  {
    slug: "common-page-header",
    title: "Page Header",
    group: "common",
    modulePath: "@/components/common/page-header",
    loader: () => import("@/components/common/page-header"),
  },
  {
    slug: "common-smart-filter-input",
    title: "Smart Filter Input",
    group: "common",
    modulePath: "@/components/common/smart-filter-input",
    loader: () => import("@/components/common/smart-filter-input"),
  },
  {
    slug: "dashboard-asset-distribution-chart",
    title: "Asset Distribution Chart",
    group: "dashboard",
    modulePath: "@/components/dashboard/asset-distribution-chart",
    loader: () => import("@/components/dashboard/asset-distribution-chart"),
  },
  {
    slug: "dashboard-asset-trend-chart",
    title: "Asset Trend Chart",
    group: "dashboard",
    modulePath: "@/components/dashboard/asset-trend-chart",
    loader: () => import("@/components/dashboard/asset-trend-chart"),
  },
  {
    slug: "dashboard-bauhaus-dashboard-header",
    title: "Bauhaus Dashboard Header",
    group: "dashboard",
    modulePath: "@/components/dashboard/bauhaus-dashboard-header",
    loader: () => import("@/components/dashboard/bauhaus-dashboard-header"),
  },
  {
    slug: "dashboard-dashboard-activity-tabs",
    title: "Dashboard Activity Tabs",
    group: "dashboard",
    modulePath: "@/components/dashboard/dashboard-activity-tabs",
    loader: () => import("@/components/dashboard/dashboard-activity-tabs"),
  },
  {
    slug: "dashboard-dashboard-data-table",
    title: "Dashboard Data Table",
    group: "dashboard",
    modulePath: "@/components/dashboard/dashboard-data-table",
    loader: () => import("@/components/dashboard/dashboard-data-table"),
  },
  {
    slug: "dashboard-dashboard-scan-history",
    title: "Dashboard Scan History",
    group: "dashboard",
    modulePath: "@/components/dashboard/dashboard-scan-history",
    loader: () => import("@/components/dashboard/dashboard-scan-history"),
  },
  {
    slug: "dashboard-dashboard-scheduled-scans",
    title: "Dashboard Scheduled Scans",
    group: "dashboard",
    modulePath: "@/components/dashboard/dashboard-scheduled-scans",
    loader: () => import("@/components/dashboard/dashboard-scheduled-scans"),
  },
  {
    slug: "dashboard-dashboard-stat-cards",
    title: "Dashboard Stat Cards",
    group: "dashboard",
    modulePath: "@/components/dashboard/dashboard-stat-cards",
    loader: () => import("@/components/dashboard/dashboard-stat-cards"),
  },
  {
    slug: "dashboard-recent-vulnerabilities",
    title: "Recent Vulnerabilities",
    group: "dashboard",
    modulePath: "@/components/dashboard/recent-vulnerabilities",
    loader: () => import("@/components/dashboard/recent-vulnerabilities"),
  },
  {
    slug: "dashboard-vuln-severity-chart",
    title: "Vuln Severity Chart",
    group: "dashboard",
    modulePath: "@/components/dashboard/vuln-severity-chart",
    loader: () => import("@/components/dashboard/vuln-severity-chart"),
  },
  {
    slug: "directories-directories-data-table",
    title: "Directories Data Table",
    group: "directories",
    modulePath: "@/components/directories/directories-data-table",
    loader: () => import("@/components/directories/directories-data-table"),
  },
  {
    slug: "directories-directories-view",
    title: "Directories View",
    group: "directories",
    modulePath: "@/components/directories/directories-view",
    loader: () => import("@/components/directories/directories-view"),
  },
  {
    slug: "disk-disk-stat-cards",
    title: "Disk Stat Cards",
    group: "disk",
    modulePath: "@/components/disk/disk-stat-cards",
    loader: () => import("@/components/disk/disk-stat-cards"),
  },
  {
    slug: "endpoints-endpoints-data-table",
    title: "Endpoints Data Table",
    group: "endpoints",
    modulePath: "@/components/endpoints/endpoints-data-table",
    loader: () => import("@/components/endpoints/endpoints-data-table"),
  },
  {
    slug: "endpoints-endpoints-detail-view",
    title: "Endpoints Detail View",
    group: "endpoints",
    modulePath: "@/components/endpoints/endpoints-detail-view",
    loader: () => import("@/components/endpoints/endpoints-detail-view"),
  },
  {
    slug: "FaultyTerminal",
    title: "FaultyTerminal",
    group: "root",
    modulePath: "@/components/faulty-terminal",
    loader: () => import("@/components/faulty-terminal"),
  },
  {
    slug: "fingerprints-arl-fingerprint-data-table",
    title: "Arl Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/arl-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/arl-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-arl-fingerprint-dialog",
    title: "Arl Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/arl-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/arl-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-arl-fingerprint-view",
    title: "Arl Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/arl-fingerprint-view",
    loader: () => import("@/components/fingerprints/arl-fingerprint-view"),
  },
  {
    slug: "fingerprints-ehole-fingerprint-data-table",
    title: "Ehole Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/ehole-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/ehole-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-ehole-fingerprint-dialog",
    title: "Ehole Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/ehole-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/ehole-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-ehole-fingerprint-view",
    title: "Ehole Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/ehole-fingerprint-view",
    loader: () => import("@/components/fingerprints/ehole-fingerprint-view"),
  },
  {
    slug: "fingerprints-fingerprinthub-fingerprint-data-table",
    title: "Fingerprinthub Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingerprinthub-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/fingerprinthub-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-fingerprinthub-fingerprint-dialog",
    title: "Fingerprinthub Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingerprinthub-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/fingerprinthub-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-fingerprinthub-fingerprint-view",
    title: "Fingerprinthub Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingerprinthub-fingerprint-view",
    loader: () => import("@/components/fingerprints/fingerprinthub-fingerprint-view"),
  },
  {
    slug: "fingerprints-fingers-fingerprint-data-table",
    title: "Fingers Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingers-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/fingers-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-fingers-fingerprint-dialog",
    title: "Fingers Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingers-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/fingers-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-fingers-fingerprint-view",
    title: "Fingers Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/fingers-fingerprint-view",
    loader: () => import("@/components/fingerprints/fingers-fingerprint-view"),
  },
  {
    slug: "fingerprints-goby-fingerprint-data-table",
    title: "Goby Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/goby-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/goby-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-goby-fingerprint-dialog",
    title: "Goby Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/goby-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/goby-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-goby-fingerprint-view",
    title: "Goby Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/goby-fingerprint-view",
    loader: () => import("@/components/fingerprints/goby-fingerprint-view"),
  },
  {
    slug: "fingerprints-import-fingerprint-dialog",
    title: "Import Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/import-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/import-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-wappalyzer-fingerprint-data-table",
    title: "Wappalyzer Fingerprint Data Table",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/wappalyzer-fingerprint-data-table",
    loader: () => import("@/components/fingerprints/wappalyzer-fingerprint-data-table"),
  },
  {
    slug: "fingerprints-wappalyzer-fingerprint-dialog",
    title: "Wappalyzer Fingerprint Dialog",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/wappalyzer-fingerprint-dialog",
    loader: () => import("@/components/fingerprints/wappalyzer-fingerprint-dialog"),
  },
  {
    slug: "fingerprints-wappalyzer-fingerprint-view",
    title: "Wappalyzer Fingerprint View",
    group: "fingerprints",
    modulePath: "@/components/fingerprints/wappalyzer-fingerprint-view",
    loader: () => import("@/components/fingerprints/wappalyzer-fingerprint-view"),
  },
  {
    slug: "ip-addresses-ip-addresses-data-table",
    title: "Ip Addresses Data Table",
    group: "ip-addresses",
    modulePath: "@/components/ip-addresses/ip-addresses-data-table",
    loader: () => import("@/components/ip-addresses/ip-addresses-data-table"),
  },
  {
    slug: "ip-addresses-ip-addresses-view",
    title: "Ip Addresses View",
    group: "ip-addresses",
    modulePath: "@/components/ip-addresses/ip-addresses-view",
    loader: () => import("@/components/ip-addresses/ip-addresses-view"),
  },
  {
    slug: "language-switcher",
    title: "Language Switcher",
    group: "root",
    modulePath: "@/components/language-switcher",
    loader: () => import("@/components/language-switcher"),
  },
  {
    slug: "loading-spinner",
    title: "Loading Spinner",
    group: "root",
    modulePath: "@/components/loading-spinner",
    loader: () => import("@/components/loading-spinner"),
  },
  {
    slug: "nav-secondary",
    title: "Nav Secondary",
    group: "root",
    modulePath: "@/components/nav-secondary",
    loader: () => import("@/components/nav-secondary"),
  },
  {
    slug: "nav-system",
    title: "Nav System",
    group: "root",
    modulePath: "@/components/nav-system",
    loader: () => import("@/components/nav-system"),
  },
  {
    slug: "nav-user",
    title: "Nav User",
    group: "root",
    modulePath: "@/components/nav-user",
    loader: () => import("@/components/nav-user"),
  },
  {
    slug: "notifications-notification-drawer",
    title: "Notification Drawer",
    group: "notifications",
    modulePath: "@/components/notifications/notification-drawer",
    loader: () => import("@/components/notifications/notification-drawer"),
  },
  {
    slug: "organization-add-organization-dialog",
    title: "Add Organization Dialog",
    group: "organization",
    modulePath: "@/components/organization/add-organization-dialog",
    loader: () => import("@/components/organization/add-organization-dialog"),
  },
  {
    slug: "organization-edit-organization-dialog",
    title: "Edit Organization Dialog",
    group: "organization",
    modulePath: "@/components/organization/edit-organization-dialog",
    loader: () => import("@/components/organization/edit-organization-dialog"),
  },
  {
    slug: "organization-organization-data-table",
    title: "Organization Data Table",
    group: "organization",
    modulePath: "@/components/organization/organization-data-table",
    loader: () => import("@/components/organization/organization-data-table"),
  },
  {
    slug: "organization-organization-detail-view",
    title: "Organization Detail View",
    group: "organization",
    modulePath: "@/components/organization/organization-detail-view",
    loader: () => import("@/components/organization/organization-detail-view"),
  },
  {
    slug: "organization-organization-list",
    title: "Organization List",
    group: "organization",
    modulePath: "@/components/organization/organization-list",
    loader: () => import("@/components/organization/organization-list"),
  },
  {
    slug: "organization-targets-add-target-dialog",
    title: "Add Target Dialog",
    group: "organization",
    modulePath: "@/components/organization/targets/add-target-dialog",
    loader: () => import("@/components/organization/targets/add-target-dialog"),
  },
  {
    slug: "organization-targets-link-target-dialog",
    title: "Link Target Dialog",
    group: "organization",
    modulePath: "@/components/organization/targets/link-target-dialog",
    loader: () => import("@/components/organization/targets/link-target-dialog"),
  },
  {
    slug: "organization-targets-targets-data-table",
    title: "Targets Data Table",
    group: "organization",
    modulePath: "@/components/organization/targets/targets-data-table",
    loader: () => import("@/components/organization/targets/targets-data-table"),
  },
  {
    slug: "organization-targets-targets-detail-view",
    title: "Targets Detail View",
    group: "organization",
    modulePath: "@/components/organization/targets/targets-detail-view",
    loader: () => import("@/components/organization/targets/targets-detail-view"),
  },
  {
    slug: "PixelBlast",
    title: "PixelBlast",
    group: "root",
    modulePath: "@/components/pixel-blast",
    loader: () => import("@/components/pixel-blast"),
  },
  {
    slug: "prototypes-status-progress-demos",
    title: "Status Progress Demos",
    group: "prototypes",
    modulePath: "@/components/prototypes/status-progress-demos",
    loader: () => import("@/components/prototypes/status-progress-demos"),
  },
  {
    slug: "route-prefetch",
    title: "Route Prefetch",
    group: "root",
    modulePath: "@/components/route-prefetch",
    loader: () => import("@/components/route-prefetch"),
  },
  {
    slug: "route-progress",
    title: "Route Progress",
    group: "root",
    modulePath: "@/components/route-progress",
    loader: () => import("@/components/route-progress"),
  },
  {
    slug: "scan-workflow-create-dialog",
    title: "Workflow Create Dialog",
    group: "scan",
    modulePath: "@/components/scan/workflow/workflow-create-dialog",
    loader: () => import("@/components/scan/workflow/workflow-create-dialog"),
  },
  {
    slug: "scan-workflow-data-table",
    title: "Workflow Data Table",
    group: "scan",
    modulePath: "@/components/scan/workflow/workflow-data-table",
    loader: () => import("@/components/scan/workflow/workflow-data-table"),
  },
  {
    slug: "scan-workflow-edit-dialog",
    title: "Workflow Edit Dialog",
    group: "scan",
    modulePath: "@/components/scan/workflow/workflow-edit-dialog",
    loader: () => import("@/components/scan/workflow/workflow-edit-dialog"),
  },
  {
    slug: "scan-workflow-preset-selector",
    title: "Workflow Preset Selector",
    group: "scan",
    modulePath: "@/components/scan/workflow-preset-selector",
    loader: () => import("@/components/scan/workflow-preset-selector"),
  },
  {
    slug: "scan-history-scan-history-data-table",
    title: "Scan History Data Table",
    group: "scan",
    modulePath: "@/components/scan/history/scan-history-data-table",
    loader: () => import("@/components/scan/history/scan-history-data-table"),
  },
  {
    slug: "scan-history-scan-history-list",
    title: "Scan History List",
    group: "scan",
    modulePath: "@/components/scan/history/scan-history-list",
    loader: () => import("@/components/scan/history/scan-history-list"),
  },
  {
    slug: "scan-history-scan-history-stat-cards",
    title: "Scan History Stat Cards",
    group: "scan",
    modulePath: "@/components/scan/history/scan-history-stat-cards",
    loader: () => import("@/components/scan/history/scan-history-stat-cards"),
  },
  {
    slug: "scan-history-scan-overview",
    title: "Scan Overview",
    group: "scan",
    modulePath: "@/components/scan/history/scan-overview",
    loader: () => import("@/components/scan/history/scan-overview"),
  },
  {
    slug: "scan-initiate-scan-dialog",
    title: "Initiate Scan Dialog",
    group: "scan",
    modulePath: "@/components/scan/initiate-scan-dialog",
    loader: () => import("@/components/scan/initiate-scan-dialog"),
  },
  {
    slug: "scan-quick-scan-dialog",
    title: "Quick Scan Dialog",
    group: "scan",
    modulePath: "@/components/scan/quick-scan-dialog",
    loader: () => import("@/components/scan/quick-scan-dialog"),
  },
  {
    slug: "scan-scan-config-editor",
    title: "Scan Config Editor",
    group: "scan",
    modulePath: "@/components/scan/scan-config-editor",
    loader: () => import("@/components/scan/scan-config-editor"),
  },
  {
    slug: "scan-scan-log-list",
    title: "Scan Log List",
    group: "scan",
    modulePath: "@/components/scan/scan-log-list",
    loader: () => import("@/components/scan/scan-log-list"),
  },
  {
    slug: "scan-scan-progress-dialog",
    title: "Scan Progress Dialog",
    group: "scan",
    modulePath: "@/components/scan/scan-progress-dialog",
    loader: () => import("@/components/scan/scan-progress-dialog"),
  },
  {
    slug: "scan-scan-status-badge",
    title: "Scan Status Badge",
    group: "scan",
    modulePath: "@/components/scan/scan-status-badge",
    loader: () => import("@/components/scan/scan-status-badge"),
  },
  {
    slug: "scan-scheduled-create-scheduled-scan-dialog",
    title: "Create Scheduled Scan Dialog",
    group: "scan",
    modulePath: "@/components/scan/scheduled/create-scheduled-scan-dialog",
    loader: () => import("@/components/scan/scheduled/create-scheduled-scan-dialog"),
  },
  {
    slug: "scan-scheduled-edit-scheduled-scan-dialog",
    title: "Edit Scheduled Scan Dialog",
    group: "scan",
    modulePath: "@/components/scan/scheduled/edit-scheduled-scan-dialog",
    loader: () => import("@/components/scan/scheduled/edit-scheduled-scan-dialog"),
  },
  {
    slug: "scan-scheduled-scheduled-scan-data-table",
    title: "Scheduled Scan Data Table",
    group: "scan",
    modulePath: "@/components/scan/scheduled/scheduled-scan-data-table",
    loader: () => import("@/components/scan/scheduled/scheduled-scan-data-table"),
  },
  {
    slug: "screenshots-screenshots-gallery",
    title: "Screenshots Gallery",
    group: "screenshots",
    modulePath: "@/components/screenshots/screenshots-gallery",
    loader: () => import("@/components/screenshots/screenshots-gallery"),
  },
  {
    slug: "search-search-page",
    title: "Search Page",
    group: "search",
    modulePath: "@/components/search/search-page",
    loader: () => import("@/components/search/search-page"),
  },
  {
    slug: "search-search-pagination",
    title: "Search Pagination",
    group: "search",
    modulePath: "@/components/search/search-pagination",
    loader: () => import("@/components/search/search-pagination"),
  },
  {
    slug: "search-search-result-card",
    title: "Search Result Card",
    group: "search",
    modulePath: "@/components/search/search-result-card",
    loader: () => import("@/components/search/search-result-card"),
  },
  {
    slug: "search-search-results-table",
    title: "Search Results Table",
    group: "search",
    modulePath: "@/components/search/search-results-table",
    loader: () => import("@/components/search/search-results-table"),
  },
  {
    slug: "settings-database-health-database-health-view",
    title: "Database Health View",
    group: "settings",
    modulePath: "@/components/settings/database-health/database-health-view",
    loader: () => import("@/components/settings/database-health/database-health-view"),
  },
  {
    slug: "settings-system-logs-ansi-log-viewer",
    title: "Ansi Log Viewer",
    group: "settings",
    modulePath: "@/components/settings/system-logs/ansi-log-viewer",
    loader: () => import("@/components/settings/system-logs/ansi-log-viewer"),
  },
  {
    slug: "settings-system-logs-log-toolbar",
    title: "Log Toolbar",
    group: "settings",
    modulePath: "@/components/settings/system-logs/log-toolbar",
    loader: () => import("@/components/settings/system-logs/log-toolbar"),
  },
  {
    slug: "settings-system-logs-system-logs-view",
    title: "System Logs View",
    group: "settings",
    modulePath: "@/components/settings/system-logs/system-logs-view",
    loader: () => import("@/components/settings/system-logs/system-logs-view"),
  },
  {
    slug: "settings-workers-agent-architecture-card",
    title: "Agent Architecture Card",
    group: "settings",
    modulePath: "@/components/settings/workers/agent-architecture-card",
    loader: () => import("@/components/settings/workers/agent-architecture-card"),
  },
  {
    slug: "settings-workers-agent-card",
    title: "Agent Card",
    group: "settings",
    modulePath: "@/components/settings/workers/agent-card",
    loader: () => import("@/components/settings/workers/agent-card"),
  },
  {
    slug: "settings-workers-agent-card-compact",
    title: "Agent Card Compact",
    group: "settings",
    modulePath: "@/components/settings/workers/agent-card-compact",
    loader: () => import("@/components/settings/workers/agent-card-compact"),
  },
  {
    slug: "settings-workers-agent-install-dialog",
    title: "Agent Install Dialog",
    group: "settings",
    modulePath: "@/components/settings/workers/agent-install-dialog",
    loader: () => import("@/components/settings/workers/agent-install-dialog"),
  },
  {
    slug: "settings-workers-agent-list-item",
    title: "Agent List Item",
    group: "settings",
    modulePath: "@/components/settings/workers/agent-list-item",
    loader: () => import("@/components/settings/workers/agent-list-item"),
  },
  {
    slug: "settings-workers-architecture-dialog",
    title: "Architecture Dialog",
    group: "settings",
    modulePath: "@/components/settings/workers/architecture-dialog",
    loader: () => import("@/components/settings/workers/architecture-dialog"),
  },
  {
    slug: "settings-workers-architecture-flow",
    title: "Architecture Flow",
    group: "settings",
    modulePath: "@/components/settings/workers/architecture-flow",
    loader: () => import("@/components/settings/workers/architecture-flow"),
  },
  {
    slug: "settings-workers-deploy-terminal-dialog",
    title: "Deploy Terminal Dialog",
    group: "settings",
    modulePath: "@/components/settings/workers/deploy-terminal-dialog",
    loader: () => import("@/components/settings/workers/deploy-terminal-dialog"),
  },
  {
    slug: "settings-workers-metric-progress",
    title: "Metric Progress",
    group: "settings",
    modulePath: "@/components/settings/workers/metric-progress",
    loader: () => import("@/components/settings/workers/metric-progress"),
  },
  {
    slug: "settings-workers-worker-dialog",
    title: "Worker Dialog",
    group: "settings",
    modulePath: "@/components/settings/workers/worker-dialog",
    loader: () => import("@/components/settings/workers/worker-dialog"),
  },
  {
    slug: "settings-workers-worker-list",
    title: "Worker List",
    group: "settings",
    modulePath: "@/components/settings/workers/worker-list",
    loader: () => import("@/components/settings/workers/worker-list"),
  },
  {
    slug: "Shuffle",
    title: "Shuffle",
    group: "root",
    modulePath: "@/components/shuffle",
    loader: () => import("@/components/shuffle"),
  },
  {
    slug: "subdomains-bulk-add-subdomains-dialog",
    title: "Bulk Add Subdomains Dialog",
    group: "subdomains",
    modulePath: "@/components/subdomains/bulk-add-subdomains-dialog",
    loader: () => import("@/components/subdomains/bulk-add-subdomains-dialog"),
  },
  {
    slug: "subdomains-subdomains-data-table",
    title: "Subdomains Data Table",
    group: "subdomains",
    modulePath: "@/components/subdomains/subdomains-data-table",
    loader: () => import("@/components/subdomains/subdomains-data-table"),
  },
  {
    slug: "subdomains-subdomains-detail-view",
    title: "Subdomains Detail View",
    group: "subdomains",
    modulePath: "@/components/subdomains/subdomains-detail-view",
    loader: () => import("@/components/subdomains/subdomains-detail-view"),
  },
  {
    slug: "target-add-target-dialog",
    title: "Add Target Dialog",
    group: "target",
    modulePath: "@/components/target/add-target-dialog",
    loader: () => import("@/components/target/add-target-dialog"),
  },
  {
    slug: "target-all-targets-detail-view",
    title: "All Targets Detail View",
    group: "target",
    modulePath: "@/components/target/all-targets-detail-view",
    loader: () => import("@/components/target/all-targets-detail-view"),
  },
  {
    slug: "target-target-overview",
    title: "Target Overview",
    group: "target",
    modulePath: "@/components/target/target-overview",
    loader: () => import("@/components/target/target-overview"),
  },
  {
    slug: "target-target-settings",
    title: "Target Settings",
    group: "target",
    modulePath: "@/components/target/target-settings",
    loader: () => import("@/components/target/target-settings"),
  },
  {
    slug: "target-targets-data-table",
    title: "Targets Data Table",
    group: "target",
    modulePath: "@/components/target/targets-data-table",
    loader: () => import("@/components/target/targets-data-table"),
  },
  {
    slug: "tools-commands-commands-data-table",
    title: "Commands Data Table",
    group: "tools",
    modulePath: "@/components/tools/commands/commands-data-table",
    loader: () => import("@/components/tools/commands/commands-data-table"),
  },
  {
    slug: "tools-config-add-custom-tool-dialog",
    title: "Add Custom Tool Dialog",
    group: "tools",
    modulePath: "@/components/tools/config/add-custom-tool-dialog",
    loader: () => import("@/components/tools/config/add-custom-tool-dialog"),
  },
  {
    slug: "tools-config-add-tool-dialog",
    title: "Add Tool Dialog",
    group: "tools",
    modulePath: "@/components/tools/config/add-tool-dialog",
    loader: () => import("@/components/tools/config/add-tool-dialog"),
  },
  {
    slug: "tools-config-custom-tools-list",
    title: "Custom Tools List",
    group: "tools",
    modulePath: "@/components/tools/config/custom-tools-list",
    loader: () => import("@/components/tools/config/custom-tools-list"),
  },
  {
    slug: "tools-config-opensource-tools-list",
    title: "Opensource Tools List",
    group: "tools",
    modulePath: "@/components/tools/config/opensource-tools-list",
    loader: () => import("@/components/tools/config/opensource-tools-list"),
  },
  {
    slug: "tools-config-tool-card",
    title: "Tool Card",
    group: "tools",
    modulePath: "@/components/tools/config/tool-card",
    loader: () => import("@/components/tools/config/tool-card"),
  },
  {
    slug: "tools-wordlist-edit-dialog",
    title: "Wordlist Edit Dialog",
    group: "tools",
    modulePath: "@/components/tools/wordlist-edit-dialog",
    loader: () => import("@/components/tools/wordlist-edit-dialog"),
  },
  {
    slug: "tools-wordlist-upload-dialog",
    title: "Wordlist Upload Dialog",
    group: "tools",
    modulePath: "@/components/tools/wordlist-upload-dialog",
    loader: () => import("@/components/tools/wordlist-upload-dialog"),
  },
  {
    slug: "unified-header",
    title: "Unified Header",
    group: "root",
    modulePath: "@/components/unified-header",
    loader: () => import("@/components/unified-header"),
  },
  {
    slug: "vulnerabilities-vulnerabilities-data-table",
    title: "Vulnerabilities Data Table",
    group: "vulnerabilities",
    modulePath: "@/components/vulnerabilities/vulnerabilities-data-table",
    loader: () => import("@/components/vulnerabilities/vulnerabilities-data-table"),
  },
  {
    slug: "vulnerabilities-vulnerabilities-detail-view",
    title: "Vulnerabilities Detail View",
    group: "vulnerabilities",
    modulePath: "@/components/vulnerabilities/vulnerabilities-detail-view",
    loader: () => import("@/components/vulnerabilities/vulnerabilities-detail-view"),
  },
  {
    slug: "vulnerabilities-vulnerability-detail-dialog",
    title: "Vulnerability Detail Dialog",
    group: "vulnerabilities",
    modulePath: "@/components/vulnerabilities/vulnerability-detail-dialog",
    loader: () => import("@/components/vulnerabilities/vulnerability-detail-dialog"),
  },
  {
    slug: "websites-websites-data-table",
    title: "Websites Data Table",
    group: "websites",
    modulePath: "@/components/websites/websites-data-table",
    loader: () => import("@/components/websites/websites-data-table"),
  },
  {
    slug: "websites-websites-view",
    title: "Websites View",
    group: "websites",
    modulePath: "@/components/websites/websites-view",
    loader: () => import("@/components/websites/websites-view"),
  },
]
