export type UiDemoMeta = {
  slug: string
  title: string
  description?: string
  group: string
}

export const uiDemoMeta: UiDemoMeta[] = [
  { slug: "icon", title: "Icon", description: "图标展示与搜索", group: "基础" },
  { slug: "button", title: "Button", description: "按钮样式", group: "基础" },
  { slug: "badge", title: "Badge", description: "标签", group: "基础" },
  { slug: "input", title: "Input", description: "文本输入", group: "表单" },
  { slug: "label", title: "Label", description: "文本标签", group: "表单" },
  { slug: "textarea", title: "Textarea", description: "多行输入", group: "表单" },
  { slug: "checkbox", title: "Checkbox", description: "多选", group: "表单" },
  { slug: "radio-group", title: "RadioGroup", description: "单选", group: "表单" },
  { slug: "switch", title: "Switch", description: "开关", group: "表单" },
  { slug: "toggle", title: "Toggle", description: "单个切换", group: "表单" },
  { slug: "toggle-group", title: "ToggleGroup", description: "多选切换", group: "表单" },
  { slug: "select", title: "Select", description: "下拉选择", group: "表单" },
  { slug: "calendar", title: "Calendar", description: "日期选择", group: "表单" },
  { slug: "datetime-picker", title: "DateTimePicker", description: "日期时间", group: "表单" },
  { slug: "dropzone", title: "Dropzone", description: "文件上传", group: "表单" },
  { slug: "avatar", title: "Avatar", description: "头像", group: "基础" },
  { slug: "alert", title: "Alert", description: "提示", group: "反馈" },
  { slug: "alert-dialog", title: "AlertDialog", description: "确认弹窗", group: "反馈" },
  { slug: "confirm-dialog", title: "ConfirmDialog", description: "业务确认", group: "反馈" },
  { slug: "dialog", title: "Dialog", description: "通用对话框", group: "反馈" },
  { slug: "drawer", title: "Drawer", description: "抽屉", group: "反馈" },
  { slug: "sheet", title: "Sheet", description: "侧边面板", group: "反馈" },
  { slug: "popover", title: "Popover", description: "浮层", group: "反馈" },
  { slug: "copyable-popover-content", title: "CopyablePopoverContent", description: "可复制内容", group: "反馈" },
  { slug: "hover-card", title: "HoverCard", description: "悬浮卡", group: "反馈" },
  { slug: "tooltip", title: "Tooltip", description: "提示", group: "反馈" },
  { slug: "dropdown-menu", title: "DropdownMenu", description: "菜单", group: "反馈" },
  { slug: "collapsible", title: "Collapsible", description: "折叠", group: "布局" },
  { slug: "command", title: "Command", description: "命令面板", group: "布局" },
  { slug: "tabs", title: "Tabs", description: "标签页", group: "布局" },
  { slug: "scroll-area", title: "ScrollArea", description: "滚动区域", group: "布局" },
  { slug: "separator", title: "Separator", description: "分割线", group: "布局" },
  { slug: "table", title: "Table", description: "基础表格", group: "数据" },
  { slug: "unified-data-table", title: "UnifiedDataTable", description: "统一表格", group: "数据" },
  { slug: "sidebar", title: "Sidebar", description: "侧边栏", group: "布局" },
  { slug: "card", title: "Card", description: "卡片", group: "布局" },
  { slug: "skeleton", title: "Skeleton", description: "骨架屏", group: "反馈" },
  { slug: "card-grid-skeleton", title: "CardGridSkeleton", description: "卡片骨架", group: "反馈" },
  { slug: "master-detail-skeleton", title: "MasterDetailSkeleton", description: "主从骨架", group: "反馈" },
  { slug: "data-table-skeleton", title: "DataTableSkeleton", description: "表格骨架", group: "反馈" },
  { slug: "spinner", title: "Spinner", description: "加载", group: "反馈" },
  { slug: "progress", title: "Progress", description: "进度条", group: "反馈" },
  { slug: "shield-loader", title: "ShieldLoader", description: "护盾加载", group: "反馈" },
  { slug: "wave-grid", title: "WaveGrid", description: "波纹背景", group: "可视化" },
  { slug: "chart", title: "Chart", description: "图表", group: "可视化" },
  { slug: "mermaid-diagram", title: "MermaidDiagram", description: "流程图", group: "可视化" },
  { slug: "terminal", title: "Terminal", description: "终端动效", group: "高级" },
  { slug: "terminal-login", title: "TerminalLogin", description: "终端登录", group: "高级" },
  { slug: "yaml-editor", title: "YamlEditor", description: "YAML 编辑器", group: "高级" },
  { slug: "sonner", title: "Sonner", description: "通知", group: "反馈" },
  { slug: "banner", title: "Banner", description: "横幅", group: "品牌" },
  { slug: "status", title: "Status", description: "状态指示", group: "品牌" },
  { slug: "field", title: "Field", description: "字段组合", group: "表单" },
  { slug: "form", title: "Form", description: "表单封装", group: "表单" },
  { slug: "tabs-style-lab", title: "Tabs Styles", description: "标签页风格实验", group: "风格" },
  { slug: "tabs-mini-lab", title: "Small Tabs", description: "小尺寸标签页候选", group: "风格" },
  { slug: "select-style-lab", title: "Select Styles", description: "下拉选择风格实验", group: "风格" },
  { slug: "control-style-lab", title: "Control Styles", description: "表单控件风格实验", group: "风格" },
  { slug: "surface-style-lab", title: "Surface Styles", description: "面板/对话框风格实验", group: "风格" },
  { slug: "overlay-style-lab", title: "Overlay Styles", description: "浮层风格实验", group: "风格" },
  { slug: "progress-style-lab", title: "Progress Styles", description: "进度条风格实验", group: "风格" },
  { slug: "button-style-lab", title: "Button Styles", description: "按钮风格实验", group: "风格" },
  { slug: "input-style-lab", title: "Input Styles", description: "输入框风格实验", group: "风格" },
  { slug: "card-style-lab", title: "Card Styles", description: "卡片风格实验", group: "风格" },
  { slug: "badge-style-lab", title: "Badge Styles", description: "标签风格实验", group: "风格" },
  { slug: "alert-style-lab", title: "Alert Styles", description: "提示风格实验", group: "风格" },
  { slug: "table-style-lab", title: "Table Styles", description: "表格风格实验", group: "风格" },
]
