// Code generated by engine-manifest-artifact-gen. DO NOT EDIT.
// Source: strict engine.v5 engine.json.

package contract

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"unicode/utf8"
)

type FilePath = string

type DirectoryPath = string

type TargetType string

const (
	TargetTypeDomain TargetType = "domain"
	TargetTypeIP     TargetType = "ip"
	TargetTypeCIDR   TargetType = "cidr"
)

type Target struct {
	Type  TargetType
	Value string
}

// SubdomainsInput is the typed lazy handle for the canonical "subdomains" execution role.
type SubdomainsInput interface {
	Path(context.Context) (string, error)
}

// HostPortsInput is the typed lazy handle for the canonical "hostPorts" execution role.
type HostPortsInput interface {
	Path(context.Context) (string, error)
}

// WebsiteURLsInput is the typed lazy handle for the canonical "websiteURLs" execution role.
type WebsiteURLsInput interface {
	Path(context.Context) (string, error)
}

// EndpointURLsInput is the typed lazy handle for the canonical "endpointURLs" execution role.
type EndpointURLsInput interface {
	Path(context.Context) (string, error)
}

type Input struct {
	Subdomains   SubdomainsInput
	HostPorts    HostPortsInput
	WebsiteURLs  WebsiteURLsInput
	EndpointURLs EndpointURLsInput
}

type Config struct {
	// Source: engine.json.execution.configSections["ffuf"].
	Ffuf FfufConfig
}

type FfufConfig struct {
	// Source: engine.json.execution.configSections["ffuf"].defaultEnabled.
	Enabled bool
	// Source: engine.json.execution.configSections["ffuf"].params["wordlist"].
	Wordlist FilePath
	// Source: engine.json.execution.configSections["ffuf"].params["recursion"].
	Recursion bool
	// Source: engine.json.execution.configSections["ffuf"].params["recursion-depth"].
	RecursionDepth int64
	// Source: engine.json.execution.configSections["ffuf"].params["recursion-strategy"].
	RecursionStrategy string
	// Source: engine.json.execution.configSections["ffuf"].params["auto-calibration"].
	AutoCalibration bool
	// Source: engine.json.execution.configSections["ffuf"].params["auto-calibration-mode"].
	AutoCalibrationMode string
	// Source: engine.json.execution.configSections["ffuf"].params["match-codes"].
	MatchCodes string
	// Source: engine.json.execution.configSections["ffuf"].params["concurrency"].
	Concurrency int64
	// Source: engine.json.execution.configSections["ffuf"].params["threads"].
	Threads int64
	// Source: engine.json.execution.configSections["ffuf"].params["rate"].
	Rate int64
	// Source: engine.json.execution.configSections["ffuf"].params["delay"].
	Delay string
	// Source: engine.json.execution.configSections["ffuf"].params["request-timeout"].
	RequestTimeout int64
	// Source: engine.json.execution.configSections["ffuf"].params["timeout"].
	Timeout int64
	// Source: engine.json.execution.configSections["ffuf"].params["follow-redirects"].
	FollowRedirects bool
	// Source: engine.json.execution.configSections["ffuf"].params["http2"].
	Http2 bool
}

type PlatformResources struct {
}

// Subdomain is the Engine-local typed item for canonical result_type "asset.subdomain.v1".
type Subdomain struct {
	DNSName string `json:"dnsName"`
}

// Endpoint is the Engine-local typed item for canonical result_type "asset.endpoint.v1".
type Endpoint struct {
	URL                      string   `json:"url"`
	Host                     string   `json:"host"`
	Title                    string   `json:"title,omitempty"`
	StatusCode               *int     `json:"statusCode,omitempty"`
	ContentLength            *int     `json:"contentLength,omitempty"`
	Location                 string   `json:"location,omitempty"`
	Webserver                string   `json:"webserver,omitempty"`
	ContentType              string   `json:"contentType,omitempty"`
	Tech                     []string `json:"tech,omitempty"`
	ResponseBody             string   `json:"responseBody,omitempty"`
	ResponseBodyTruncated    bool     `json:"responseBodyTruncated,omitempty"`
	Vhost                    *bool    `json:"vhost,omitempty"`
	ResponseHeaders          string   `json:"responseHeaders,omitempty"`
	ResponseHeadersTruncated bool     `json:"responseHeadersTruncated,omitempty"`
}

// HostPort is the Engine-local typed item for canonical result_type "asset.host_port.v1".
type HostPort struct {
	Host string `json:"host"`
	IP   string `json:"ip"`
	Port int    `json:"port"`
}

// Website is the Engine-local typed item for canonical result_type "asset.website.v1".
type Website struct {
	URL             string   `json:"url"`
	Host            string   `json:"host"`
	Title           string   `json:"title,omitempty"`
	StatusCode      *int     `json:"statusCode,omitempty"`
	ContentLength   *int     `json:"contentLength,omitempty"`
	Location        string   `json:"location,omitempty"`
	Webserver       string   `json:"webserver,omitempty"`
	ContentType     string   `json:"contentType,omitempty"`
	Tech            []string `json:"tech,omitempty"`
	ResponseBody    string   `json:"responseBody,omitempty"`
	Vhost           *bool    `json:"vhost,omitempty"`
	ResponseHeaders string   `json:"responseHeaders,omitempty"`
}

// WebsiteTechnology is the Engine-local typed item for canonical result_type "asset.website_technology.v1".
type WebsiteTechnology struct {
	URL  string   `json:"url"`
	Tech []string `json:"tech"`
}

// Screenshot is the Engine-local typed item for canonical result_type "asset.screenshot.v1".
type Screenshot struct {
	URL        string `json:"url"`
	StatusCode *int   `json:"statusCode,omitempty"`
	Image      []byte `json:"image"`
}

// Directory is the Engine-local typed item for canonical result_type "asset.directory.v1".
type Directory struct {
	URL           string `json:"url"`
	Status        int    `json:"status"`
	ContentLength int64  `json:"contentLength"`
	ContentType   string `json:"contentType"`
	Duration      int64  `json:"duration"`
}

// Vulnerability is the Engine-local typed item for canonical result_type "asset.vulnerability.v1".
type Vulnerability struct {
	URL         string         `json:"url"`
	VulnType    string         `json:"vulnType"`
	Severity    string         `json:"severity"`
	Source      string         `json:"source"`
	CVSSScore   *float64       `json:"cvssScore,omitempty"`
	Description string         `json:"description"`
	RawOutput   map[string]any `json:"rawOutput"`
}

func lunafoxValidateResultString(name, value string, nonEmpty, trimmed bool) error {
	if nonEmpty && value == "" {
		return fmt.Errorf("%s is required", name)
	}
	if trimmed && value != strings.TrimSpace(value) {
		return fmt.Errorf("%s must be canonical", name)
	}
	if !utf8.ValidString(value) {
		return fmt.Errorf("%s must be valid UTF-8", name)
	}
	return nil
}

func lunafoxValidateResultHTTPURL(name, value string, forbidUserInfo bool) error {
	parsed, err := url.Parse(value)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return fmt.Errorf("%s is invalid", name)
	}
	if forbidUserInfo && parsed.User != nil {
		return fmt.Errorf("%s must not contain user info", name)
	}
	return nil
}

func lunafoxValidateResultStrings(name string, values []string, required bool) error {
	if required && values == nil {
		return fmt.Errorf("%s is required", name)
	}
	for index, value := range values {
		if !utf8.ValidString(value) {
			return fmt.Errorf("%s[%d] must be valid UTF-8", name, index)
		}
	}
	return nil
}

func lunafoxValidateResultInt(name string, value int64, min, max *int64) error {
	if min != nil && value < *min {
		return fmt.Errorf("%s is below the minimum", name)
	}
	if max != nil && value > *max {
		return fmt.Errorf("%s is above the maximum", name)
	}
	return nil
}

func lunafoxValidateResultNumber(name string, value float64, min, max *float64) error {
	if min != nil && value < *min {
		return fmt.Errorf("%s is below the minimum", name)
	}
	if max != nil && value > *max {
		return fmt.Errorf("%s is above the maximum", name)
	}
	return nil
}

func lunafoxInt64Ptr(value int64) *int64       { return &value }
func lunafoxFloat64Ptr(value float64) *float64 { return &value }

// EncodeSubdomain validates Schema-basics and encodes one Subdomain observation.
func EncodeSubdomain(item Subdomain) (string, error) {
	if err := lunafoxValidateResultString("subdomain dnsname", item.DNSName, true, false); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeEndpoint validates Schema-basics and encodes one Endpoint observation.
func EncodeEndpoint(item Endpoint) (string, error) {
	if err := lunafoxValidateResultString("endpoint url", item.URL, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint host", item.Host, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint title", item.Title, false, false); err != nil {
		return "", err
	}
	if item.StatusCode != nil {
		if err := lunafoxValidateResultInt("endpoint statuscode", int64(*item.StatusCode), lunafoxInt64Ptr(100), lunafoxInt64Ptr(599)); err != nil {
			return "", err
		}
	}
	if item.ContentLength != nil {
		if err := lunafoxValidateResultInt("endpoint contentlength", int64(*item.ContentLength), lunafoxInt64Ptr(0), lunafoxInt64Ptr(2147483647)); err != nil {
			return "", err
		}
	}
	if err := lunafoxValidateResultString("endpoint location", item.Location, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint webserver", item.Webserver, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint contenttype", item.ContentType, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultStrings("endpoint tech", item.Tech, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint responsebody", item.ResponseBody, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("endpoint responseheaders", item.ResponseHeaders, false, false); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeHostPort validates Schema-basics and encodes one HostPort observation.
func EncodeHostPort(item HostPort) (string, error) {
	if err := lunafoxValidateResultString("hostport host", item.Host, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("hostport ip", item.IP, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultInt("hostport port", int64(item.Port), lunafoxInt64Ptr(1), lunafoxInt64Ptr(65535)); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeWebsite validates Schema-basics and encodes one Website observation.
func EncodeWebsite(item Website) (string, error) {
	if err := lunafoxValidateResultString("website url", item.URL, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website host", item.Host, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website title", item.Title, false, false); err != nil {
		return "", err
	}
	if item.StatusCode != nil {
		if err := lunafoxValidateResultInt("website statuscode", int64(*item.StatusCode), lunafoxInt64Ptr(100), lunafoxInt64Ptr(599)); err != nil {
			return "", err
		}
	}
	if item.ContentLength != nil {
		if err := lunafoxValidateResultInt("website contentlength", int64(*item.ContentLength), lunafoxInt64Ptr(0), nil); err != nil {
			return "", err
		}
	}
	if err := lunafoxValidateResultString("website location", item.Location, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website webserver", item.Webserver, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website contenttype", item.ContentType, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultStrings("website tech", item.Tech, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website responsebody", item.ResponseBody, false, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("website responseheaders", item.ResponseHeaders, false, false); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeWebsiteTechnology validates Schema-basics and encodes one WebsiteTechnology observation.
func EncodeWebsiteTechnology(item WebsiteTechnology) (string, error) {
	if err := lunafoxValidateResultString("websitetechnology url", item.URL, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultStrings("websitetechnology tech", item.Tech, true); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeScreenshot validates Schema-basics and encodes one Screenshot observation.
func EncodeScreenshot(item Screenshot) (string, error) {
	if err := lunafoxValidateResultString("screenshot url", item.URL, true, false); err != nil {
		return "", err
	}
	if item.StatusCode != nil {
		if err := lunafoxValidateResultInt("screenshot statuscode", int64(*item.StatusCode), lunafoxInt64Ptr(100), lunafoxInt64Ptr(599)); err != nil {
			return "", err
		}
	}
	if len(item.Image) == 0 {
		return "", fmt.Errorf("screenshot image is required")
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeDirectory validates Schema-basics and encodes one Directory observation.
func EncodeDirectory(item Directory) (string, error) {
	if err := lunafoxValidateResultString("directory url", item.URL, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultInt("directory status", int64(item.Status), lunafoxInt64Ptr(0), lunafoxInt64Ptr(999)); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("directory contenttype", item.ContentType, true, false); err != nil {
		return "", err
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

// EncodeVulnerability validates Schema-basics and encodes one Vulnerability observation.
func EncodeVulnerability(item Vulnerability) (string, error) {
	if err := lunafoxValidateResultString("vulnerability url", item.URL, true, false); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultHTTPURL("vulnerability url", item.URL, true); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("vulnerability vulntype", item.VulnType, true, true); err != nil {
		return "", err
	}
	if err := lunafoxValidateResultString("vulnerability severity", item.Severity, true, false); err != nil {
		return "", err
	}
	if !lunafoxResultEnumAllowed(item.Severity, []string{"unknown", "info", "low", "medium", "high", "critical"}) {
		return "", fmt.Errorf("vulnerability severity has an unsupported value")
	}
	if err := lunafoxValidateResultString("vulnerability source", item.Source, true, false); err != nil {
		return "", err
	}
	if !lunafoxResultEnumAllowed(item.Source, []string{"nuclei"}) {
		return "", fmt.Errorf("vulnerability source has an unsupported value")
	}
	if item.CVSSScore != nil {
		if err := lunafoxValidateResultNumber("vulnerability cvssscore", *item.CVSSScore, lunafoxFloat64Ptr(0), lunafoxFloat64Ptr(10)); err != nil {
			return "", err
		}
	}
	if err := lunafoxValidateResultString("vulnerability description", item.Description, false, false); err != nil {
		return "", err
	}
	if item.RawOutput == nil {
		return "", fmt.Errorf("vulnerability rawoutput is required")
	}
	payload, err := json.Marshal(item)
	if err != nil {
		return "", fmt.Errorf("marshal result: %w", err)
	}
	return string(payload), nil
}

func lunafoxResultEnumAllowed(value string, allowed []string) bool {
	for _, candidate := range allowed {
		if value == candidate {
			return true
		}
	}
	return false
}

// Progress is the Engine-local progress port exposed to hand-written code.
type Progress interface {
	Report(context.Context, string) error
}

// Results is the Engine-local typed result port surface. It is not an
// authorization policy or an output membership declaration.
type Results struct {
	Subdomains          SubdomainSubmitter
	Endpoints           EndpointSubmitter
	HostPorts           HostPortSubmitter
	Websites            WebsiteSubmitter
	WebsiteTechnologies WebsiteTechnologySubmitter
	Screenshots         ScreenshotSubmitter
	Directories         DirectorySubmitter
	Vulnerabilities     VulnerabilitySubmitter
}

// Source: canonical result descriptor "asset.subdomain.v1".
type SubdomainSubmitter interface {
	Submit(context.Context, <-chan Subdomain) error
}

// Source: canonical result descriptor "asset.endpoint.v1".
type EndpointSubmitter interface {
	Submit(context.Context, <-chan Endpoint) error
}

// Source: canonical result descriptor "asset.host_port.v1".
type HostPortSubmitter interface {
	Submit(context.Context, <-chan HostPort) error
}

// Source: canonical result descriptor "asset.website.v1".
type WebsiteSubmitter interface {
	Submit(context.Context, <-chan Website) error
}

// Source: canonical result descriptor "asset.website_technology.v1".
type WebsiteTechnologySubmitter interface {
	Submit(context.Context, <-chan WebsiteTechnology) error
}

// Source: canonical result descriptor "asset.screenshot.v1".
type ScreenshotSubmitter interface {
	Submit(context.Context, <-chan Screenshot) error
}

// Source: canonical result descriptor "asset.directory.v1".
type DirectorySubmitter interface {
	Submit(context.Context, <-chan Directory) error
}

// Source: canonical result descriptor "asset.vulnerability.v1".
type VulnerabilitySubmitter interface {
	Submit(context.Context, <-chan Vulnerability) error
}

type Execution struct {
	Target            Target
	Input             Input
	Config            Config
	PlatformResources PlatformResources
	Workspace         DirectoryPath
	Progress          Progress
	Results           Results
}

type Handler func(context.Context, *Execution) error
