package main

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/yyhuni/lunafox/worker/internal/activity"
	"github.com/yyhuni/lunafox/worker/internal/workflow"
)

func generateDocumentation(templateFile TemplateFile) (string, error) {
	var sb strings.Builder

	// Auto-generated notice (kept as generator metadata)
	sb.WriteString("<!-- This file is auto-generated by go generate. DO NOT EDIT. -->\n")
	sb.WriteString("<!-- Source: worker/internal/workflow/subdomain_discovery/templates.yaml -->\n")
	sb.WriteString("<!-- Generate: go generate ./internal/workflow/subdomain_discovery/ -->\n")
	sb.WriteString(fmt.Sprintf("<!-- Generated At (UTC): %s -->\n\n", time.Now().UTC().Format(time.RFC3339)))

	docMeta, err := requireDocMetadata(templateFile.Metadata)
	if err != nil {
		return "", err
	}
	labels, err := requireLabels(docMeta.Labels)
	if err != nil {
		return "", err
	}

	// Title and overview
	displayName := templateFile.Metadata.DisplayName
	description := templateFile.Metadata.Description
	fmt.Fprintf(&sb, "# %s\n\n", displayName)
	fmt.Fprintf(&sb, "> %s\n\n", description)
	fmt.Fprintf(&sb, "**%s**: %s\n\n", labels["workflow_name"], templateFile.Metadata.Name)
	fmt.Fprintf(&sb, "**Version**: %s\n\n", templateFile.Metadata.Version)
	fmt.Fprintf(&sb, "**Target Types**: %s\n\n", strings.Join(templateFile.Metadata.TargetTypes, ", "))

	// Render sections in configured order
	for _, section := range docMeta.Sections {
		if _, ok := supportedSections[section.ID]; !ok {
			return "", fmt.Errorf("metadata.doc.sections: unsupported section id %s", section.ID)
		}
		if section.Title == "" {
			return "", fmt.Errorf("metadata.doc.sections: title is required for section %s", section.ID)
		}

		fmt.Fprintf(&sb, "## %s\n\n", section.Title)
		switch section.ID {
		case "workflow":
			renderWorkflowSection(&sb, templateFile, labels)
		case "tools":
			renderToolsSection(&sb, templateFile, labels)
		case "examples":
			renderExamplesSection(&sb, templateFile, docMeta, labels)
		case "notes":
			renderNotesSection(&sb, templateFile, labels)
		}
	}

	return sb.String(), nil
}

func requireDocMetadata(meta workflow.WorkflowMetadata) (*workflow.DocMetadata, error) {
	if meta.Doc == nil {
		return nil, fmt.Errorf("metadata.doc is required")
	}
	if len(meta.Doc.Sections) == 0 {
		return nil, fmt.Errorf("metadata.doc.sections is required")
	}
	return meta.Doc, nil
}

func requireLabels(labels map[string]string) (map[string]string, error) {
	if labels == nil {
		return nil, fmt.Errorf("metadata.doc.labels is required")
	}
	for _, key := range requiredLabelKeys {
		if labels[key] == "" {
			return nil, fmt.Errorf("metadata.doc.labels missing key: %s", key)
		}
	}
	return labels, nil
}

func renderWorkflowSection(sb *strings.Builder, templateFile TemplateFile, labels map[string]string) {
	sb.WriteString(labels["workflow_includes"])
	sb.WriteString("\n\n")

	stages := templateFile.Metadata.Stages
	for i, stage := range stages {
		fmt.Fprintf(sb, "### %d. %s (`%s`)\n\n", i+1, stage.Name, stage.ID)
		fmt.Fprintf(sb, "%s\n\n", stage.Description)

		if len(stage.Notes) > 0 {
			fmt.Fprintf(sb, "**%s**:\n", labels["stage_notes"])
			for _, note := range stage.Notes {
				fmt.Fprintf(sb, "- %s\n", note)
			}
			sb.WriteString("\n")
		}

		fmt.Fprintf(sb, "**%s**:\n", labels["properties"])
		if stage.Required {
			fmt.Fprintf(sb, "- %s\n", labels["required_stage"])
		} else {
			fmt.Fprintf(sb, "- %s\n", labels["optional_stage"])
		}
		if stage.Parallel {
			fmt.Fprintf(sb, "- %s\n", labels["supports_parallel"])
		}
		sb.WriteString("\n")
	}
}

func renderToolsSection(sb *strings.Builder, templateFile TemplateFile, labels map[string]string) {
	stages := templateFile.Metadata.Stages

	toolsByStage := make(map[string][]string)
	for toolName, tool := range templateFile.Tools {
		stage := tool.Metadata.Stage
		toolsByStage[stage] = append(toolsByStage[stage], toolName)
	}

	for _, stage := range stages {
		tools := toolsByStage[stage.ID]
		if len(tools) == 0 {
			continue
		}
		sort.Strings(tools)

		fmt.Fprintf(sb, "### %s %s\n\n", stage.Name, labels["stage_tools"])
		for _, toolName := range tools {
			tool := templateFile.Tools[toolName]
			generateToolDoc(sb, toolName, tool, labels)
		}
	}
}

func renderExamplesSection(sb *strings.Builder, templateFile TemplateFile, docMeta *workflow.DocMetadata, labels map[string]string) {
	sb.WriteString("```yaml\n")
	if len(docMeta.ExampleHeader) > 0 {
		for _, line := range docMeta.ExampleHeader {
			if line == "" {
				sb.WriteString("#\n")
				continue
			}
			sb.WriteString("# " + line + "\n")
		}
		sb.WriteString("#\n\n")
	}
	sb.WriteString(generateExampleConfig(templateFile, labels))
	sb.WriteString("```\n\n")
}

func renderNotesSection(sb *strings.Builder, templateFile TemplateFile, labels map[string]string) {
	notes := templateFile.Metadata.Notes
	if len(notes.Global) == 0 && len(notes.Config) == 0 {
		return
	}
	if len(notes.Global) > 0 {
		fmt.Fprintf(sb, "### %s\n\n", labels["global_notes"])
		for _, note := range notes.Global {
			fmt.Fprintf(sb, "- %s\n", note)
		}
		sb.WriteString("\n")
	}
	if len(notes.Config) > 0 {
		fmt.Fprintf(sb, "### %s\n\n", labels["config_notes"])
		for _, note := range notes.Config {
			fmt.Fprintf(sb, "- %s\n", note)
		}
		sb.WriteString("\n")
	}
}

func generateToolDoc(sb *strings.Builder, toolName string, tool activity.CommandTemplate, labels map[string]string) {
	fmt.Fprintf(sb, "#### %s\n\n", tool.Metadata.DisplayName)
	fmt.Fprintf(sb, "**%s**: `%s`\n\n", labels["tool_name"], toolName)

	fmt.Fprintf(sb, "**%s**: %s\n\n", labels["description"], tool.Metadata.Description)

	if tool.Metadata.Warning != "" {
		fmt.Fprintf(sb, "⚠️ **%s**: %s\n\n", labels["warning"], tool.Metadata.Warning)
	}

	fmt.Fprintf(sb, "**%s**:\n\n", labels["base_command"])
	sb.WriteString("```shell\n")
	sb.WriteString(tool.BaseCommand)
	if !strings.HasSuffix(tool.BaseCommand, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString("```\n\n")

	if len(tool.InternalParams) > 0 {
		fmt.Fprintf(sb, "**%s**:\n", labels["internal_params"])
		keys := make([]string, 0, len(tool.InternalParams))
		for key := range tool.InternalParams {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(sb, "- `%s`: %v\n", key, tool.InternalParams[key])
		}
		sb.WriteString("\n")
	}

	if len(tool.Metadata.Notes) > 0 {
		fmt.Fprintf(sb, "**%s**:\n", labels["tool_notes"])
		for _, note := range tool.Metadata.Notes {
			fmt.Fprintf(sb, "- %s\n", note)
		}
		sb.WriteString("\n")
	}

	renderParamTable := func(title string, params []activity.Parameter) {
		if len(params) == 0 {
			return
		}
		fmt.Fprintf(sb, "**%s**:\n\n", title)
		fmt.Fprintf(sb, "| %s | %s | %s | %s | %s |\n",
			labels["parameter"], labels["type"], labels["default"], labels["required"], labels["description"])
		sb.WriteString("|-----------|------|---------|----------|-------------|\n")

		for _, param := range params {
			typeStr := param.ConfigSchema.Type
			defaultStr := "-"
			if param.ConfigSchema.Default != nil {
				defaultStr = fmt.Sprintf("%v", param.ConfigSchema.Default)
			}
			requiredStr := labels["no"]
			if param.ConfigSchema.Required {
				requiredStr = labels["yes"]
			}
			desc := param.Documentation.Description

			fmt.Fprintf(sb, "| `%s` | %s | %s | %s | %s |\n",
				param.ConfigSchema.Key, typeStr, defaultStr, requiredStr, desc)
		}
		sb.WriteString("\n")
	}

	renderParamTable(labels["runtime_parameters"], tool.RuntimeParams)
	renderParamTable(labels["cli_parameters"], tool.CLIParams)

	fmt.Fprintf(sb, "**%s**:\n\n", labels["config_example"])
	sb.WriteString("```yaml\n")
	fmt.Fprintf(sb, "%s:\n", tool.Metadata.Stage)
	sb.WriteString("  enabled: true\n")
	sb.WriteString("  tools:\n")
	fmt.Fprintf(sb, "    %s:\n", toolName)
	sb.WriteString("      enabled: true\n")

	for _, param := range append(append([]activity.Parameter{}, tool.RuntimeParams...), tool.CLIParams...) {
		if param.ConfigExample.ShowAs == "hidden" {
			continue
		}
		value := param.ConfigExample.Value
		if value == nil {
			if param.ConfigSchema.Required {
				value = "<required>"
			} else {
				value = "<optional>"
			}
		}
		var line string
		if param.ConfigExample.ShowAs == "value" {
			line = fmt.Sprintf("      %s: %v", param.ConfigSchema.Key, value)
		} else if param.ConfigExample.ShowAs == "comment" {
			line = fmt.Sprintf("      # %s: %v", param.ConfigSchema.Key, value)
		}
		if param.ConfigExample.Comment {
			desc := param.Documentation.Description
			if desc != "" {
				line = fmt.Sprintf("%s  # %s", line, desc)
			}
		}
		if line != "" {
			sb.WriteString(line + "\n")
		}
	}
	sb.WriteString("```\n\n")
}

func generateExampleConfig(templateFile TemplateFile, labels map[string]string) string {
	var sb strings.Builder

	stages := templateFile.Metadata.Stages
	toolsByStage := make(map[string][]string)
	for toolName, tool := range templateFile.Tools {
		stage := tool.Metadata.Stage
		toolsByStage[stage] = append(toolsByStage[stage], toolName)
	}

	for i, stage := range stages {
		tools := toolsByStage[stage.ID]
		if len(tools) == 0 {
			continue
		}

		sort.Strings(tools)

		fmt.Fprintf(&sb, "# %s %d: %s", labels["stage_prefix"], i+1, stage.Name)
		if stage.Parallel {
			fmt.Fprintf(&sb, " (%s)", labels["parallel_execution"])
		}
		sb.WriteString("\n")

		if stage.Description != "" {
			fmt.Fprintf(&sb, "# %s\n", stage.Description)
		}

		fmt.Fprintf(&sb, "%s:\n", stage.ID)
		if stage.Required {
			sb.WriteString("  enabled: true\n")
		} else {
			sb.WriteString("  enabled: false\n")
		}
		sb.WriteString("  tools:\n")

		for _, toolName := range tools {
			tool := templateFile.Tools[toolName]
			generateToolConfig(&sb, toolName, tool)
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func generateToolConfig(sb *strings.Builder, toolName string, tool activity.CommandTemplate) {
	if tool.Metadata.Description != "" {
		fmt.Fprintf(sb, "    # %s\n", tool.Metadata.Description)
	}
	fmt.Fprintf(sb, "    %s:\n", toolName)
	sb.WriteString("      enabled: true\n")
	for _, param := range append(append([]activity.Parameter{}, tool.RuntimeParams...), tool.CLIParams...) {
		if param.ConfigExample.ShowAs == "hidden" {
			continue
		}
		key := param.ConfigSchema.Key
		value := param.ConfigExample.Value
		if value == nil {
			if param.ConfigSchema.Required {
				value = "<required>"
			} else {
				value = "<optional>"
			}
		}

		var line string
		if param.ConfigExample.ShowAs == "value" {
			line = fmt.Sprintf("      %s: %v", key, value)
		} else if param.ConfigExample.ShowAs == "comment" {
			line = fmt.Sprintf("      # %s: %v", key, value)
		}

		if param.ConfigExample.Comment {
			desc := param.Documentation.Description
			if desc != "" {
				line = fmt.Sprintf("%s  # %s", line, desc)
			}
		}

		if line != "" {
			sb.WriteString(line + "\n")
		}
	}
}
