import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import path from "node:path"

const source = readFileSync(path.resolve(process.cwd(), "components/shared/loading/content-handoff.tsx"), "utf8")
const globals = readFileSync(path.resolve(process.cwd(), "app/globals.css"), "utf8")
const uiFoundationGuide = readFileSync(path.resolve(process.cwd(), "components/ui/README.md"), "utf8")

function cssRule(selector: string) {
  const start = globals.indexOf(`${selector} {`)
  expect(start).toBeGreaterThanOrEqual(0)
  const end = globals.indexOf("\n}", start)
  expect(end).toBeGreaterThan(start)
  return globals.slice(start, end)
}

function expectNoCssRule(selector: string) {
  expect(globals).not.toContain(`${selector} {`)
}

describe("content-handoff contract", () => {
  it("owns shared skeleton-to-content overlap handoff metadata", () => {
    expect(source).toContain("export function ContentHandoff")
    expect(source).toContain("owner: string")
    expect(source).toContain("layer?: LoadingLayer")
    expect(source).toContain("intent?: LoadingIntent")
    expect(source).toContain("isLoading: boolean")
    expect(source).toContain("skeleton: React.ReactNode")
    expect(source).toContain("mountContentWhileLoading?: boolean")
    expect(source).toContain("prepareContentBeforeHandoff?: boolean")
    expect(source).toContain("prepareContentBeforeHandoff = false")
    expect(source).toContain("shouldMountContentWhileLoading")
    expect(source).toContain("CONTENT_HANDOFF_STABLE_FRAMES")
    expect(source).toContain("window.requestAnimationFrame")
    expect(source).toContain('position: "absolute" as const')
    expect(source).toContain('overflow: "clip"')
    expect(source).toContain('transitionMode?: "crossfade" | "replace"')
    expect(source).toContain('transitionMode = "crossfade"')
    expect(source).toContain('if (transitionMode === "replace")')
    expect(source).toContain("skeletonClassName?: string")
    expect(source).toContain('className={cn("loading-handoff__skeleton", skeletonClassName)}')
    expect(source).toContain("data-loading-hidden")
    expect(source).toContain("measureContentIntrinsicHeight")
    expect(source).toContain("stateNode.children")
    expect(source).toContain("rootsWithGeometry")
    expect(source).toContain("stateNode.scrollHeight")
    expect(source).toContain("hasCommittedContent")
    expect(source).toContain("data-loading-content-ready")
    expect(source).toContain("contentHeight <= 0")
    expect(source).toContain("syncObservedRoots")
    expect(source).toContain("MutationObserver")
    expect(source).toContain("observer?.unobserve(root)")
    expect(source).toContain("getLoadingOwnerAttributes")
    expect(source).toContain("getLoadingStructureSlotAttributes")
    expect(source).toContain('layer = "section"')
    expect(source).toContain('intent = "data"')
    expect(source).toContain("getLoadingOwnerAttributes({ owner, layer, intent })")
    expect(source).toContain("data-slot=\"content-handoff\"")
    expect(source).toContain('getLoadingStructureSlotAttributes("surface")')
    expect(source).toContain('data-loading-structure-state="skeleton"')
    expect(source).toContain('data-loading-structure-state="content"')
    expect(source).toContain("ContentHandoff requires a non-empty owner.")
    expect(source).not.toContain("reservedHeight")
    expect(source).not.toContain("preparedHeight")
    expect(source).not.toContain("minHeight:")
    expect(source).not.toContain("data-loading-geometry-prepared")
    expect(source).not.toContain("data-loading-prepared-")
  })

  it("uses shared overlap handoff motion with reduced-motion fallback", () => {
    const loadingRule = cssRule('.loading-handoff[data-loading-phase="loading"]')
    const loadingSkeletonRule = cssRule('.loading-handoff[data-loading-phase="loading"] > .loading-handoff__skeleton')
    const hiddenContentRule = cssRule('.loading-handoff[data-loading-phase="loading"] > .loading-handoff__content[data-loading-hidden="true"]')
    const handoffSkeletonRule = cssRule('.loading-handoff[data-loading-phase="handoff"] > .loading-handoff__skeleton')
    const handoffReadySkeletonRule = cssRule('.loading-handoff[data-loading-phase="handoff"][data-loading-content-ready="true"] > .loading-handoff__skeleton')
    const handoffContentRule = cssRule('.loading-handoff[data-loading-phase="handoff"] > .loading-handoff__content')
    const handoffHiddenContentRule = cssRule('.loading-handoff[data-loading-phase="handoff"] > .loading-handoff__content[data-loading-hidden="true"]')
    const contentRule = cssRule('.loading-handoff[data-loading-phase="content"]')
    const settledContentRule = cssRule('.loading-handoff[data-loading-phase="content"] > .loading-handoff__content')

    expect(globals).toContain(".loading-handoff")
    expect(globals).toContain(".loading-handoff__skeleton")
    expect(globals).toContain(".loading-handoff__content")
    expect(globals).toContain('.loading-handoff[data-loading-phase="loading"] > .loading-handoff__content[data-loading-hidden="true"]')
    expect(globals).toContain('.loading-handoff[data-loading-phase="loading"] {')
    expect(loadingRule).toContain("display: grid;")
    expect(loadingRule).toContain("position: relative;")
    expect(loadingRule).toContain("grid-template-rows: minmax(0, 1fr);")
    expect(loadingSkeletonRule).toContain("grid-area: 1 / 1;")
    expect(hiddenContentRule).toContain("visibility: hidden;")
    expect(handoffSkeletonRule).toContain("grid-area: 1 / 1;")
    expect(handoffSkeletonRule).not.toContain("loading-handoff-skeleton-exit")
    expect(handoffReadySkeletonRule).toContain("loading-handoff-skeleton-exit")
    expect(handoffContentRule).toContain("grid-area: 1 / 1;")
    expect(handoffHiddenContentRule).toContain("visibility: hidden;")
    expect(handoffHiddenContentRule).toContain("pointer-events: none;")
    expect(contentRule).toContain("display: grid;")
    expect(contentRule).toContain("grid-template-rows: minmax(0, 1fr);")
    expect(settledContentRule).toContain("grid-area: 1 / 1;")
    expect(globals).toContain("animation: loading-handoff-skeleton-exit var(--motion-duration-reveal) var(--motion-ease-standard) both;")
    expect(globals).toContain("@keyframes loading-handoff-skeleton-exit")
    expect(globals).not.toContain("loading-handoff-content-enter")
    expect(globals).not.toContain("loading-handoff-content-enter 280ms")
    expect(globals).not.toContain("translateY(2px)")
    expect(globals).toContain(".loading-handoff__skeleton,")
    expect(globals).toContain(".loading-handoff__content,")
    expect(globals).toContain("animation: none !important;")
    expect(hiddenContentRule).toContain("grid-area: 1 / 1;")
    expectNoCssRule('.loading-handoff[data-loading-phase="loading"] .loading-handoff__skeleton')
    expectNoCssRule('.loading-handoff[data-loading-phase="loading"] .loading-handoff__content[data-loading-hidden="true"]')
    expectNoCssRule('.loading-handoff[data-loading-phase="handoff"] .loading-handoff__skeleton')
    expectNoCssRule('.loading-handoff[data-loading-phase="handoff"] .loading-handoff__content')
  })

  it("documents the readiness-signal deadlock guardrail", () => {
    expect(uiFoundationGuide).toContain("### ContentHandoff Readiness Standard")
    expect(uiFoundationGuide).toContain("If `isLoading` is driven by a readiness signal emitted from inside the children")
    expect(uiFoundationGuide).toContain("the caller MUST pass `mountContentWhileLoading`")
    expect(uiFoundationGuide).toContain("out of the visible loading Grid track")
    expect(uiFoundationGuide).toContain("MUST NOT write late measurements, `min-height`, or any other dynamic geometry")
    expect(uiFoundationGuide).toContain("only to delay readiness until its first frame is stable")
    expect(uiFoundationGuide).toContain("readiness gate only")
    expect(uiFoundationGuide).toContain("If readiness is owned outside the children but the resolved child is lazy or dynamic")
    expect(uiFoundationGuide).toContain("MUST keep the outgoing skeleton visible until committed content has positive natural geometry")
    expect(uiFoundationGuide).toContain("Never wire a loader so that `isLoading` prevents the child from mounting")
    expect(uiFoundationGuide).toContain("permanent skeleton/loading deadlock")
  })
})
